### ISSUE TITLE
parsing times with AM and PM

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/lubridate#100]
ymd_hms should recognize AM and PM and parse times accordingly. Or, at least, there should be a parsing function specifically for that format.

Garrett

**Comment by jsramos** [comment]
Using lubridate 1.3.3.

<code>parse_date_time(c('12/17/1996 04:00:00 PM','4/18/1950 0130'), c('%m/%d/%Y %I:%M:%S %p','%m/%d/%Y %H%M'))</code>

Result is
<code>[1] NA NA
Warning message:
All formats failed to parse. No formats found. </code>

1st string should parse with 1st format. 2nd string should parse with 2nd format. I've tried all combinations, but to no avail. Removing the <code>%p</code> gets me a little further, but doesn't do what it says. Definitely don't want to use as.Date, nor as.POSIXct. A little help here?

**Comment by vspinu** [comment]
On current version of lubridate you get:

```
> parse_date_time(c('12/17/1996 04:00:00 PM','4/18/1950 0130'), c("mdYHMS", "mdYHM"))
[1] "1996-12-17 04:00:00 UTC" NA                       
Warning message:
 1 failed to parse. 
```

Which still fails on the second format. That's a bug. 

BTW, the above is equivalent to 

```
mdy_hms(c('12/17/1996 04:00:00 PM','4/18/1950 0130'), truncated = 1)
[1] "1996-12-17 04:00:00 UTC" NA                       
Warning message:
 1 failed to parse. 
```

**Comment by jsramos** [comment]
Thanks for the reply. Although your example manages to parse the 1st string, it is still wrong. It's interpreting 04:00:00 PM as 0400 UTC, that's 4AM. Is this a bug as well?

**Comment by vspinu** [comment]
> Is this a bug as well? 

It's a not a bug for `parse_date_time` as documentation says:

```
     ‘p’ AM/PM indicator in the locale.  Used in conjunction with ‘I’
          and *not* with ‘H’.  An empty string in some locales.
```

But it's likely a bug for `mdy_hms`. I will check that out.

**Comment by jsramos** [comment]
As you can see, the snippet in my original comment is using <code>%I</code> for 12-hour field, along with <code>%p</code>.

I found another strange thing, though. I tested my original issue on a Win7 PC and none of the date strings could be parsed. I'm repeating the exercise on a MacOSX Yosemite and lo and behold:

<code>> parse_date_time(c('12/17/1996 04:00:00 PM','4/18/1950 0130'), c('%m/%d/%Y %I:%M:%S %p','%m/%d/%Y %H%M'))

[1] "1996-12-17 16:00:00 UTC" NA

Warning message:
1 failed to parse.</code>

Not only parses the string, but it does so correctly. The 4PM is parsed as 1600 hours.

Hope this helps you squashing this Zerg :+1:

**Comment by vspinu** [comment]
> As you can see, the snippet in my original comment is using %I for 12-hour field, along with %p.

Ah. Sorry about that. 

> Not only parses the string, but it does so correctly. The 4PM is parsed as 1600 hours.

You might be using different versions of lubridate. The CRAN version is by now quite outdated. PM/AM are also locale specific. You should check that you have english locate everywhere. Otherwise  there indeed might be system differences. 

In any case I plan to expand internal C parser to handle AaBbp formats natively, so all these problems with AM/PM and alphabetic months will be done with pretty soon now. 

I have opened a dedicated #327 issue for this. Please continue there if you spot any further related issues.

**Comment by jsramos** [comment]
Thanks a lot. Will try setting locales for all boxes and update lubridate to the most recent version and report back.

**Comment by rhpoon** [comment]
I ran into problems for time = 00:00:00 as following, it wont pick up the time and hence subsequent passing could become problems:

> time <- ymd_hms("2010-12-13 00:00:01")
> time
[1] "2010-12-13 00:00:01 UTC"
> time <- ymd_hms("2010-12-13 00:00:00")
> hms(time)
[1] "2010H -12M -13S"
