### ISSUE TITLE
Method not defined for "Interval `%within%` list"

### ISSUE THREAD

**Issue by mcanouil** [tidyverse/lubridate#1001]
Hi,

it seems that using an interval as LHS and a list of intervals as RHS is not implemented.
The current documentation implies it is supposed to work:
* __a__  An interval or date-time object.
* __b__ Either an interval vector, or a list of intervals.

``` r
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> Les objets suivants sont masqués depuis 'package:base':
#> 
#>     date, intersect, setdiff, union
int <- interval(ymd("2001-01-01"), ymd("2002-01-01"))
int2 <- interval(ymd("2001-06-01"), ymd("2002-01-01"))
int2 %within% list(int)
#> Error in int2 %within% list(int): No %within% method with signature a = Interval,  b = list
```
<sup>Created on 2021-10-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mcanouil** [comment]
``I wanted to be sure, if the documentation is wrong, or if the method is missing because from the documentation and I quote, LHS should be "An interval or date-time object" and RHS "Either an interval vector, or a list of intervals", meaning the following combinations are supposed to work :
* date %within% c(interval)
* interval %within% c(interval)
* date %within% list(interval)
* interval %within% list(interval)

``` r
library(lubridate)

int <- interval(ymd("2001-01-01"), ymd("2002-01-01"))
int2 <- interval(ymd("2001-06-01"), ymd("2002-01-01"))

ymd("2001-05-03") %within% int
#> TRUE
int2 %within% int
#> TRUE
ymd("2001-05-03") %within% list(int)
#> TRUE
int2 %within% list(int)
#> Error in int2 %within% list(int) :
#>   No %within% method with signature a = Interval,  b = list
```

I'll have a look at how the other methods are implemented to add the missing combination via a PR (if no one else  take care of it first).

**Comment by vspinu** [comment]
Ok, I see. Actually (int, int) is working, so should be `(int, list)`. You are right.

**Comment by vspinu** [comment]
I took care of it. Thanks for bringing in!
