### ISSUE TITLE
Coercion of a duration into a character and back does not work

### ISSUE THREAD

**Issue by tvatter** [tidyverse/lubridate#1005]
Hi,

While coercing a duration into a character work, the output of the coercion into a character can't be coerced back into a duration.

```r
(x <- duration(1, "years"))  # [1] "31557600s (~1 years)"
(y <- as.character(x))         # [1] "31557600s (~1 years)"
(z <- as.duration(y))           # [1] NA
```

 I understand that the basic purpose of the parser is different and that this behavior is expected. However, I just encountered a situation where this is problematic:

```r
df <- tibble(x = duration(1, "years"))     # x is a duration
tmp <- tempfile(); write_csv(df, tmp)    # write the df to file
df2 <- read_csv(tmp)                           # x is now a character which can't be easily coerced
```

Now, I get that one could just convert a duration as a numeric before writing, via `mutate(across(where(is.duration), as.numeric))` or the "old" way `mutate_if(is.duration, as.numeric)`. But it seems like an unnecessary burden to the user, especially since this behavior is not, to the best of my knowledge, documented.

I will also file a bug report in `readr`. While I understand that `readr` can't be expected to know whether to coerce to numeric or character for every object class out there, I would have expected that classes from the `tidyverse` packages should be supported seamlessly. However, it seems that the "responsibility" of providing a parser for the duration class should be on `lubridate`.

Thoughts?

**Comment by tvatter** [comment]
Edit, I see that this isn't a new problem with `readr`:

- https://github.com/tidyverse/readr/issues/1037
- https://github.com/tidyverse/readr/issues/549

**Comment by surdina** [comment]
I just came across the same thing!

Perhaps rather naively, it also seems to me that `as.duration()` should be able to handle the string format it produces. The information is still there, and the coercion could be achieved by reading the string and ignoring everything after `s`.

Right now, for character input, `as.duration()` calls `as.period()`, which calls `parse_period()`, which calls `C_parse_period()`. It's basically attempting to convert the duration column in string form to a period column and back.  

Would it make sense to check if the string is in that non-numeric display duration format? For instance inside of `as.duration()` in case `as.period()` yields `NA`, or -- if that's too slow -- within `C_parse_period()`.

**Comment by vspinu** [comment]
Thanks or bringing it up.
