### ISSUE TITLE
`round_date` compares days to seconds, leading to incorrect results

### ISSUE THREAD

**Issue by jaganmn** [tidyverse/lubridate#1008]
It seems that https://github.com/tidyverse/lubridate/commit/f4a4e426588729c0b781613ddc0fa688aaf29b68 has introduced a bug causing `round_date(x = <Date>, unit = <"2 days" or longer>)` to return rounded Dates that are either (a) wrong or (b) right, but only by coincidence. See my [answer](https://stackoverflow.com/questions/70222688/round-date-function-returns-floor-date-instead-of-rounded-date/70224473#70224473) to a recent SO question, which explains the bug.

To emphasize the extent of the regression, here is a transparent example of `round_date` failing:

``` r
library("lubridate")
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
R.version.string
#> [1] "R version 4.1.2 (2021-11-01)"
packageVersion("lubridate")
#> [1] '1.8.0'
round_date(seq(as.Date("2021-01-01"), as.Date("2021-01-31"), by = 1), unit = "month")
#>  [1] "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01"
#>  [6] "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01"
#> [11] "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01"
#> [16] "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01"
#> [21] "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01"
#> [26] "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01" "2021-01-01"
#> [31] "2021-01-01"
```

where it is understood that the second half of the output should contain `"2021-02-01"`...

**Comment by jaganmn** [comment]
Bump? I suspect you'll want this fixed sooner rather than later...

It's really bad luck that none of your regression tests in `test-round.R` catch this. For instance, I see:

```r
expect_equal(round_date(as.Date(​x​), ​"​month​"​), as.Date(​"​2009-08-01​"​))
```

but that is one case where the right answer is obtained entirely by accident. And there are several other tests with `x = <Date>` and `unit = "week"`... I guess those are passing, too...

**Comment by pchtsp** [comment]
I just got here to say I'm having the same issue. @jaganmn would you care doing a PR to the repo? you seem to know very well what could be changed, including adding a couple unit tests. 
It's likely the maintainer is busy... thanks!

**Comment by jaganmn** [comment]
OK - done. Let me know if you find something amiss.

**Comment by vspinu** [comment]
Damn it. Sorry guys for being so late on this. I missed the original notification.  It's indeed pretty crazy that the regression wasn't picked by the tests. It was an unfortunate typo.
