### ISSUE TITLE
referenced `%within%` page is 404 on package website

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/lubridate#1009]
The following page has "See also" entry for `%within%` operator:
https://lubridate.tidyverse.org/reference/interval.html

But the linked page is 404:
https://lubridate.tidyverse.org/reference/%within%.html

The correct link:
https://lubridate.tidyverse.org/reference/within-interval.html

**Comment by vspinu** [comment]
It has been fixed. Thanks!
