### ISSUE TITLE
round_date rounds "2017-06-24" as "2017-06-01" where it should be "2017-07-01"

### ISSUE THREAD

**Issue by hidekoji** [tidyverse/lubridate#1014]
With lubridate version 1.8.0, `round_date` rounds "2017-06-24" as "2017-06-01" where it should be "2017-07-01".

I noticed if I pass POSIXct (i.e. `ymd_hms("2017-06-24 00:00:00")`) it works ok but passing Date (i.e. `ymd("2017-06-24")`) returns incorrect result.

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
    x <- ymd("2017-06-24")
    x2 <- ymd_hms("2017-06-24 00:00:00")
    round_date(x, unit = "month")
#> [1] "2017-06-01"
    round_date(x2, unit = "month")
#> [1] "2017-07-01 UTC"
```

<sup>Created on 2022-01-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vspinu** [comment]
I cannot reproduce this. What OS is this? What locale? Can you reproduce with clean R session?
I  don't see how this could be happening. 
```R
> x <- ymd("2017-06-24")
> x2 <- ymd_hms("2017-06-24 00:00:00")
> round_date(x, unit = "month")
[1] "2017-07-01"
> round_date(x2, unit = "month")
[1] "2017-07-01 UTC"
```

**Comment by hidekoji** [comment]
It's macOS Big Sur (11.6)

```r

> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0  Matrix_1.3-3    tools_4.1.0     survival_3.2-11 splines_4.1.0   grid_4.1.0      lattice_0.20-44
```

**Comment by hidekoji** [comment]
By the way, is this fixed with the recent commit?

https://github.com/tidyverse/lubridate/commit/0e6970a63e0ee642b2470af6cf4f7a92226250ad#diff-6530cdec4c90e2f31d664264eb6d626ea1f827711403431a33f4afe27c3d8165

**Comment by vspinu** [comment]
Arh, right. That's the thing most likely. Can you try github version?

**Comment by hidekoji** [comment]
Yes, it works with the Github version.
