### ISSUE TITLE
Printing issue with lubridate::as_datetime(Inf) output

### ISSUE THREAD

**Issue by fzenoni** [tidyverse/lubridate#1020]
There is a confusing behavior when executing:

```r
lubridate::as_datetime(Inf)
```
as the output is `NA`.

However,
```r
is.na(lubridate::as_datetime(Inf))
```
returns `FALSE`.

**Comment by vspinu** [comment]
This is how POSIXct objects are printed in R unfortunately. It's not lubridate specific:

```R
> as.POSIXct(Inf)
[1] NA
> as.numeric(as.POSIXct(Inf))
[1] Inf
```

I am pretty sure we don't want to overwrite the default printing method in lubridate. Feel free to report this to R bug tracker proper.
