### ISSUE TITLE
inconsistent (and incorrect) behaviour in interval class when using Inf

### ISSUE THREAD

**Issue by yfarjoun** [tidyverse/lubridate#1021]
I'm trying to work with half-infinite date intervals i.e. something of the sort of `interval(today(),Inf)`...but that doesn't work.

Instead I've been using something like `interval(today(),today()+Inf)` which does work, however, when I do the same for the "start" it fails: 

```r
> interval(today(),today())
[1] 2022-02-23 UTC--2022-02-23 UTC
> interval(today()-Inf,today())
[1] NA--NA
> interval(today()+Inf,today())
[1] NA--NA
> interval(today(),today()+Inf)
[1] 2022-02-23 UTC--NA
> interval(today(),today()-Inf)
[1] 2022-02-23 UTC--NA
```

Also, this isn't a "display only" problem: 

```r
> (today()-1) %within% interval(today()-Inf,today())
[1] TRUE
> (today()+1) %within% interval(today()-Inf,today())
[1] TRUE <<<<<<<<<<<<<<<<-------NOT TRUE! should be FALSE
> (today()+1) %within% interval(today(),today()+Inf)
[1] TRUE
> (today()-1) %within% interval(today(),today()+Inf)
[1] FALSE
```

**Comment by vspinu** [comment]
It's a bug indeed. Not just display

```R
> unclass(interval(.POSIXct(-Inf), today()))
[1] Inf
attr(,"start")
[1] NA
attr(,"tzone")
[1] ""
```

PR's welcome :wink:

**Comment by vspinu** [comment]
It actually not a bug. It's a consequence of how interval objects are stored. We store start and duration but not the end of the interval. As a result we cannot represent the end in this particular case. I am afraid there is little that can be done here :disappointed:
