### ISSUE TITLE
HOW TO CONVERT char-type ddmmyyyy to date-type ddmmyyyy with no separators "-","/" etc

### ISSUE THREAD

**Issue by jukkaollgren** [tidyverse/lubridate#1034]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
# insert reprex here
```

**Comment by vspinu** [comment]
```R
> dmy("05102020")
[1] "2020-10-05"
> 
```
