### ISSUE TITLE
%within% result changes if interval is flipped

### ISSUE THREAD

**Issue by billybarc** [tidyverse/lubridate#1036]
Is the result of test 2 from the reprex below expected behavior of `%within%`?  I understand from `lubridate:::.within` why it returns FALSE, but I could not find any explanation in `?%within%` or `?int_standardize` as to why one would consider it to be false.

```r
library(lubridate)
int <- interval(as.Date("2021-01-01"), as.Date("2021-12-31"))
x <- as.Date("2021-06-15")
x %within% int #test 1
int2 <- int_flip(int)
x %within% int2 #test 2
```

Should one always use `int_standardize()` for the interval when doing such a comparison?

Cross posted from [stackoverflow](https://stackoverflow.com/questions/71611667/is-it-a-bug-that-a-true-date-within-interval-result-will-become-false-if-the-i)

**Comment by sanjmeh** [comment]
@billybarc did you finally arrive at any conclusion?

**Comment by billybarc** [comment]
> sanjmeh
Nope, this is still open.

**Comment by vspinu** [comment]
Sorry for taking so long. It was a bug indeed.
