### ISSUE TITLE
daylight saving breaks +months() in Linux but not Windows

### ISSUE THREAD

**Issue by andreas50** [tidyverse/lubridate#1037]
The following date calculation gives the expected result ("2022-03-01 EST") in Windows 10, but not under various Linux versions (Debian 10.12, Ubuntu 20.04.4):

```r
as.POSIXct("2022-04-01 EDT") - months(1)
[1] "2022-02-01 EST"
```

In particular,
```
as.POSIXct("2022-04-01 EDT") - months(1) + months(1)
"2022-03-01 EST"
```
does not return the original date.

I am using R 4.1.3. and the latest version of lubridate.

**Comment by stibu81** [comment]
I can confirm this problem also with CET (Ubuntu 20.04, R 4.2.1, lubridate 1.8.0):

```
> ymd_hms("2021-10-01 00:00:00", tz = "CET") + months(1)
[1] "2021-10-01 CEST"
```

On Windows, the correct result is produced.

For now, I'm using this as a workaround, which works also on Ubuntu:

```
> ceiling_date(ymd_hms("2021-10-01 00:00:00", tz = "CET") + days(1), "month")
[1] "2021-11-01 CET"
```

**Comment by vspinu** [comment]
This has something to do with the march 1. Ridiculous bug :sob:. Looking into it. 

```R
  time <- ymd("2022-04-01", tz = "America/New_York")
  expect_equal(time - months(1), ymd("2022-03-01", tz = "America/New_York"))
  time <- ymd("2022-05-01", tz = "America/New_York")
  expect_equal(time - months(2), ymd("2022-03-01", tz = "America/New_York"))
  time <- ymd_hms("2022-05-02 04:01:01", tz = "America/New_York")
  expect_equal(time - period("1m 2d 4H 1M 1S"), ymd("2022-03-01", tz = "America/New_York"))
```

**Comment by stibu81** [comment]
Thanks for taking a look at this. I think this is related to daylight saving time. There is a time shift in March and October and only these two months seem to be affected. But you are also right that the first of the month seems to play a role. These two work, even though the subtracted interval includes a time shift:
```
time <- ymd("2022-04-02", tz = "America/New_York")
expect_equal(time - months(1), ymd("2022-03-02", tz = "America/New_York"))
time <- ymd("2022-11-02", tz = "America/New_York")
expect_equal(time - months(1), ymd("2022-10-02", tz = "America/New_York"))
```

**Comment by vspinu** [comment]
Fixed in devel

**Comment by stibu81** [comment]
I can confirm that this now works on Linux. Thanks!

**Comment by andreas50** [comment]
Also working for me again. Thank you!
