### ISSUE TITLE
Math on interval objects

### ISSUE THREAD

**Issue by kenahoo** [tidyverse/lubridate#105]
If I'm given an interval object, I'd like to know how many days/hours/whatevers it represents between its start & stop.  The only way I can see to do it currently is to use `difftime()` in a pretty awkward way:

```
> ival
[1] 2011-01-01 03:00:46 -- 2011-10-21 18:33:44
> class(ival)
[1] "interval" "numeric"

> difftime(attr(ival, "start") + as.numeric(ival), attr(ival, "start"), 'days')
Time difference of 293.6479 days
```

An `as.difftime.interval(x, units)` method would be helpful, interested in a patch?  Or is there another way I'm not thinking of?

**Comment by cronacronis** [comment]
@garrettgman is there `dmonth`? 
I cannot find it

**Comment by vspinu** [comment]
No there is not. Durations are recorded in seconds, as there is no standard duration of months that function is not there. 

Unfortunately same issue is with years but there is a `dyears` function. Lubridate also uses average month duration of months internally in a couple of places. I guess these might be enough reasons to add the `dmonth` function as well.

**Comment by cronacronis** [comment]
@vspinu nevetheless when we posses start and end point of the interval, we can easily add or subtract months (or any other intervals). E.g. `[01-01-2015; 05-06-2015] => {5 months 4 days}`
