### ISSUE TITLE
Stamp chooses wrong format even when order is provided

### ISSUE THREAD

**Issue by mjsmith037** [tidyverse/lubridate#1052]
Even when order is specified explicitly, `stamp` chooses the wrong format when "Multiple formats matched"

```r
stamp("June 2022", order="%B %Y")(today())
# Multiple formats matched: "%Ob %Y"(1), "%B %Y"(0)
# Using: "%Ob %Y"
# [1] "Jun 2022"
# Desired output: "June 2022"
```

Using `stamp_date` consistently misinterprets the year (yielding a format of "%B %d%y"), and provides no "order" parameter to correct it.

**Comment by vspinu** [comment]
Sorry for the long silence. It works for me in a development version. 

There was indeed a bug in stamp, but I am not sure it's related to this issue. 

Could you please try the development version and if the problem persists, reopen the issue.
```R
> Sys.getlocale("LC_TIME")
[1] "en_GB.utf8"
> stamp("June 2022", order="%B %Y")(today())
Using: "%B %Y"
[1] "October 2022"
```
