### ISSUE TITLE
local timestamp?

### ISSUE THREAD

**Issue by eitsupi** [tidyverse/lubridate#1063]
Related to #591 #438 #359

Thank you for maintaining this user-friendly package for so many years.

My use case is to aggregate records with UTC timestamps observed in various regions into a daily tally by converting them to local time.
Is there an easy way to do this with lubridate?
Since function `local_time` generate the clock time but not the date, there appears to be no way to know the local date.

``` r
df <- readr::read_csv(I("
id,timestamp,timezone
1,2019-01-01T00:00:00Z,UTC
2,2019-01-01T00:00:00Z,Asia/Tokyo
3,2019-01-01T20:00:00Z,UTC
4,2019-01-01T20:00:00Z,Asia/Tokyo
"), show_col_types = FALSE)

df |>
  dplyr::mutate(local_clock = lubridate::local_time(timestamp, timezone))
#> # A tibble: 4 × 4
#>      id timestamp           timezone   local_clock
#>   <dbl> <dttm>              <chr>      <drtn>
#> 1     1 2019-01-01 00:00:00 UTC            0 secs
#> 2     2 2019-01-01 00:00:00 Asia/Tokyo 32400 secs
#> 3     3 2019-01-01 20:00:00 UTC        72000 secs
#> 4     4 2019-01-01 20:00:00 Asia/Tokyo 18000 secs
```

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I understand that only a single time zone is set in a vector, which would result in incorrect data unless the time zone is ignored by humans, but it would be useful to have a function that calculates the local time from UTC and the time zone string
(the reverse process of `force_tzs`).

For now, the data must be split and processed by time zones.

``` r
df <- readr::read_csv(I("
id,timestamp,timezone
1,2019-01-01T00:00:00Z,UTC
2,2019-01-01T00:00:00Z,Asia/Tokyo
3,2019-01-01T20:00:00Z,UTC
4,2019-01-01T20:00:00Z,Asia/Tokyo
"), show_col_types = FALSE)

df |>
  tidyr::nest(data = !timezone) |>
  dplyr::rowwise() |>
  dplyr::summarise(
    id = data$id,
    local_timestamp = purrr::map_dbl(
      data$timestamp,
      ~ lubridate::with_tz(.x, timezone) |>
        lubridate::force_tz("UTC")
    ) |>
      lubridate::as_datetime()
  ) |>
  dplyr::right_join(df, by = "id") |>
  dplyr::arrange(id)
#> # A tibble: 4 × 4
#>      id local_timestamp     timestamp           timezone
#>   <dbl> <dttm>              <dttm>              <chr>
#> 1     1 2019-01-01 00:00:00 2019-01-01 00:00:00 UTC
#> 2     2 2019-01-01 09:00:00 2019-01-01 00:00:00 Asia/Tokyo
#> 3     3 2019-01-01 20:00:00 2019-01-01 20:00:00 UTC
#> 4     4 2019-01-02 05:00:00 2019-01-01 20:00:00 Asia/Tokyo
```

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vspinu** [comment]
This is a group-wize operation.  I am afraid, It's rare enough operation and is not warranted a dedicated function:

```R
> group_by(df, timezone) |>
+   mutate(local = force_tz(with_tz(timestamp, timezone[[1]]), "UTC"))
## # A tibble: 4 × 4
## # Groups:   timezone [2]
##      id timestamp           timezone   local      
##   <dbl> <dttm>              <chr>      <dttm>             
## 1     1 2019-01-01 00:00:00 UTC        2019-01-01 00:00:00
## 2     2 2019-01-01 00:00:00 Asia/Tokyo 2019-01-01 09:00:00
## 3     3 2019-01-01 20:00:00 UTC        2019-01-01 20:00:00
## 4     4 2019-01-01 20:00:00 Asia/Tokyo 2019-01-02 05:00:00
```

**Comment by eitsupi** [comment]
Thank you for the solution.
Unfortunately I had no idea that `group_by` works for this.
Definitely this behavior makes sense to me !
`group_by(df, timezone) |> mutate(local = force_tz(with_tz(timestamp, timezone), "UTC"))`
