### ISSUE TITLE
Recognising date string from Linux/MacOS

### ISSUE THREAD

**Issue by hemip** [tidyverse/lubridate#1066]
A common datetime format I'm missing is the standard output string from the Linux/BSD command 'date' which look like

Fri Sep 16 11:45:41 CEST 2022

```r
lubridate::as_datetime("Fri Sep 16 11:45:41 CEST 2022")
#> Warning: All formats failed to parse. No formats found.
#> [1] NA
```

**Comment by vspinu** [comment]
`as_datetime` follows builtin `as.POSIXct` and supports ISO8601 standard only. I have added a comment to the documentation.

For other formats you can use 

```R
> lubridate::parse_date_time("Fri Sep 16 11:45:41 CEST 2022", "mdTY")
[1] "2022-09-16 11:45:41 UTC"
```
