### ISSUE TITLE
`round_date` not working correctly / CRAN outdated?

### ISSUE THREAD

**Issue by acmuehlhausen-smc** [tidyverse/lubridate#1073]
Hello there,

I've got some problems with 'round_date()' not working properly (more like 'floor_date'). There is issue #1008, which fits quite well to my problem. It's marked as fixed, however the package version from CRAN (1.80) still contains the error. 

I'd be glad if this could be fixed soon. :) 

Best regards!

**Comment by vspinu** [comment]
The release to CRAN is planned for this week. Just need to fix a few more issues and its ready to go.
