### ISSUE TITLE
Unable to create named period vectors

### ISSUE THREAD

**Issue by d-morrison** [tidyverse/lubridate#1074]
I'm trying to create a vector of periods with names, but the result is a numeric vector of 0s:

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
test = c(a = hours(1), b = hours(1) + minutes(30))
print(test)
#> a b 
#> 0 0
class(test)
#> [1] "numeric"
```

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Possibly related to #1072 ?

**Comment by vspinu** [comment]
Thanks for reporting this. This bug was there since the very origins of lubridate c.XYZ methods.
