### ISSUE TITLE
 ymd_hms() producing wrong answer

### ISSUE THREAD

**Issue by shafiul0304034** [tidyverse/lubridate#1086]
ymd_hms(c("10-09-2011 10:00", "11-09-2011 10:00", "13-09-2011 10:00", "17-09-2011 10:00")) should produce "NA" value. Instead, it produces [1] "2010-09-20 11:10:00 UTC" "2011-09-20 11:10:00 UTC" "2013-09-20 11:10:00 UTC" "2017-09-20 11:10:00 UTC"

```r

```

**Comment by vspinu** [comment]
2011 is parsed as day-hour. See #1077 for how this will be tackled in the next release.
