### ISSUE TITLE
Can timechange be in Imports, not Depends?

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/lubridate#1090]
I don't think there is any reason it should be in Depends, right? It forces lubridate to show this message when it is loaded

```r
library(lubridate, warn.conflicts = FALSE)
#> Loading required package: timechange
```

We generally prefer putting packages in Imports unless there is a _really_ compelling reason not to

**Comment by vspinu** [comment]
yes. it was a mistake.
