### ISSUE TITLE
ceiling_date returns date with year off-by-one for dates prior to 1970

### ISSUE THREAD

**Issue by groditi** [tidyverse/lubridate#1107]
For dates before 1970 ceiling_months will return the incorrect year if ```change_on_boundary = FALSE```

```r
 ceiling_date(
     c(ymd('1969-01-01')+years(c(0:2))),
     unit = 'month', 
     change_on_boundary = FALSE
 )
#[1] "1968-02-01" "1969-02-01" "1971-01-01"
 ceiling_date(
     c(ymd('1969-01-01')+years(c(0:2))),
     unit = 'month', 
     change_on_boundary = TRUE
 )
#[1] "1969-02-01" "1970-02-01" "1971-02-01"
```

**Comment by vspinu** [comment]
Works fine for me with devel on linux. Which version of lubridate and timechange do you have?

```R
> ceiling_date(
+      c(ymd('1969-01-01')+years(c(0:2))),
+      unit = 'month', 
+      change_on_boundary = FALSE
+ )
[1] "1969-01-01" "1970-01-01" "1971-01-01"
> ceiling_date(
+      c(ymd('1969-01-01')+years(c(0:2))),
+      unit = 'month', 
+      change_on_boundary = TRUE
+ )
[1] "1969-02-01" "1970-02-01" "1971-02-01"
```

**Comment by vspinu** [comment]
I have just added this test case to our unit tests and it works as expected in the CI on all platforms and versions of R. So it's pretty surely fixed in devel. Please reopen if you keep seeing this. The new CRAN release is coming soon.

**Comment by groditi** [comment]
Lubridate 1.8.0 on windows, no version of timechange installed. Installed 1.9.2 from source and timechange 0.2.0 from source and that fixed it
