### ISSUE TITLE
Time is cut for datetimes with HH:MM:SS = 00:00:00

### ISSUE THREAD

**Issue by adrianrupp88** [tidyverse/lubridate#1112]
When I try to convert a datetime character vector or string, where the time is 00:00:00, the time is cut:

``` r
lubridate::ymd_hms(c("2023-01-01 00:00:00", "2023-01-01 00:00:00"))
#> [1] "2023-01-01 UTC" "2023-01-01 UTC"
```

I would expect, that the items in the vector will be formated into POSIXct like this:

``` r
#> [1] "2023-01-01 00:00:00 UTC" "2023-01-01 00:00:00 UTC"
```

**Comment by vspinu** [comment]
This is how R prints datetimes (aka POSIXct). If you see "UTC" in the printed version then it's a POSIXt, otherwise it's a Date object.

You can format it explicitly as well

```R
format(ymd_hms("2023-01-01 00:00:00"), format = "%Y-%m-%d %H:%M:%S")
[1] "2023-01-01 00:00:00"
```
