### ISSUE TITLE
Set time units locale dependant in duration output

### ISSUE THREAD

**Issue by diegomsg** [tidyverse/lubridate#1130]
Is it possible to set time units output in `as.duration` related functions to get the nice formatting in `-86169s (~-23.94 hours)` to any language?
Can't find anything on `LC_TIME` to include time units beyond days, months and AM/PM.

**Comment by vspinu** [comment]
I am afraid the localized formatting is rabbit hole and it will likely break international setups for people who already rely on the current formatting. You can pretty easily do it yourself by converting seconds to hours and format or just `gsub` hours to whatever language you need.
