### ISSUE TITLE
CRAN ERROR what are the plans?

### ISSUE THREAD

**Issue by aphalo** [tidyverse/lubridate#1174]
@vspinu Package 'lubridate' is triggering an ERROR in R devel (future R 4.5.0). Do you plan just to update the unit tests avoiding use of TZ arguments named `"EET"`, `"CET"`, etc., no longer supported by R or to do some other changes to continue supporting them? This is relevant to me as this ERROR is affecting indirectly packages that I maintain. I have changed the code and unit tests to avoid the ERROR in my packages, but I am considering how to update their documentation. Thanks!

**Comment by vspinu** [comment]
@aphalo Yeh, there is little we can do really. TZ argument is propagated to as.POSIXct everywhere, so it's updating tests only. In any case this is a welcomed change as those names are not proper time zones really.
