### ISSUE TITLE
Suppressing "estimate only" message

### ISSUE THREAD

**Issue by wibeasley** [tidyverse/lubridate#173]
_I posted this in the lubridate's Google Groups a month ago.  I'm reposting it here, since it looks like it's the only thread in the group._

Is it currently possible to suppress the message "estimate only: convert difftimes to intervals for accuracy" when executing something like the following line?
`as.period(ymd("2010-01-01") - ymd("2009-11-01"))` #From https://github.com/hadley/lubridate/issues/75

Is there a way to suppress this specific message, without suppressing more important warnings that may occur?

If not, would t be helpful if I forked lubridate and modified this method from

```
setMethod("as.period", signature(x = "difftime"), function(x, unit = NULL, ...){
  message("estimate only: convert difftimes to intervals for accuracy")
  seconds_to_period(as.double(x, "secs"))
})
```

to something like

```
setMethod("as.period", signature(x = "difftime"), function(x, unit = NULL, showAccuracyWarning=TRUE, ...){
  if( showAccuracyWarning ) message("estimate only: convert difftimes to intervals for accuracy")
  seconds_to_period(as.double(x, "secs"))
})
```

?

To make the signatures and behavior consistent, I suppose these two lines show be modified as well.
https://github.com/hadley/lubridate/blob/95418730b7beff3508f7044a4ce11326167afc81/R/coercion.r#L370
https://github.com/hadley/lubridate/blob/95418730b7beff3508f7044a4ce11326167afc81/R/coercion.r#L436

I really like the period concept in lubridate.  I deal with human age a lot, such as if kids were eligible for a specific government program during a past event.  The period `10y 0m 1d` is more accurate/appropriate than dividing a difftime of 3653 days by 365.25.  It's even more important when the eligibility threshold is 6 months or 34 months old.

**Comment by lejon** [comment]
I get the same annoying warning behaviour with other time functions also, for instance: 

seconds(60) / minutes(1)

estimate only: convert to intervals for accuracy
[1] 1

Ideally the above fix should be applied for all combinations of time functions (i.e everywhere that particular warning message is issued)

I'm using R version 3.4.3 (2017-11-30) and lubridate_1.7.1

**Comment by fbreitwieser** [comment]
I have the same issue, I'll send a pull request with a fix

**Comment by MadNietzsche** [comment]
Just so you know, this error can be suppressed by using suppressMessages():

`r suppressMessages(seconds(60) / minutes(1))`
