### ISSUE TITLE
need sum method for timespan classes

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/lubridate#176]
This should return a duration object, but it doesn't

```
sum(dseconds(1:10))
[1] 55
```

From https://gist.github.com/ijlyttle/5444643

**Comment by hadley** [comment]
Providing an implementation of the `Summary` group generic would knock off the most of these. This, however, is likely to be a breaking change since it's almost certain that someone will be depending on the current behaviour of `sum()`.

**Comment by hadley** [comment]
Given my concerns about breaking changes to other code, and the relatively little interest in this functionality, I think it's safer to close the issue.
