### ISSUE TITLE
expanding/contracting for weekends

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/lubridate#21]
Did we still want to make a function that would allow a user to expand or contract a period for weekends?  We mentioned it at the beginning of the project.  But I'm not sure what that would specifically look like. Perhaps:

today + business_days(days(3))
today + business_hours(hours(50))
tomorrow + market_days(days(2))

? 
maybe business_days() could modify the class of its argument and then we could write a +/- method for that new class
something for version 2?

**Comment by imanuelcostigan** [comment]
I've spun this functionality out into a separate package: https://github.com/imanuelcostigan/fmdates

**Comment by vspinu** [comment]
@imanuelcostigan, that's great! I guess `fmdates` would also be a proper place for handling holidays as per #341.

**Comment by hadley** [comment]
There's now also https://github.com/DavisVaughan/almanac — I think it's now clear this is sufficiently complex that it belongs outside of lubridate.
