### ISSUE TITLE
pretty_dates requires unrealistic knowledge about number of intervals

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/lubridate#216]
From David A. :

The `pretty_dates` function is limited to creating dates based on a set number of breaks. The function assumes that you know exactly the number of intervals required to get nice looking dates.

Consider your example in the documentation that creates nice dates:

```
x <- seq.Date(as.Date("2009-08-02"), by = "year", length.out = 2)
# "2009-08-02" "2010-08-02"
pretty_dates(x, 12)
```

If you change it to `pretty_dates(x, 13)`, they no longer "look pretty."  What I am getting at is that the user does not necessarily know the exact number of intervals, and he or she may not be strict about requiring exactly 13 breaks.

Can there be an argument built in to the function that indicates whether the user is strict about the breaks or not? I was thinking of something like this:

```
pretty_dates(x, 13, strict=FALSE)
## "2009-08-01 GMT" "2009-09-01 GMT" "2009-10-01 GMT"  etc.

pretty_dates(x, 20, strict=FALSE)
## "2009-08-01 GMT" "2009-08-16 GMT" "2009-09-01 GMT"  etc.
```

**Comment by hadley** [comment]
This is probably no longer so important as base R has a decent `pretty.Date` method now.
