### ISSUE TITLE
Timezone import slow - possible solutions

### ISSUE THREAD

**Issue by alexbbrown** [tidyverse/lubridate#225]
## Note that this first post does not in fact present a viable solution.

At the moment, tz conversion is done in force_tz.

essentially

``` R
parse_date_time(tz="America/Los_Angeles","2013-12-16 00:06:04","YmdHMS")
[1] "2013-12-16 00:06:04 PST"
```

is

``` R
force_tz(tz="America/Los_Angeles",parse_date_time("2013-12-16 00:06:04","YmdHMS"))
[1] "2013-12-16 00:06:04 PST"
```

Point 1.  The output format of both of these commands includes timezone in a format (I can't find the name of) represented by "PST".  This is neither Olson nor ISO8601.  It would be _sane_ to be able to import this representation directly back into time handling functions, but I can't see how

``` R
> parse_date_time("2013-12-16 00:06:04 PST","YmdHMSz")
[1] NA
```

nope.  Let's call this one R's problem for now, not lubridate's.

``` R
?strptime
     ‘%Z’ (output only.) Time zone as a character string (empty if not
          available).
```

Let's assume we know the timezone (or have chosen it) to be "America/Los_Angeles".  Let's also make the simplifying assumption that DST doesn't exist for the next few steps.

``` R
strftime(parse_date_time("2013-12-16 00:06:04","YmdHMS"),"%Y-%m-%d %H:%M:%S %z")
[1] "2013-12-15 16:06:04 -0800"
```

This _IS_ parable, and note that the time is correct, and also that force_tz is no longer invoked (use trace(force_tz)).

``` R
parse_date_time("2013-12-15 16:06:04 -0800","YmdHMSz")
[1] "2013-12-16 00:06:04 UTC"
strftime(parse_date_time("2013-12-15 16:06:04 -0800","YmdHMSz"),"%Y-%m-%d %H:%M:%S %z")
[1] "2013-12-15 16:06:04 -0800"
```

This is important because force_tz is very slow compared to parsing.

``` R
system.time(A<-parse_date_time(tz="America/Los_Angeles",rep("2013-12-15 16:06:04",1000000),"YmdHMS"))
trace: force_tz(fast_strptime(x, fmt, tz = "UTC"), tzone = tz)
   user  system elapsed 
 13.801   0.129  13.934 
system.time(B<-with_tz(tz="America/Los_Angeles",parse_date_time(rep("2013-12-15 16:06:04 -0800",1000000),"YmdHMSz")))
   user  system elapsed 
  0.332   0.049   0.380 
```

Note that I curiously have to tell it it's America/Los_Angeles anyway (using cheap with_tz call)

So, what if I have a function like:

``` R
tzoffset(tz) { return "-0800" }
```

and do

``` R
parse_date_time(paste("2013-12-16 00:06:04",tzoffset("America/Los_Angeles")),"YmdHMSz")
```

Of course it's more complex than that, since DST can affect it, and applies differently to different dates (I assume, and don't want to find out).

Of course if that works, then parse_date_time can internally add the correct offset, or just supply it directly to fast_time, so the external interface is the same.

This is all probably wishful thinking, but timezone conversion is about the slowest thing in the shiny app I'm writing, and I get 50Mb+ input files.

---

http://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by hadley** [comment]
Closing this since it's a rather vague issue; we'd be happy to act on concrete ideas for improving timezone performance, but it's hard to do that while still keeping computations accurate.
