### ISSUE TITLE
month() no working properly

### ISSUE THREAD

**Issue by gerlis22** [tidyverse/lubridate#280]
I'm trying to extract the character string of the month from dates using month() and get the an error.

month(ymd(080101), label = TRUE)
Error in month(ymd(80101), label = TRUE) : unused argument (label = TRUE)

**Comment by ngfrey** [comment]
@gerlis22 you can just use: "lubridate::month(df$DateVariable, label = TRUE)" if you want to also use the data.table package.

**Comment by vspinu** [comment]
Indeed. This is shadowing issue. `data.table` has its own month, day etc functions. You must make sure you use the ones from lubridate.

**Comment by Sasken2k** [comment]
thanks gerlis22, you are correct
