### ISSUE TITLE
Problem to add a year when date is a 29 Feb

### ISSUE THREAD

**Issue by larmarange** [tidyverse/lubridate#284]
``` r
as.period(new_interval(ymd('1992-02-29'),ymd('2013-12-05')))
```

is working well. But 

``` r
as.period(new_interval(ymd('1992-02-29'),ymd('2013-12-05')), unit="year")
```

creates the following error:

```
Error in while (any(start + est * per < end)) est[start + est * per <  : 
  missing value where TRUE/FALSE needed
```

According to RStudio debugger, the problem comes from line 49 in `ops-division.r`

**Comment by motabe** [comment]
Guys, this is still happening nowadays, is there a way to cirvumvent this problem?

**Comment by cderv** [comment]
What are you trying to do exactly ? 

initial problem is ok
``` r
library(lubridate)
as.period(interval(ymd('1992-02-29'),ymd('2013-12-05')), units = "year")
#> [1] "21y 9m 6d 0H 0M 0S"
as.period(interval(ymd('1992-02-29'),ymd('2013-12-05')))
#> [1] "21y 9m 6d 0H 0M 0S"
```

and about adding months to some date, this is correctly working and explain in [Arithmetic with date times](http://lubridate.tidyverse.org/articles/lubridate.html#arithmetic-with-date-times). 

``` r
# 31 of April does not exists, thus NA
ymd('2012-03-31') + months(1)
#> [1] NA
#use %m+% to have the last day of the new month
ymd('2012-03-31') %m+% months(1)
#> [1] "2012-04-30"
ymd('2012-02-29') %m+% months(1)
#> [1] "2012-03-29"
# same with years
ymd('2012-03-31') + years(1)
#> [1] "2013-03-31"
ymd('2012-02-29') %m+% years(1)
#> [1] "2013-02-28"
```

Created on 2018-04-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


Created on 2018-04-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
