### ISSUE TITLE
should `year()` return an integer instead of a double?

### ISSUE THREAD

**Issue by wibeasley** [tidyverse/lubridate#361]
Is there any advantage/disadvantage to the [`year()`](https://github.com/hadley/lubridate/blob/master/R/accessors-year.r) function returning an integer instead of a numeric?

``` r
> (y <- lubridate::year(as.Date("2012-05-09")))
[1] 2012
> class(y)
[1] "numeric"
```

It's certainly not a real problem, but I've noticed that I almost always wrap it in `as.integer()` because it's (a) a grouping variable in dplyr or (b) being written to a database.

**Comment by wibeasley** [comment]
I poked around a little more and saw that @gregorp did this in his fork:  https://github.com/gregorp/lubridate/commit/2a9ad5a269b0208b6919a0ce16ef638f80eb8897

If you like the functionality change, tell me if you'd like me to write/modify the [tests ](https://github.com/hadley/lubridate/blob/master/tests/testthat/test-accessors.R).

**Comment by vspinu** [comment]
The same applies to other accessors, except `day` which already returns an integer. So if year to be changed, all others (except second) should be changed as well. That also includes `Period` objects which enforce integers during the construction but don't have integer representation internally. Rather messy.

So the extent of the change is non-trivial and is likely to cause S4 related breakage internally and for dependent packages. Why did you propose the change in the first place? What's your usage pattern?

Also note that the fix shouldn't be with `as.integer` but rather modifying `+ 1900`, to `+ 1900L`. `as.POSIXlt(..)$year` returns an integer.

**Comment by wibeasley** [comment]
Thanks for the explanations, @vspinu.

> the extent of the change is non-trivial and is likely to cause S4 related breakage internally and for dependent packages

Ok.  It may not make sense, but I thought I'd suggest it anyway.  I assumed that it wouldn't cause numerical problems because the 32-bit integer would always be implicitly cast to the 64-bit float by R.  But maybe I'm missing something, or maybe there's an S4 type problem that I'm unaware of.

> Why did you propose the change in the first place? What's your usage pattern?

Because I use year a lot as a grouping variable or in other scenarios where I'm reluctant to use a floating point value in numerical comparisons.  And I write a lot to databases, and the smaller data type  makes things a tad more efficient.  I guess it's a left over from my OO days, and using the most specific data type possible.

Also, I'm not aware of a scenario where I'd want 'year()' to validly return a non-integer.  But I certainly could be overlooking an important use case.

> note that the fix shouldn't be with as.integer but rather modifying + 1900, to + 1900L.

Cool.  Makes sense.

> as.POSIXlt(..)$year returns an integer.

Cool. I wasn't aware of that.  Maybe that's another argument `lubridate::year()` should too.  \*ducks\*

**Comment by msberends** [comment]
Added a comment to the PR #814, discussion continued there and should perhaps be kept there.
