### ISSUE TITLE
Make as.duration (and others) Accept All ISO8601 Formats

### ISSUE THREAD

**Issue by billdenney** [tidyverse/lubridate#362]
I'd like to be able to use as.duration for durations as specified in ISO8601 like

```
as.duration("P1Y2M10DT2H30M")
```

Similarly, it would be nice to be able to define intervals as with all the methods in https://en.wikipedia.org/wiki/ISO_8601#Time_intervals

**Comment by vspinu** [comment]
Period, duration and interval ISO parsing is now in master. See docs and example for `period`, `duration`, and `interval`.

**Comment by billdenney** [comment]
Thank you!  Is it too late to ask for `as.ISO8601` methods or an extension to `as.character` formatting?  (I could help with a PR with guidance on your implementation preferences.)

**Comment by vspinu** [comment]
It's a good idea. Could you open a new issue for this?  PRs are always welcome ;)
