### ISSUE TITLE
Share parsing code with readr

### ISSUE THREAD

**Issue by hadley** [tidyverse/lubridate#396]
I think it might be worthwhile to pull out a separate package that combines the best of readr, lubridate, and https://github.com/google/cctz.

**Comment by hadley** [comment]
I suspect using cctz might also improve the performance of the accessors, instead of having to convert to POSIXlt and then extract.

**Comment by vspinu** [comment]
Parsing in `lubridate` is very loosely coupled with everything else so splitting it out wouldn't be a problem.  I think some 2x loss in parsing speed is inevitable while transiting to C++ but it's probably worth it. If parsing is taken out of lubridate it probably should be all that code in `parse.r + guess.r + stamp.r` and associated C files. 

> I suspect using cctz might also improve the performance of the accessors, instead of having to convert to POSIXlt and then extract.

Indeed. The main issue is (and has always been) painful manipulation with time zones and fitting datetimes to wall clocks.  In the past I tried twice to dig into pure zoneinfo system and lost quite some hair on both occasions. I wasn't aware of `cctz`. It is defenitely the way to go for that. It looks great but it doesn't work on windows. Shipping zoneinfo database with the package should fix that. 

Why do you need this in the first place? Do you miss anything particular in `readr`?

**Comment by vspinu** [comment]
>  think some 2x loss in parsing speed is inevitable 

Hm. I have just benchmarked `readr` and there is a 6x difference. I guess most of it comes down to C++ class machinery. That's a bit too much to give up. On the other hand all those are miliseconds for 10^5 vector. Any other date time mainpulation would take longer with current POSIXlt based updating. 

```r
> microbenchmark(#POSIXct = as.POSIXct(tt, tz = "UTC"), 
+                ymd_hms =  ymd_hms(tt),               
+                pdt2 = parse_date_time2(tt, "YmdHMOS"), 
+                fstrptime = fast_strptime(tt, "%Y-%m-%d %H:%M:%OS", lt = FALSE),
+                readr = parse_datetime(tt, "%Y-%m-%d %H:%M:%OS"),
+                times = 10)
Unit: milliseconds
      expr       min        lq      mean    median        uq       max neval cld
   ymd_hms 21.510929 21.970417 24.264337 22.138597 22.483404 43.589531    10  b 
      pdt2  5.797062  5.975298  6.085724  6.103876  6.153184  6.400493    10 a  
 fstrptime  5.950783  6.218417  6.253889  6.289236  6.316614  6.446869    10 a  
     readr 37.320900 37.369509 37.933928 37.691130 37.868808 39.554504    10   c
```

In order to make a decision we will need a clear benchmark of how much speedup we can gain with cctz as compared to current POSIXct -> POSIXlt -> POSIXct mechanism.  Most relevant starting point is #225 (`force_tz` improvment).

**Comment by hadley** [comment]
I doubt the speed different is due to C vs C++. Let's explore more. 

I needed something fully in C/C++ for readr because parsing happens during load and I didn't want to call back to R. Also I forgot that lubridate did this already :/

**Comment by imanuelcostigan** [comment]
See RcppCCTZ: http://dirk.eddelbuettel.com/code/rcpp.cctz.html

**Comment by kenahoo** [comment]
Is the `cctz` library preferable to [Boost](http://www.boost.org/doc/libs/1_63_0/doc/html/date_time.html)?  Or do the two libraries serve different niches?

**Comment by hadley** [comment]
@kenahoo it's vastly preferable

**Comment by hadley** [comment]
Given that there hasn't been any movement on this in the last two years, I'm going to close it. I still think it's a good idea, but I don't think tracking here is terribly useful.
