### ISSUE TITLE
Inconsistent mday() and month() behaviour

### ISSUE THREAD

**Issue by khakieconomics** [tidyverse/lubridate#489]
I noticed a difference in the behaviour when assigning months and mdays. 

```
> a <- as.Date("2016-03-31")
> b <- a
> mday(a) <- 32
> month(b) <- 2
> a
[1] "2016-04-01"
> b
[1] NA
```

I'd expect either both to return NA, or b to return `2016-03-02` (possibly as an option). 

Thanks again for all your work!

**Comment by cderv** [comment]
Hi, 
why `b` should return `2016-03-02` ? 
`b` returns `NA` because you try to change month of `2016-03-31` which is march to february (`month(b) <- 2`) and "2016-02-31" do not exists... so it returns `NA`

**Comment by khakieconomics** [comment]
Right, but the 32nd of March doesn't exist either...

To be clear, the behaviour of `mday(a) <- 32` is useful. I'd have thought that `month(b) <- 2` would roll forward the days too (possibly as an option).

**Comment by fakyras** [comment]
any news on fixing this bug? :)

> as.Date('2017-03-28') + months(-1)
[1] "2017-02-28"
> as.Date('2017-03-29') + months(-1)
[1] NA
> as.Date('2017-03-30') + months(-1)
[1] NA
> as.Date('2017-03-31') + months(-1)
[1] NA

took a while to figure that I can't trust lubridate in my application

**Comment by vspinu** [comment]
> took a while to figure that I can't trust lubridate in my application

@fakyras, the behavior that you reported is not a bug. Search for "February 29" to get plenty of references on this issue tracker. Also read the docs for `period` or `Period-class`.

@khakieconomics the option to `xyz(..)<-` sounds like the way to go about this, but AFAICR last time I tried it wasn't that straightforward due to how R treats that generic.

**Comment by vspinu** [comment]
The reason why this behaves as it is, is that `xyz<-` operators fallback on arithmetic operations internally. But the arithmetic convention in lubridate is to return NA when the result is non-existing date, which makes a difference for months and years. 

One one hand `xyz<-` is conceptually more similar to `update` (which performs rolling) than to the arithmetic operations. So current behavior of `month<-`  and `year<-` is somewhat non-intuitive.  On the other hand, for rolling you can now do `update(a, month=2)`, but there is no easy way to get NAs.

So, as `month<-` and `update(x, month=...)` are now complementary, and any change in current behavior would break backward compatibility with no clear benefits, I am leaving this as it is. 

This issue definitely something to consider for the potential rewrite of lubridate.
