### ISSUE TITLE
Incorrect result when incrementing in fall back daylight savings time

### ISSUE THREAD

**Issue by mpettis** [tidyverse/lubridate#498]
When I go forward 62 minutes from 12:59 am on a date on which the clocks fall back (so that time is in daylight savings time), I should end up at 1:01 am standard time.  However, I end up at 2:01 am standard time.

Possibly related to: https://github.com/hadley/lubridate/issues/468

    library(lubridate)
    as.POSIXct(strptime("2016-11-06 00:59:00", format="%F %T", tz="America/Los_Angeles"), tz="America/Los_Angeles")
    "2016-11-06 00:59:00 PDT"
    as.POSIXct(strptime("2016-11-06 00:59:00", format="%F %T", tz="America/Los_Angeles"), tz="America/Los_Angeles") + minutes(62)
    "2016-11-06 02:01:00 PST" # Should be "2016-11-06 01:01:00 PST"
     
    parse_date_time("2016-11-06 00:59:00", orders="ymd HMS", tz="America/Los_Angeles")
    "2016-11-06 00:59:00 PDT"
    parse_date_time("2016-11-06 00:59:00", orders="ymd HMS", tz="America/Los_Angeles") + minutes(62)
    "2016-11-06 02:01:00 PST" # Should be "2016-11-06 01:01:00 PST"
     
    ymd_hms("2016-11-06 00:59:00", tz="America/Los_Angeles")
    "2016-11-06 00:59:00 PDT"
    ymd_hms("2016-11-06 00:59:00", tz="America/Los_Angeles") + minutes(62)
    "2016-11-06 02:01:00 PST" # Should be "2016-11-06 01:01:00 PST"

**Comment by vspinu** [comment]
You need durations. Compare:

```R
> ymd_hms("2016-11-06 00:59:00", tz="America/Los_Angeles") + minutes(2)
[1] "2016-11-06 01:01:00 PST"

> ymd_hms("2016-11-06 00:59:00", tz="America/Los_Angeles") + dminutes(2)
[1] "2016-11-06 01:01:00 PDT"

> ymd_hms("2016-03-13 01:59:00", tz="America/Los_Angeles") + minutes(2)
[1] NA

> ymd_hms("2016-03-13 01:59:00", tz="America/Los_Angeles") + dminutes(2)
[1] "2016-03-13 03:01:00 PDT"
```

I agree that this is not particularly intuitive, but it's more or less consistent to how periods behave with bigger units (months and days). 

@garrettgman , @hadley do you have extra thoughts regarding consistency of arithmetic operations on periods around DST skips/repeats?

**Comment by vspinu** [comment]
I am afraid "fixing" this would require changing the semantics of how period arithmetic works in lubridate. Currently no-matter what period you use, if an arithmetic operation ends on a non-existing date-time (like in your case) it will result in NA. 

This issue should be carefully considered in case a rewrite of lubridate is ever attempted.
