### ISSUE TITLE
`hms` parsers: negative components vs negative period

### ISSUE THREAD

**Issue by alchenist** [tidyverse/lubridate#511]
The ability to handle negative components in the `hms` parsers (from commit a8ade12 fixing #333)  is welcome. However, I commonly encounter periods where the sign indicated at the beginning applies to the entire period, where we would `expect_that(hms("-01:30:00"), equals(hours(-1) + minutes(-30) + seconds(0)))`. Current behavior would pass this instead: ` expect_that(hms("-01:30:00"), equals(hours(-1) + minutes(30) + seconds(0)))`

Should there be support for cases where individual components take the initial sign, in addition to cases where each component is signed?

**Comment by vspinu** [comment]
Where do you encounter such format? Is there a standardized rule for such format somewhere?

The only option I see is to add an extra argument to hms for this case.

**Comment by alchenist** [comment]
Not quite; I don't think there's a standard for either representation of negative durations, but leading negatives for multi-part durations do have precedent: see [the interpretation of ISO 8601 durations in the W3C XML schema datatype spec](https://www.w3.org/TR/xmlschema-2/#duration-lexical-repr), which allows for a preceding minus sign in front of the entire duration to indicate a negative duration and only allows unsigned components.

> An optional preceding minus sign ('-') is allowed, to indicate a negative duration. If the sign is omitted a positive duration is indicated.
> ...
> P-1347M is not allowed although -P1347M is allowed.

**Comment by vspinu** [comment]
So what would you suggest in terms of UI? We actually need to implement ISO 8601 anyways, so maybe just go that way?

**Comment by vspinu** [comment]
I am inclined to have mixed signs within durations. Making negative duration is easy by unary `-` after the parsing.

**Comment by vspinu** [comment]
I decided not to take any action on this. Preprocessing leading `-` in a string is trivial, and negating the whole duration is immideate with unary `-` after parsing. It's just not worth the implementation complexity, especially that the compatibility preserving UI is not obvious.

Something to consider for potential lubridate's rewrite though.
