### ISSUE TITLE
nanosecond support?

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/lubridate#540]
Hello,

I was thinking that, probably, to make `lubridate` be the reference for date-time management, there should be support for timestamps that are extremely granular dont you think? Nowadays, milliseconds are an eternity :)

Here come.. nanoseconds! Can `lubridate` deal with them? I just saw a related project https://github.com/eddelbuettel/nanotime

Thanks!

**Comment by vspinu** [comment]
None of the functions in lubridate are aware of the nanotime yet. I am not sure we can make nanotime a first class citizen without an extensive expansion or re-design of the package.

**Comment by randomgambit** [comment]
that would be great!!!. 

A MAJOR provider of financial data just upgraded its infrastructure to provide every trade/order etc with nanosecond timestamp resolution... At the moment I can only process the file in Python (not even sure I can plot the data in ggplot without trimming the nanosecond part)

**Comment by randomgambit** [comment]
Indeed `lubridate` seem to support timestamp beyond milliseconds already

```
> options(digits.secs=8)
> ymd_hms('2015-01-01 08:20:04.12345678')
[1] "2015-01-01 08:20:04.123456 UTC"
```

so my guess is that this should not be too hard (I might be wrong), but SO useful.

**Comment by vspinu** [comment]
That's fractional date-time. POSIXct is a double so you get imprecise nanoseconds with that.

**Comment by vspinu** [comment]
There is no way lubridate can support nanoseconds in current incarnation. I am leaving this for the future rewrite of lubridate which should take care of nanoseconds out from the start.

**Comment by randomgambit** [comment]
oh @vspinu that is SAD!!!
