### ISSUE TITLE
Order wday from Mon to Sun

### ISSUE THREAD

**Issue by estroger34** [tidyverse/lubridate#551]
`wday(label = T)` returns the day of the week as an ordered factor with Sunday being the first day of the week. It would be nice to have an option for an alternative order with Monday being the first day. Having both weekend days together at the end of a weekly profile is often beneficial.

**Comment by cderv** [comment]
duplicates of #257 
It is already taken into account in last dev version. You can install it from github.

see NEWS.md
New `wday` function
```
wday(x, label = FALSE, abbr = TRUE,
  week_start = getOption("lubridate.week.start", 7),
  locale = Sys.getlocale("LC_TIME"))
```
