### ISSUE TITLE
Combine Data Frames (Mutating Join): Based in Time Interval Class via int_overlaps()

### ISSUE THREAD

**Issue by jtelleriar** [tidyverse/lubridate#553]
# Mutating JOIN by means of lubridate's int_overlaps()

I would like to know if it would be possible to perform in R a mutating JOIN (LEFT or INNER) between data frames / tibbles, based on 2 Time Interval Class Columns in each of the Data Frames, by means of lubridate's package int_overlaps() function.

If not possible, ¿Would it be possible to implement such feature in order to perform it in an easy way by means of a single function?

Thank you!
Juan

**Comment by vspinu** [comment]
Sorry for being late on this.

This is out of scope for lubridate. Also almost surely you cannot perform joins on intervals with existing tools. The pattern that you describe is just too complex. You might be able to achieve what you want with repeated invocation of `data.table`'s joins with `roll=TRUE` parameter.

**Comment by jtelleriar** [comment]
Thank you however.
Juan
