### ISSUE TITLE
Inconsistent date parsing when year has 2 or 4 digits and the monts is written in lower case

### ISSUE THREAD

**Issue by malwinare** [tidyverse/lubridate#555]
Hi all, 
This issue maybe be related to #425 .

The date-parsing behavior of `parse_date_time()` is inconsistent depending on whether one or more dates are given, and if it is a mixture of 2- or 4-digit year. For 2-digit year, for instace "16.dec.25", the result is "2016-12-25". However, when the same date is parsed with a date of 4-digit year, for instance "2016.dec.25", it results in "16-12-25". 

This happens for dates where month is wrtitten in lower case letters. However, when month is written in a way where the first letter is upper case and the rest is lower case, the `parse_date_time()` works fine.

Examples
```
parse_date_time(c("16.dec.25"), orders = "ymd")    # "2016-12-25"
parse_date_time(c("2016.dec.25", "16.dec.25"), orders = "ymd")    # "2016-12-25" "16-12-25"
parse_date_time(c("16.dec.25", "16.dec.25"), orders = "ymd")    # "2016-12-25" "2016-12-25"

# works fine in this case:
parse_date_time(c("2016.Dec.25", "16.Dec.25"), orders = "ymd")    # "2016-12-25" "2016-12-25"
```
R version: 3.2.3
lubridate: 1.6.0
locale: en_US.UTF-8 

Thanks in advance.
Best, 
Malwina

**Comment by cderv** [comment]
works fine for me with current dev version 1.6.0.9009

``` r
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
parse_date_time(c("16.dec.25"), orders = "ymd")  
#> [1] "2016-12-25 UTC"
parse_date_time(c("2016.dec.25", "16.dec.25"), orders = "ymd")
#> [1] "2016-12-25 UTC" "2016-12-25 UTC"
parse_date_time(c("16.dec.25", "16.dec.25"), orders = "ymd") 
#> [1] "2016-12-25 UTC" "2016-12-25 UTC"
parse_date_time(c("2016.Dec.25", "16.Dec.25"), orders = "ymd")  
#> [1] "2016-12-25 UTC" "2016-12-25 UTC"
```
Did you tried ?

**Comment by malwinare** [comment]
Yes, with the dev version 1.6.0.9009 it is working. 
Thanks a lot.
