### ISSUE TITLE
Add to or subtract from a date - timeanddate.com

### ISSUE THREAD

**Issue by iembry-USGS** [tidyverse/lubridate#557]
It would be nice to have a feature like the [TimeandDate.com Calculator: Add to or subtract from a date](https://www.timeanddate.com/date/dateadd.html) and this screenshot: ![2017-03-28 11_52_35-date calculator_ add to or subtract from a date results](https://user-images.githubusercontent.com/4990804/27433376-0d350b44-571a-11e7-8003-ec7be4123a75.png)

Thank you.

Irucka

**Comment by vspinu** [comment]
Is this what you want?

```R
ymd(20170628) + weeks(23)
ymd(20170628) + period("1y2m1w2d)
```

**Comment by iembry-USGS** [comment]
Yes, that is exactly it! Thank you.

Irucka
