### ISSUE TITLE
today() does not take the time zone into account

### ISSUE THREAD

**Issue by Courvoisier13** [tidyverse/lubridate#558]
In `today()` the argument `tzone` has no effect. it always gives "UTC":
`> tz(today("Europe/Rome"))
[1] "UTC"
> tz(today("GMT"))
[1] "UTC"
> tz(today("EST"))
[1] "UTC"
> tz(today("Europe/Rome"))
[1] "UTC"`

Is this a bug?

**Comment by vspinu** [comment]
`today` returns a Date which doesn't have a tzone marker. So tz returns UTC as a fall back default.

```R
> today("Japan")
[1] "2017-06-28"
> today("Europe/Paris")
[1] "2017-06-27"
```
