### ISSUE TITLE
Incorrect parsing of Mon-Year (bY) format

### ISSUE THREAD

**Issue by IdoBar** [tidyverse/lubridate#559]
Hi,

I'm trying to parse a very simple date format, which appears as either `%d-%b-%Y`, `%b-%Y` or `%Y`.
`parse_date_time()`  works great for the 1st and 3rd formats, but is unable to parse the second one (though `guess_date()` successfully guesses the right format).
Examples:
```
> parse_date_time("May-2010", orders="bY")
[1] NA
Warning message:
All formats failed to parse. No formats found. 
> guess_formats("May-2010", orders="bY")
     bY 
"%b-%Y" 
> parse_date_time("May-2010", orders="%b-%Y")
[1] NA
Warning message:
All formats failed to parse. No formats found. 
> parse_date_time("May-2010", orders="Y")
[1] "2010-01-01 UTC"
> parse_date_time("01-May-2010", orders="dbY")
[1] "2010-05-01 UTC"
```
I'm using R 3.3.1, with lubridate 1.6.0, on a Windows machine with "English_Australia.1252" locale.

**Comment by cderv** [comment]
Base function `strptime` does not parse correctly. It could be not a `lubridate` issue

``` r
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
old <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "eng")
#> [1] "English_United Kingdom.1252"
strptime("May-2010", format="%b-%Y")
#> [1] NA
strptime("10-May-2010", format="%d-%b-%Y")
#> [1] "2010-05-10 CEST"
```

**Comment by vspinu** [comment]
This should be working. Our C parser handles English months but for some reasons "bY" is not getting through.

```R
> parse_date_time2("May-2010", orders="bY")
[1] "2010-05-01 UTC"
> parse_date_time(c("01-May-2010", "May-2010", "2010"), orders=c("mbY", "bY", "Y"))
[1] NA               "2010-01-01 UTC" "2010-01-01 UTC"
```

**Comment by IdoBar** [comment]
Thanks Christophe,

Using `Om` instead of `b` worked for me and parsed correctly all the appearances, using `orders=c("dOmY", "OmY", "Y")`, so I'll go with that for now.
Vitalie, using `parse_date_time2("May-2010", orders="bY")` worked alright, but only when I know in advance the format to expect and it is not flexible to "guess" when the input of mixed formats.

Thanks for your responses, Ido
