### ISSUE TITLE
Error in UseMethod

### ISSUE THREAD

**Issue by vidyasagarbhargava** [tidyverse/lubridate#561]
Hi,
I am getting below errors while extracting year from date object using lubridate package on mac.
```
train$Datetime<-ymd(train$Datetime)  
train$year<-year(train$Datetime)
```

Error in UseMethod("year", x) : 
  no applicable method for 'year' applied to an object of class "Date"

Thanks!

**Comment by vspinu** [comment]
Works just fine here:

```R
year(today())
[1] 2017
> year(ymd("10-10-10"))
[1] 2010
```

Try to re-install or install from github with devtools.

**Comment by vidyasagarbhargava** [comment]
Hi vspinu,
I have re-installed the lubridate package from cran. But still getting this error for year and month both and not for other function like mday, wday (these are working fine). I get this error only when i re-run the script.
For the first time or in initializing new session  in rstudio i don't face any error.

**Comment by vspinu** [comment]
I will need a reproducible example to investigate this. Could you please isolate the troublesome part of train$Datetime and paste here?

**Comment by vspinu** [comment]
It must be some local issue with the instalation of R, RStudio or lubridate. Most surely not a bug in lubridate as it would have rendered the package unusable for almost all users.
