### ISSUE TITLE
Typo in period_to_seconds help: 364.25 days in a year

### ISSUE THREAD

**Issue by PJBiostat** [tidyverse/lubridate#562]
Most minor of issues. Fortunately the function itself does not have that error in its calculation.

**Comment by cderv** [comment]
In current dev version in master, it is ok. See `period_to_seconds` documentation on [http://lubridate.tidyverse.org](http://lubridate.tidyverse.org/reference/period_to_seconds.html) which is the doc for last version.

Correction was made in PR #537
