### ISSUE TITLE
Weird behavior of seconds_to_period on data set with only a few observations beyond 1 hour and nano seconds

### ISSUE THREAD

**Issue by PJBiostat** [tidyverse/lubridate#563]
I have some hockey data I cannot share but I can give this little snippet. A game consists of 3 periods of 20 minutes, which if tied at the end go into 5 minutes of overtime. In my data set of 1230 games, there are exactly 10 games where the first goal is scored in that 5 extra minutes window. The original data is in seconds (all the way to nanoseconds apparently) as a double precision variable (`firsttime`). For some unknown reason, for those 10 observations, seconds_to_period would not give me the hour, though I would be happy with just extending the minutes to 60 and beyond. I tried after converting the time to a nice whole integer, still would not give me the hour.

`allfirstgoals <- allfirstgoals %>% mutate(FirstGoalTime=seconds_to_period(firsttime))`

![selection_020](https://user-images.githubusercontent.com/20845536/27872575-34aee3e0-6177-11e7-808c-89ab06ce4dc4.png)

**Comment by vspinu** [comment]
Don't use period for this. It's an S4 class which doesn't play nicely with dplyr. Use plain difftime for this.  Also upgrade to the github version.

In order to figure out your problem we would need a sample of the problematic data.

**Comment by PJBiostat** [comment]
I was surprised it was an S4 class as I figured tidyverse packages should play nice with dplyr. In any case, difftime does not do what I need here, I can divide by 60 and certainly don't need or want to specify some unnecessary timezone or origin. All I really wanted was to have a quick MM:SS display (possibly HH:MM:SS, or MMM:SS)  for an axis in ggplot2. In-game sports time-keeping usually uses an internal game clock and rarely refers to hours, so a small modification of time display options would be a nice feature to have. I imagine soccer would be complicated to do with notions of stoppage time, but at least for hockey, MMM:SS would be enough. 

Now, done in isolation, the operation works, it really only occurs within the data frame and operations on the data frame (such as ggplot). Selecting the vector and its specific component looks fine.
![selection_022](https://user-images.githubusercontent.com/20845536/27917011-c2d7fd66-6238-11e7-95d6-ea894189d98b.png)

**Comment by vspinu** [comment]
Have you had a look at [hms](https://github.com/tidyverse/hms) for this?

**Comment by PJBiostat** [comment]
I have not. Thanks, will try and get back to you. 

In the meantime, here is a reproducible example (which may be unnecessarily long) for that weird data frame behavior. Displaying the data frame only uses the trailing seconds, while the vector inside is correct. It is not quite the wrong time from my data, but still, not the expected behavior.
`set.seed(123)`
`fakedata <-data.frame(time1=sort(c(runif(1000,0,3600),runif(10,3600,3901))),
  EventInd=rep(c(1,0),c(1000,10)))`
`fakedata <- tbl_df(fakedata)`
`fakedata <- fakedata %>% mutate(time2=seconds_to_period(time1))`
`fakedata %>% filter(EventInd==0)`
`fakedata$time2[fakedata$EventInd==0]`

![selection_023](https://user-images.githubusercontent.com/20845536/27917826-230c5798-623b-11e7-8134-7127f4ebe9b6.png)
![selection_024](https://user-images.githubusercontent.com/20845536/27917828-258c8768-623b-11e7-913a-c9848b936d10.png)

**Comment by PJBiostat** [comment]
hms seems to work like a charm, thanks! 
![selection_026](https://user-images.githubusercontent.com/20845536/27918385-d1feddb0-623c-11e7-8d72-9f161b14e4e0.png)

If the seconds_to_period issue is not worth investigating (I am not a fan of bringing S4 classes to the front end), you may close the issue. From my end, it is resolved.

**Comment by vspinu** [comment]
> not the expected behavior.

It's just a display issue. tibble displays seconds only because periods inherit from numeric. Till folks figure out an uniform framework how to handle S4 classes there is nothing to be done here.
