### ISSUE TITLE
Feature request: new epiweek/epiyear functions would benefit from option to use "US-CDC" defn or "isoweek"

### ISSUE THREAD

**Issue by rbalshaw** [tidyverse/lubridate#564]
<< continuing a discussion in #492 >>

The US/CDC uses an epiweek defined as starting on Sunday.  Much of the rest of the world uses epiweeks that start on Monday (as in the definitions used by `isoweek`).

It would be helpful if the epiweek and epiyear functions had an option to permit the choice of either definition, perhaps following the  `week_start` option as in `wday`?

As well, the documentation could indicate the rationale for this option, perhaps something as simple as

"The US/CDC uses an epiweek defined as starting on Sunday.  Much of the rest of the world uses epiweeks starting on Monday -- as in the definitions used by `isoweek`.

Could these be added?

Thank you!

**Comment by vspinu** [comment]
I have just looked into it, and I am afraid I either misunderstood this issue or you simply want `isoweek` and `isoyear`.  `isoweek` is like `eipiweek` but starts on Monday, same for `isoyear`. So there is no issue.

**Comment by rbalshaw** [comment]
You are right.  With the “Monday” option, this would replicate isoweek.  Adding this option (and this bit of documentation) will clarify the distinction between the US CDC version of epiweek and the notion of epiweek used in many other parts of the world.

An alternative that comes to mind would be to refer to isoweek as the appropriate choice of functions when the user desires the non-US definition to be used.

I suppose I was trying to clarify things in response to the many queries on the web from people trying to understand the US definition of epieweek and how it differs from the definition used elsewhere.

Thanks for looking into this.  Either solution would close this from my perspective.

**Comment by vspinu** [comment]
Ok. I am altering the documentation then:

```R
#' @description `epiweek()` is the US CDC version of epidemiological week. It
#'   follows same rules as `isoweek()` but starts on Sunday. In other parts of
#'   the world the convention is to start epidemiological weeks on Monday,
#'   which is the same as `isoweek`.
```

If I ever write a new datetime package, everything will be ISO by default :)

**Comment by rbalshaw** [comment]
Thanks.  That’s a tidier solution.

Rob

**Comment by stragu** [comment]
Hi @vspinu 

I assume the documentation for `epiyear()` should also have the same information? Currently it only says:

> `epiyear()` returns years according to the epidemilogical week calendars.

... with no mention of US vs ISO.

**Comment by rbalshaw** [comment]
Hi – I’ve not been part of this conversation for a long time, but I’d suggest that though the connection to the US vs. ISO definitions is implicitly there, it would be good to be explicit.

Rob
