### ISSUE TITLE
confusion between as.period and as.duration ?!

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/lubridate#565]
Hello there, please consider this simple example:

```
dataframe <- data_frame(date = c(ymd('2016-01-01','2016-02-01' )),
                        maturity =  c(ymd('2017-01-01','2027-02-01' )) )

dataframe <- dataframe %>% mutate(tenor = maturity - date,
                     tenor1 = as.period(tenor),
                     tenor2 = as.duration(tenor))

> dataframe
# A tibble: 2 x 5
        date   maturity     tenor         tenor1                 tenor2
      <date>     <date>    <time>   <S4: Period>         <S4: Duration>
1 2016-01-01 2017-01-01  366 days  366d 0H 0M 0S   31622400s (~1 years)
2 2016-02-01 2027-02-01 4018 days 4018d 0H 0M 0S 347155200s (~11 years)
```

Here I want to keep the row whose remaining duration is more than a year. Using `years()` or `dyears()` sometime works, sometimes doesnt.

```

> dataframe %>% filter(tenor > years(5)) # FAIL
# A tibble: 2 x 5
        date   maturity     tenor         tenor1                 tenor2
      <date>     <date>    <time>   <S4: Period>         <S4: Duration>
1 2016-01-01 2017-01-01  366 days  366d 0H 0M 0S   31622400s (~1 years)
2 2016-02-01 2027-02-01 4018 days 4018d 0H 0M 0S 347155200s (~11 years)

> dataframe %>% filter(tenor > dyears(5)) 
# A tibble: 1 x 5
        date   maturity     tenor        tenor1                 tenor2
      <date>     <date>    <time>  <S4: Period>         <S4: Duration>
1 2016-02-01 2027-02-01 4018 days 366d 0H 0M 0S 347155200s (~11 years)

> dataframe %>% filter(tenor1 > years(5))
# A tibble: 1 x 5
        date   maturity     tenor        tenor1                 tenor2
      <date>     <date>    <time>  <S4: Period>         <S4: Duration>
1 2016-02-01 2027-02-01 4018 days 366d 0H 0M 0S 347155200s (~11 years)

> dataframe %>% filter(tenor1 > dyears(5)) # FAIL
Error in filter_impl(.data, quo) : 
  Evaluation error: cannot compare Period to Duration:
coerce with 'as.duration' first..
> dataframe %>% filter(tenor2 > dyears(5))
# A tibble: 1 x 5
        date   maturity     tenor        tenor1                 tenor2
      <date>     <date>    <time>  <S4: Period>         <S4: Duration>
1 2016-02-01 2027-02-01 4018 days 366d 0H 0M 0S 347155200s (~11 years)

> dataframe %>% filter(tenor2 > dyears(5))
# A tibble: 1 x 5
        date   maturity     tenor        tenor1                 tenor2
      <date>     <date>    <time>  <S4: Period>         <S4: Duration>
1 2016-02-01 2027-02-01 4018 days 366d 0H 0M 0S 347155200s (~11 years)
```

Is the FAIL with `dataframe %>% filter(tenor > years(5))` and `dataframe %>% filter(tenor1 > dyears(5))` expected/normal? I am puzzled here.

Thanks!!

**Comment by cderv** [comment]
one element of response is the class of the element. `dyears` is a duration object and `years` is a period object - not the same. Tenor column is difftime object. When doing calculation with date, everything is not equivalent. (see [docs](http://lubridate.tidyverse.org/articles/lubridate.html#arithmetic-with-date-times)). You must take that into account when comparing with `<` I think. 

Does it help you? 

``` r
dataframe %>% summarise_all(funs(class))
#> # A tibble: 1 x 5
#>    date maturity    tenor tenor1   tenor2
#>   <chr>    <chr>    <chr>  <chr>    <chr>
#> 1  Date     Date difftime Period Duration
class(years(5))
#> [1] "Period"
#> attr(,"package")
#> [1] "lubridate"
class(dyears(5))
#> [1] "Duration"
#> attr(,"package")
#> [1] "lubridate"
```

**Comment by randomgambit** [comment]
hi @cderv thanks but according to the docs (that I have read)

> Why two classes? Because the timeline is not as reliable as the number line. The Duration class will always supply mathematically precise results. A duration year will always equal 365 days. Periods, on the other hand, fluctuate the same way the timeline does to give intuitive results.

So my understanding is that both period and duration for one year will mean approximately the same thing (expect for leap years and other corner cases): a length of time of about one year . There is unfortunately nothing is the docs that explain the failures above. 

If the results are expected what is the right syntax then to have 
`tenor > years(5)` and `tenor1 > dyears(5)` return a legit result? 

Thanks again!!

**Comment by randomgambit** [comment]
Hi @vspinu can you please tell me more? I really need to know whats going on here

Thanks!!

**Comment by vspinu** [comment]
> So my understanding is that both period and duration for one year will mean approximately the same thing (expect for leap years and other corner cases): a length of time of about one year .

It's "about" one year, and that's the problem. What should be the result of the following:

```R
> dyears(1)
[1] "31536000s (~52.14 weeks)"
> years(1) < dseconds(31536000)
```
and it should be apparent fthat the behavior is undefined.

> Hi @vspinu can you please tell me more? I really need to know whats going on here

Not sure what could be added here. Period doesn't have a defined length, so cannot be compared to exact time spans like Durations. 

Of course we can extend the semantics of boolean operators by converting periods automatically to durations but for now it's undefined.
