### ISSUE TITLE
`floor_date(date, "year")` is off by one in leap years

### ISSUE THREAD

**Issue by nacnudus** [tidyverse/lubridate#567]
``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
floor_date(ymd("2016-02-29"), "year")
#> [1] "2016-01-01"
floor_date(ymd("2016-03-01"), "year")
#> [1] "2015-12-31"

# I would expect the equivalent of this
ymd("2016-02-29") - ddays(yday(ymd("2016-02-29")) - 1)
#> [1] "2016-01-01"
ymd("2016-03-31") - ddays(yday(ymd("2016-03-31")) - 1)
#> [1] "2016-01-01"
```

**Comment by hadley** [comment]
I just discovered this too

**Comment by DavisVaughan** [comment]
+1 to get this fixed. Was planning on using it for period conversion in `tibbletime`.

**Comment by vspinu** [comment]
Sorry for being slow on this and other issues. My bandwidth for R open source has been close to zero recently. Will have a look later this week.

**Comment by DavisVaughan** [comment]
@vspinu, I'm no expert on lubridate, but I forked it and commenting out [this line](https://github.com/tidyverse/lubridate/blob/d84e9b0c275f6b72278ef000cc369f9910bb01ee/src/update.cpp#L156) seems to fix the problem. I'm not sure if that line needs to be there? Just a thought.

All tests (that were passing before the change) still pass.

**Comment by vspinu** [comment]
@DavisVaughan, you are right. I have no idea why that line is there.. It might have had some sense in the earlier drafts of that functionality, but I don't recall anymore.
