### ISSUE TITLE
bug in hms function

### ISSUE THREAD

**Issue by blueskypie** [tidyverse/lubridate#568]
> hms("12:30.5")
[1] "12H 30M 5S"
It should be "12M 30.5S"

**Comment by cderv** [comment]
Use `ms` not `hms` 
``` r
ms("12:30.5")
#> [1] "12M 30.5S"
```
it is explained in the doc. see :  `help(hms, package = "lubridate")`

**Comment by blueskypie** [comment]
thanks! but the format of time isn't known beforehand.

**Comment by schmate** [comment]
I gusess you think that lubridate should interpret the format by finding : and . characters. Do I understand your expectations?

By using the hms() function, you declare that the format is **h**our-**m**inute-**s**econd, no matter how you separate those numbers. As you see in the documentation of the package, it can be even a sentence containing three numbers.

You cn read the package's documantation by using `?lubridate()` or the function's here: `help(hms, package = "lubridate")`
