### ISSUE TITLE
installation problem - Error in as.POSIXlt

### ISSUE THREAD

**Issue by hylaarborea** [tidyverse/lubridate#574]
I am trying to install lubridate but I have always the same error message.  Looking around it looks related to the fact that it has a function date() which already exist also as base::date(). But during the test of the package it calls date() and therefore the error.

Here the details:
https://stackoverflow.com/questions/45959714/r-lubridate-package-installation-error-in-as-posixlt

It looks like I am the only one to have this problem. I tried to install also an old version of R, to add or remove other packages but I have always the same error... 
Maybe someone here can help?

**Comment by wlandau-lilly** [comment]
I wonder if this is somehow related to the [current Solaris CRAN check error](https://cran.rstudio.com/web/checks/check_results_lubridate.html).

**Comment by DavisVaughan** [comment]
@hylaarborea, this may help you. Just solved a similar problem.

https://github.com/business-science/tidyquant/issues/62

Look at the very bottom of this issue for the section on an `.Rprofile` script. If that `.Rprofile` script has a `.Last` function defined that calls `date()` then it will crash the installation of `lubridate`.

**Comment by hylaarborea** [comment]
Thanks @DavisVaughan    
it was just because the line
cat(paste(date(),"\nAdios\n"))
in the file:
~/.Rprofile

**Comment by pgensler** [comment]
@DavisVaughan  @hylaarborea It may be worth noting that you can indeed edit your .Rprofile from this:
https://csgillespie.github.io/efficientR/3-3-r-startup.html#rprofile
So maybe a simple purrr script that iterates over the items in your .Rprofile, and if it detects that the `.Last` function is there, just delete it/remove that line? I would think this is a bad practice, but good to know it's possible to develop a workaround to remove the line.

**Comment by vspinu** [comment]
This issue was caused by lubridate. We were not handling missing argument to date. Sorry for the trouble. Now fixed in master.
