### ISSUE TITLE
travis build failing for R devel

### ISSUE THREAD

**Issue by vnijs** [tidyverse/lubridate#578]
Testing works fine for R release but fails with R devel. Error message below

Error : package â€˜lubridateâ€™ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package â€˜radiant.dataâ€™

For full log see: https://travis-ci.org/radiant-rstats/radiant.data/builds/278372339

Any suggestions? Thanks

**Comment by vspinu** [comment]
Do you use lubridate built in earlier version of R? It's probably the case if you fetch it from CRAN. I have just tested lubridate-dev with the most recent R-dev and all works just fine. 

In case you use lubridate-dev from github, could you please re-run your bulds? I have made some changes with the regard to routines registration for R-dev.

**Comment by hadley** [comment]
@vnijs you probably just need to delete your travis caches.

**Comment by vspinu** [comment]
Seems to be an outdated CRAN mirror issue. See this [thread](http://r.789695.n4.nabble.com/R-devel-r73293-and-the-testthat-package-td4745460.html).

I have just suffered this with testthat on windows with R-devel. The package is picked from Rstudio mirror and it seems that it has not been updated yet there, which is rather strange (@hadley you might want to have a closer look at this). 

```R
> install.packages("testthat")
Installing package into ‘C:/Users/bbltr/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/testthat_1.0.2.zip'
Content type 'application/zip' length 1058113 bytes (1.0 MB)
downloaded 1.0 MB

package ‘testthat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\bbltr\AppData\Local\Temp\Rtmp8gt52I\downloaded_packages
> library("testthat", lib.loc="~/R/win-library/3.5")
Error: package ‘testthat’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

I am closing this as it's not lubridate specific.
