### ISSUE TITLE
floor_date in official release still not working afte ~1 year

### ISSUE THREAD

**Issue by adibender** [tidyverse/lubridate#579]
Is it possible to make a maintenance release? After almost one year, #486 (and floor_date) still don't work with NAs present in the official CRAN release. Just realized after reinstalling R with packages from CRAN instead of GitHub.

**Comment by vspinu** [comment]
Sure. Will try to fix most stringent bugs this weekend and will roll a release asap no matter what. 

My apologies.  I have been out of R development for half a year now and it's hard to do cook something if you don't eat that food.

**Comment by adibender** [comment]
No worries. Thanks for the quick response!

**Comment by vspinu** [comment]
I have uploaded 1.7.0 to CRAN two weeks ago but there seems to be a busy period and my turn hasn't come yet. Package is in [recheck](ftp://cran.r-project.org/incoming/recheck/) at the moment. Closing this as the ball is not with me any longer.

**Comment by vspinu** [comment]
Finally on CRAN!

**Comment by adibender** [comment]
Great! Thanks!
