### ISSUE TITLE
lubridate not unloading

### ISSUE THREAD

**Issue by yonicd** [tidyverse/lubridate#580]
```r
loadedNamespaces()
# [1] "graphics"  "tools"     "utils"     "yaml"      "grDevices" "stats"     "datasets"  "methods"   "base"     
asNamespace('lubridate')
# <environment: namespace:lubridate>
loadedNamespaces()
# [1] "magrittr"  "graphics"  "tools"     "utils"     "yaml"      "grDevices" "stats"     "lubridate" "datasets"  "stringi"   "methods"  
# [12] "stringr"   "base"     
unloadNamespace('lubridate')
loadedNamespaces()
# [1] "magrittr"  "graphics"  "tools"     "utils"     "yaml"      "grDevices" "stats"     "lubridate" "datasets"  "stringi"   "methods"  
# [12] "stringr"   "base" 
```

```r
> devtools::session_info()
Session info --------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.331)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-09-29                  

Packages ------------------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.3.2   2016-10-31 local         
 datasets  * 3.3.2   2016-10-31 local         
 devtools    1.13.3  2017-08-02 cran (@1.13.3)
 digest      0.6.12  2017-01-27 cran (@0.6.12)
 graphics  * 3.3.2   2016-10-31 local         
 grDevices * 3.3.2   2016-10-31 local         
 lubridate   1.6.0   2016-09-13 CRAN (R 3.3.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.3.0)
 memoise     1.1.0   2017-09-07 local         
 methods   * 3.3.2   2016-10-31 local         
 stats     * 3.3.2   2016-10-31 local         
 stringi     1.1.5   2017-04-07 CRAN (R 3.3.2)
 stringr     1.2.0   2017-02-18 CRAN (R 3.3.2)
 tools       3.3.2   2016-10-31 local         
 utils     * 3.3.2   2016-10-31 local         
 withr       2.0.0   2017-07-28 CRAN (R 3.3.2)
 yaml        2.1.14  2016-11-12 cran (@2.1.14)
```

**Comment by vspinu** [comment]
Most likely an R's issue and probably due to the compiled code loaded with lubridate.  Why do you need this for? Unloading namespaces is prone to failures. It's enough another package to import something from lubridate and unloading will fail anyways.

This is low priority AFAIC, and if you or someone else are willing to investigate this more carefully I would close this for now.

**Comment by yonicd** [comment]
The example above is deliberately on an empty environment in a new session. there arent any other namespaces that dep. on lubridate that would cause it not unload, and if this was the case an error would be returned stating that it cant be unloaded. 

Isnt it a precondition of a package to be able to unload when it is unattached? this is not an uncommon  procedure in a workflow.

**Comment by vspinu** [comment]
> Isnt it a precondition of a package to be able to unload when it is unattached? 

Never heard of such "precondition". This is why I asked  why would you need that for and where the current behavior interferes with your workflow.

> this is not an uncommon procedure in a workflow.

Devtools re-loads it just fine, so looks like it's not really necessary for a workflow. 

In any case, it's unlikely to be the lubridate issue. Likely R or Rcpp issue. If you are really bothered by this, please report to R folks. 

We do indeed have quite some mixed C and Rcpp code down there which might cause issues with dyn-un-lloading. But, all C code and dynlib registration conforms to R standards so I am unlikely to look at this any time soon (unless there is indeed a serious issue with the standard workflow).
