### ISSUE TITLE
Interval - inconsistent lengths Error

### ISSUE THREAD

**Issue by kmcconeghy** [tidyverse/lubridate#581]
Hello, 

I encounter an error when I create an interval class object then filter the dataset and attempt to view the dataset.

Test Code:
```
#Test code for Lubridate Package:
library('tidyverse')
library('lubridate')

#test
db <- lakers %>% 
  mutate(NewDate <- ymd(20100101),
         TestInterval <- interval(ymd(date), NewDate))
View(db)

db2 <- db %>%
  filter(opponent=='POR')
View(db2)
```
 Error in validObject(.Object) : 
  _invalid class “Interval” object: Inconsistent lengths: spans = 1751, start dates = 34624_

The error appears from this code snippet:
```
if (length(object@.Data) != length(object@start)) {
    msg <- paste("Inconsistent lengths: spans = ", length(object@.Data),
      ", start dates = ", length(object@start), sep = "")
    errors <- c(errors, msg)
  }
```
This seems a bug to me, could you comment on what is happening?

**Comment by vspinu** [comment]
Intervals are S4 objects and those are not well supported by the dplyr machinery. Nothing that could be done at the moment on lubridate side.

**Comment by vspinu** [comment]
There is an initiative for generalized vectors in adley/vctrs#27. Till that issue is fixed, dplyr is unlikely to work well with intervals. Closing as notn-ubridate specific.
