### ISSUE TITLE
Interval Inconsistency

### ISSUE THREAD

**Issue by feyziemreoral** [tidyverse/lubridate#584]
Hi

I'm new to GitHub.

I just noticed that the interval function is giving some unexpected results...

> interval('2015-03-01', '2016-10-01') / months(1)
[1] 19
> interval('2015-03-02', '2016-10-01') / months(1)
[1] 19.47541
> interval('2015-03-03', '2016-10-01') / months(1)
[1] 18.93333

I would expect the output of the middle function to be between the first and third. 

If I change the end period to 2015 I get what I would expect...

> interval('2015-03-01', '2015-10-01') / months(1)
[1] 7
> interval('2015-03-02', '2015-10-01') / months(1)
[1] 6.966667
> interval('2015-03-03', '2015-10-01') / months(1)
[1] 6.933333

Am I missing something?

**Comment by vspinu** [comment]
It's probably a bug. Division by month is rather flimsy.
