### ISSUE TITLE
hms-generated Period objects in tibbles vs dplyr::filter

### ISSUE THREAD

**Issue by jon-harmon-macmillan** [tidyverse/lubridate#588]
`library(dplyr)`
`library(lubridate)`
`time_data = tibble(key_field = 1:4, time_field = c('01:02:03', '04:05:06', '07:08:09', '10:11:12'))`
`time_data$time_field = hms(time_data$time_field)`
`time_data %>% filter(key_field %in% c(2, 3)) %>% select(time_field) %>% str()`

`Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	2 obs. of  1 variable:`
` $ time_field:Formal class 'Period' [package "lubridate"] with 6 slots`
`  .. ..@ .Data : num  6 9`
`  .. ..@ year  : num  0 0 0 0`
`  .. ..@ month : num  0 0 0 0`
`  .. ..@ day   : num  0 0 0 0`
`  .. ..@ hour  : num  1 4 7 10`
`  .. ..@ minute: num  2 5 8 11`

time_field in the filtered table has 2 rows, but more than 2 rows worth of time data for hour and minute. This causes issues depending what things I then try to do with this field.

I encountered this while loading time data from a database and attempting to clean it up with the tidyverse. It appears to work fine until I subset it using %. Note: Subsetting the original tibble using [] subsetting results in more-expected results:
`time_data[2:3, ] %>% select(time_field) %>% str()`
`Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	2 obs. of  1 variable:`
`$ time_field:Formal class 'Period' [package "lubridate"] with 6 slots`
`  .. ..@ .Data : num  6 9`
`  .. ..@ year  : num  0 0`
`  .. ..@ month : num  0 0`
`  .. ..@ day   : num  0 0`
`  .. ..@ hour  : num  4 7`
`  .. ..@ minute: num  5 8`

I'm not 100% certain whether this is a Period bug or a filter bug (although dplyr::bind_rows shows similar strange behavior).

**Comment by vspinu** [comment]
It's dplyr issue. It doesn't handle generic vectors (S4 classes) well. They are working on it, but there is no solution on the horizon AFAIK. There have been a number of [similar issues](https://github.com/tidyverse/lubridate/search?q=dplyr&state=closed&type=Issues&utf8=%E2%9C%93) here in case you are interested.
