### ISSUE TITLE
Interoperability between 'difftime' and 'Period' objects

### ISSUE THREAD

**Issue by kenahoo** [tidyverse/lubridate#589]
Similar to #323, `difftime` and `Period` objects don't seem to compare usefully:

```
t1 <- Sys.time()
t2 <- t1 + lubridate::hours(1)
(t2 - t1) > lubridate::seconds(60)  # Should be TRUE, but is FALSE
```

I'm guessing a similar fix to #323's will work.

Workaround: use Durations instead of Periods.

**Comment by vspinu** [comment]
In your case it should be FALSE but with 2 hours it indeed should be TRUE

```
t1 <- Sys.time()
t2 <- t1 + lubridate::hours(2)
(t2 - t1) > lubridate::seconds(60)  # Should be TRUE, but is FALSE
```

**Comment by kenahoo** [comment]
@vspinu - why should it be false?  Did you perhaps misread my "seconds" as "minutes"?

**Comment by vspinu** [comment]
Argh. Indeed. I did :/

**Comment by vspinu** [comment]
I have just made Periods, Durations and difftime cross-comparable. This incompleteness were always bugging me as unsatisfactory.
