### ISSUE TITLE
Case where dmy fails

### ISSUE THREAD

**Issue by kendonB** [tidyverse/lubridate#590]
I came across this case today:

``` r
dmy("4, 5 and 6 November 1998")
#> Warning: All formats failed to parse. No formats found.
#> [1] NA
```

A good solution would result in:
``` r
dmy("4, 5 and 6 November 1998")
#> [1] "1998-11-06"
```

Interestingly, it produces the wrong date with two numbers before the month.
``` r
dmy("5 and 6 November 1998")
#> [1] "1998-06-05"
```

**Comment by vspinu** [comment]
> A good solution would result in:

I don't see this as good solution. Why not 4th or 5th? 

> , it produces the wrong date with two numbers before the month.

First two numbers stand for day and month, so you get what you asked for. 

The assumption of lubridate parsing is that there is one date per string. So, I am afraid, in this case you have no choice but to preprocess the dates yourself.
