### ISSUE TITLE
with_tz is not vectorized over `tzone` parameter

### ISSUE THREAD

**Issue by Teebusch** [tidyverse/lubridate#591]
The `with_tz()` function is not vectorized over the tzname argument. Minimal example:

```r
t1 <- lubridate::now()

lubridate::with_tz(t1, "UTC")
# [1] "2017-10-24 12:29:27 UTC"

lubridate::with_tz(rep(t1, 2), "UTC")
# [1] "2017-10-24 12:29:27 UTC" "2017-10-24 12:29:27 UTC"

lubridate::with_tz(rep(t1, 2), rep("UTC", 2))
# Error in as.POSIXlt.POSIXct(x, tz) : invalid 'tz' value 
```

This creates problems when calling `with_tz()` from within `mutate()` like this:
```r
data.frame(t1 = rep(t1), tz = rep("UTC")) %>%
  dplyr::mutate(t2 = lubridate::with_tz(t1, tz))
#  Error in as.POSIXlt.POSIXct(x, tz) : invalid 'tz' value 
```

**Comment by vspinu** [comment]
It doesn't make much sense to vectorize in with_tz as R date-time classes cannot hold heterogeneous timezones within one vector.  There is `force_tzs` in devel but it has an extra `tz_out` argument. See #438 for the discussion. 

Do you have a concrete use case for heterogenuous tz for with_tz or you simply want it to work for the simple tz-replicated case?

**Comment by Teebusch** [comment]
Thank you for patiently pointing out the other discussion. I think `local_time()` and `force_tzs()` provide the functionality I need. 

I'm reading log files into data frames. The logs contain timestamps for a number of events (in UTC), and the local timezone (as a string). I just want to convert the event timestamps to local times and forget about the timezone. 
(In principle I only "need" this to work for the homogenous case (all tz's are the same), since I can apply the time zone to each log individually first and keep the time zone separately for potential later use.)

Given that heterogenous timezones in a vector are not possible the behavior of `with_tz()` makes sense. 

A small remaining "complaint" is that it took me a while to figure out that the vectorization is the problem from the `invalid 'tz' value` error. I thought my timezone strings were somehow invalid.

**Comment by vspinu** [comment]
> The logs contain timestamps for a number of events (in UTC), and the local timezone (as a string).

Are you sure those are UTC or actual times in the specified time-zones?

In a nutshell:
 - If you have UTC and TZ-strings then you need `local_time` (read as UTC, then retrieve local time)
 - If you have time stamp in the specified TZ then you need `force_tz` (read as UTC then `force_tzs`) 

> vectorization is the problem from the invalid 'tz' value error

I guess I can improve on that. I don't want to vectorize for the simple repetition case in `with_tz` because people which are looking for vectorized `with_tz`  actually need `force_tzs` or `local_time` instead. I will add a hint to the error message.

**Comment by Teebusch** [comment]
Thank you! Yes, the timestamps are definitely in UTC, so `force_tz` is not what I need. 
`local_time` seems to be useful, however. I will use a workaround until the function is part of the CRAN release.
I agree that vectorization does not make sense for `with_tz` if the output vector cannot have heterogenous timezones.
