### ISSUE TITLE
Not available for R 3.4.2

### ISSUE THREAD

**Issue by Mcmlxxxi** [tidyverse/lubridate#592]
Hi! Lubricate is not available for R ver 3.4.2 Can you fix it? Thx.

**Comment by vspinu** [comment]
New version is waiting in CRAN's pipeline (ftp://cran.r-project.org/incoming/recheck/) since 8th of October. CRAN maintainers are currently very busy.  Nothing I can do except of pinging them in another week or so.

**Comment by Mcmlxxxi** [comment]
THX
