### ISSUE TITLE
Time zone stripped when vectorizing date created with ymd_hms() on Linux

### ISSUE THREAD

**Issue by jmaddalena** [tidyverse/lubridate#593]
When we simply run the command, `ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver')`, the results are consistent. However, when we vectorize
 `c(ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver'))`, we obtain different results on Mac and on Linux:

On Mac (R version 3.4.0):
```
> c(ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver'))
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
[1] "2017-10-24 00:30:00 UTC"
```
On Linux VM (R version 3.3.3):
```
> c(ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver'))
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
[1] "2017-10-23 18:30:00 MDT"
```

It appears that when the date is vectorized on the Linux VM, the time zone is stripped and the date is automatically converted to UTC.  

Both the Mac and the Linux VM are running lubridate version 1.6.0.

**Comment by tybyers** [comment]
I am also seeing this on R Linux version 3.4:

Compare behavior on Linux:
```
> R.version.string
[1] "R version 3.4.2 (2017-09-28)"
> Sys.info()['sysname']
sysname 
"Linux" 
> lubridate::ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver')
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
[1] "2017-10-23 18:30:00 MDT"
> c(lubridate::ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver'))
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
[1] "2017-10-24 00:30:00 UTC"
```


To (correct) behavior on Mac, running same version of R:
```
> R.version.string
[1] "R version 3.4.2 (2017-09-28)"
> Sys.info()['sysname']
 sysname 
"Darwin" 
> lubridate::ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver')
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
[1] "2017-10-23 18:30:00 MDT"
> c(lubridate::ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver'))
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
[1] "2017-10-23 18:30:00 MDT"
```

**Comment by vspinu** [comment]
R's `c` function strips attributes, as documented in its help file. 

```R
> attributes(c(ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver')))
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
$class
[1] "POSIXct" "POSIXt" 

> attributes(ymd_hms('2017-10-23T18:30:00-06:00', tz = 'America/Denver'))
Date in ISO8601 format; converting timezone from UTC to "America/Denver".
$tzone
[1] "America/Denver"

$class
[1] "POSIXct" "POSIXt" 
```

That being said, this should not impact your results. It's the same instant after all, just in different tzone. You can always call `with_tz` on it to fix that.

Also, to avoid that warning you better do `with_tz(ymd_hms(x), tz = "America/Denver")`. it's more explicit, so you won't fall into the confusing "merely-display" issues like the one you reported.
