### ISSUE TITLE
as_datetime("2017-01-20") returns NA, breaks compatibility

### ISSUE THREAD

**Issue by mmitkevich** [tidyverse/lubridate#597]
Hi, latest as_datetime doesn't parse ISO time string any more.
```R
> lubridate::as_datetime("2017-01-20")
[1] NA
Warning message:
All formats failed to parse. No formats found. 
```
I had to insert old implementation
```R
setMethod("as_datetime", "character",
          function(x, tz = "UTC") {
            with_tz(as.POSIXct(x), tzone = tz)
          })
```

into my code to revert to old semantics. It breaked my code.

Why shouldn't `as_datetime` parse dates without time as midnights?

**Comment by vspinu** [comment]
Hm. This breaking change slipped my radar. Consequence of #536 and #527. We want a consistent behavior of all of the parsing code. Will fix in a moment.
