### ISSUE TITLE
Issue with Lubridate 1.7.0 and "America/Chicago"

### ISSUE THREAD

**Issue by BadgerEnergy** [tidyverse/lubridate#603]
After updating to v1.7.0 it seems that `lubridate` no longer considers `"America/Chicago"` a time zone yet multiple other CST time zones are still recognized.

```
> ISOdatetime(2016, 1, 1, 0, 0, 0, tz = "America/Chicago") - lubridate::years(1)
Error in (function (dt, year, month, yday, mday, wday, hour, minute, second,  : 
  Invalid timezone of input vector: "America/Chicago"
> ISOdatetime(2016, 1, 1, 0, 0, 0, tz = "Canada/Central") - lubridate::years(1)
[1] "2015-01-01 CST"
> ISOdatetime(2016, 1, 1, 0, 0, 0, tz = "US/Central") - lubridate::years(1)
[1] "2015-01-01 CST"
```

R version 3.4.1 (2017-06-30)

**Comment by vspinu** [comment]
What system is this? Is this mac? Can you please check this with github version? This should be fixed and a patch release is pending CRAN review at the moment.

**Comment by vspinu** [comment]
ISOdatetime is not a lubridate function. It's from R's base namespace. `make_datetime` is from lubridate:

```R
> make_datetime(2016, 1, 1, 0, 0, 0, tz = "America/Chicago")
[1] "2016-01-01 CST"
```

Please re-open if you have any issues.
