### ISSUE TITLE
Error during installation on CentOS 6.6 from CRAN

### ISSUE THREAD

**Issue by msapunov** [tidyverse/lubridate#604]
> install.packages("lubridate")
Selection: 29
trying URL 'https://cran.biotools.fr/src/contrib/lubridate_1.7.1.tar.gz'
Content type 'application/x-gzip' length 399040 bytes (389 KB)
==================================================
downloaded 389 KB

* installing *source* package 'lubridate' ...
** package 'lubridate' successfully unpacked and MD5 sums checked
** libs
g++ -std=c++11 -I/softs/R/R-3.3.2/gcc.4.9.2/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I/usr/local/include -I"/softs/R/R-3.3.2/gcc.4.9.2/lib64/R/library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:20:7: error: 'newDatetimeVector' in namespace 'Rcpp' does not name a type
 Rcpp::newDatetimeVector C_update_dt(const Rcpp::NumericVector& dt, const Rcpp::IntegerVector& year, const Rcpp::IntegerVector& month, const Rcpp::IntegerVector& yday, const Rcpp::IntegerVector& mday, const Rcpp:
       ^
RcppExports.cpp: In function 'SEXPREC* _lubridate_C_update_dt(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)':
RcppExports.cpp:37:123: error: 'C_update_dt' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(C_update_dt(dt, year, month, yday, mday, wday, hour, minute, second, tz, roll, week_start));
                                                                                                                           ^
RcppExports.cpp: At global scope:
RcppExports.cpp:42:7: error: 'newDatetimeVector' in namespace 'Rcpp' does not name a type
 Rcpp::newDatetimeVector C_force_tz(const Rcpp::NumericVector dt, const Rcpp::CharacterVector tz, const bool roll);
       ^
RcppExports.cpp: In function 'SEXPREC* _lubridate_C_force_tz(SEXP, SEXP, SEXP)':
RcppExports.cpp:50:57: error: 'C_force_tz' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(C_force_tz(dt, tz, roll));
                                                         ^
RcppExports.cpp: At global scope:
RcppExports.cpp:55:7: error: 'newDatetimeVector' in namespace 'Rcpp' does not name a type
 Rcpp::newDatetimeVector C_force_tzs(const Rcpp::NumericVector dt, const Rcpp::CharacterVector tzs, const Rcpp::CharacterVector tz_out, const bool roll);
       ^
RcppExports.cpp: In function 'SEXPREC* _lubridate_C_force_tzs(SEXP, SEXP, SEXP, SEXP)':
RcppExports.cpp:64:67: error: 'C_force_tzs' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(C_force_tzs(dt, tzs, tz_out, roll));
                                                                   ^
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package 'lubridate'
* removing '/softs/R/R-3.3.2/gcc.4.9.2/lib64/R/library/lubridate'

The downloaded source packages are in
	'/tmp/Rtmp7bUkQT/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("lubridate") :
  installation of package 'lubridate' had non-zero exit status
>

**Comment by vspinu** [comment]
Very outdated Rcpp?

**Comment by msapunov** [comment]
No Rcpp has been installed on the machine at all. Issued is fixed.
