### ISSUE TITLE
latest version of lubridate (1.7.1) time zone bug

### ISSUE THREAD

**Issue by gongkai06** [tidyverse/lubridate#606]
I installed the latest version (1.7.1) by using devtools::install_github("tidyverse/lubridate"). However, it cannot be properly installed on my Windows computer. The previous version (1.6.0) runs very well. The following is the error information:

-------------------
> devtools::install_github("tidyverse/lubridate")
Downloading GitHub repo tidyverse/lubridate@master
from URL https://api.github.com/repos/tidyverse/lubridate/zipball/master
Installing lubridate
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/n1510071/AppData/Local/Temp/RtmpYtaM5W/devtools232c9d334e6/tidyverse-lubridate-b21a3cd" --library="C:/Program Files/R/R-3.4.1/library"  \
  --install-tests 

* installing *source* package 'lubridate' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c datetime.c -o datetime.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c period.c -o period.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c tparse.c -o tparse.o
**tparse.c: In function 'C_parse_dt':
tparse.c:360:26: warning: 'oMIN' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oMIN)[i] = NA_INTEGER;**
                          ^
tparse.c:359:27: warning: 'oHOUR' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oHOUR)[i] = NA_INTEGER;
                           ^
tparse.c:358:26: warning: 'oDAY' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oDAY)[i] = NA_INTEGER;
                          ^
tparse.c:357:28: warning: 'oMONTH' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oMONTH)[i] = NA_INTEGER;
                            ^
tparse.c:356:27: warning: 'oYEAR' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oYEAR)[i] = NA_INTEGER;
                           ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c update.cpp -o update.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
c:/Rtools/mingw_32/bin/ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o lubridate.dll tmp.def RcppExports.o datetime.o period.o tparse.o update.o utils.o -L. -lcctz -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/i386 -lR
installing to C:/Program Files/R/R-3.4.1/library/lubridate/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c datetime.c -o datetime.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c period.c -o period.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c tparse.c -o tparse.o
tparse.c: In function 'C_parse_dt':
tparse.c:337:26: warning: 'oMIN' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oMIN)[i] = M;
                          ^
tparse.c:336:27: warning: 'oHOUR' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oHOUR)[i] = H;
                           ^
tparse.c:335:26: warning: 'oDAY' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oDAY)[i] = d;
                          ^
tparse.c:334:28: warning: 'oMONTH' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oMONTH)[i] = m - 1;
                            ^
tparse.c:333:27: warning: 'oYEAR' may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oYEAR)[i] = y - 1900;
                           ^
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c update.cpp -o update.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"C:/Program Files/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
c:/Rtools/mingw_64/bin/ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o lubridate.dll tmp.def RcppExports.o datetime.o period.o tparse.o update.o utils.o -L. -lcctz -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
installing to C:/Program Files/R/R-3.4.1/library/lubridate/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\lubridate.dll to C:\Program Files\R\R-3.4.1\library\lubridate\libs\x64\lubridate.dll: Permission denied
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (lubridate)
Reloading installed lubridate

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

    date

**Comment by gongkai06** [comment]
> library(lubridate)
> lubridate::with_tz(Sys.time(), "America/Vancouver")
Error in C_valid_tz(tzone) : object '_lubridate_C_valid_tz' not found
> lubridate::with_tz(Sys.time())
Error in C_valid_tz(tzone) : object '_lubridate_C_valid_tz' not found
> ymd('1999-01-01', tz = 'US/Central')
Error in parse_dt(x, format, TRUE, FALSE, cutoff_2000) : 
  object 'C_parse_dt' not found
> ymd('1999-01-01')
Error in parse_dt(x, format, TRUE, FALSE, cutoff_2000) : 
  object 'C_parse_dt' not found

**Comment by gongkai06** [comment]
I reinstalled to the lower version 1.6.0, and it has similar installation message as 1.7.1. But the R command works very well.
-----
> lubridate::with_tz(Sys.time(), "America/Vancouver")
[1] "2017-11-06 14:23:51 PST"

**Comment by vspinu** [comment]
What about installing from CRAN, does it work?

Try to re-install Rcpp and re-install lubridate. It works on my windows machine and works on CRAN windows builds, so it must be some local issue with the compilation.

**Comment by gongkai06** [comment]
I installed from CRAN, and it works now. I removed the lubridate package and tried to install from github again, and it also works. Not sure what happens.
