### ISSUE TITLE
date() returns error if only one value in large list is incorrect

### ISSUE THREAD

**Issue by retide** [tidyverse/lubridate#609]
I tried to use date() on large datasets (100,000+ entries) of webscraped data. Currently, one erroneous value causes date to throw an error and not return anything. I tried to work around by handling the error in R, but this makes things slower by 2 orders of magnitude (too slow for my purpose, consider the example below). Wouldn't it be more useful to return NA/NULL (and maybe a warning) for failed conversions when processing large vectors with date()?

> ### Benchmark conversion with lubridate::date()
> d <- rep("2010-05-07", 10000)
> system.time(date(d))
> 
> ### With one wrong value nothing is returned
> d[3] <- "NOTADATE"
> l_d <- date(d)
> 
> ### Sapply with error handle is much much slower
> system.time(l_d2 <- sapply(d, function(x) {
>   x <- try(date(x))
>   ifelse(inherits(x, "try-error"), NA, x)
> }))

**Comment by vspinu** [comment]
`date` is not for character strings. Please use proper parsers (ymd, parse_datetime, parse_datetime2, fast_strptime) or even `as_date` will work.

**Comment by retide** [comment]
Thank you, as_date works fine and fast.
