### ISSUE TITLE
GPLv2 and ASL are incompatible

### ISSUE THREAD

**Issue by QuLogic** [tidyverse/lubridate#610]
The `DESCRIPTION` file says lubridate is GPL-2 and the description notes that some code from cctz is ASL 2.0. However, these two licenses are incompatible, e.g., see [this table](https://fedoraproject.org/wiki/Licensing:Main#Good_Licenses) or [Apache's own notes](https://www.apache.org/licenses/GPL-compatibility.html):
> the FSF has never considered the Apache License to be compatible with GPL version 2

ASL 2.0 _is_ compatible with GPLv3 so if lubridate were under that license, things would be fine (and the combined work would be GPLv3.) The files that say GPL2 _or later_ can be re-licensed no problem. There are other .c files that don't contain a license header and theoretically one needs consent from all contributors to change those licenses. However, looking at the files in GitHub only shows a single contributor so this may be a bit simpler.

cc @dpocock who wrote #383 because this is presumably also a problem for Debian packaging as well.

**Comment by vspinu** [comment]
Thanks for pointing this out. I am the sole author of C/C++ code in lubridate and I can change the license if needed.

Should I be aware of some major consequences of such re-licensing to users and reverse dependencies of lubridate?

**Comment by QuLogic** [comment]
Well, IANAL, so I can only say as much as Google, probably. ;) I believe the major changes are the anti-tivoization clause and the explicit patent grant (which is in ASL anyway).

**Comment by khotilov** [comment]
@vspinu The cctz code that is included in lubridate was released by Google, so you cannot change its license.  Changing the package license to GPLv3+ might be the most reasonable and the least disruptive change.

**Comment by vspinu** [comment]
I have decided to move cctz interface out into a separate R package; earlier or later I will have to do that anyways. Will try to fix this within a week or two. Sorry for the delay.

**Comment by vspinu** [comment]
The intention was always to release under GPL (>= 2) as the internal files stipulate and licencing prior to ba7e0fe16a stated. The DESCRIPTION now states this clearly. I am also on my way of moving CCTZ out of the package, so the issue should be considered solved either way. Sorry for all the caused trouble.

**Comment by QuLogic** [comment]
BTW, I just found [RcppCCTZ](https://cran.r-project.org/web/packages/RcppCCTZ/index.html) if you don't want to handle the separate package yourself.
