### ISSUE TITLE
Compile issue on 1.7.1 (Ubuntu, Rcpp related)

### ISSUE THREAD

**Issue by drexell0680** [tidyverse/lubridate#612]
I attempted to install lubridate 1.7.1 as part of the tidyverse install from CRAN, but ran into an error (below).  To fix, I had to update Rcpp from 0.12.8 to 0.12.13.   

I'm on g++ 6.2.0, R 3.3.3, Ubuntu 14.04.

--Dan
 
> In file included from /usr/lib/R/site-library/Rcpp/include/Rcpp/date_datetime/date_datetime.h:31:0,
>                  from /usr/lib/R/site-library/Rcpp/include/Rcpp.h:60,
>                  from update.cpp:1:
> /usr/lib/R/site-library/Rcpp/include/Rcpp/date_datetime/newDatetimeVector.h: In instantiation of ‘Rcpp::newDatetimeVector::newDatetimeVector(const Rcpp::VectorBase<RHS_RTYPE, RHS_NA, RHS_T>&) [with int RTYPE = 14; bool NA = true; VEC = Rcpp::Vector<14, Rcpp::PreserveStorage>]’:
> update.cpp:144:56:   required from here
> /usr/lib/R/site-library/Rcpp/include/Rcpp/date_datetime/newDatetimeVector.h:34:32: error: ‘const class Rcpp::VectorBase<14, true, Rcpp::Vector<14, Rcpp::PreserveStorage> >’ has no member named ‘attr’
>                  setClass(other.attr("tzone"));
>                           ~~~~~~^~~~
> make: *** [update.o] Error 1
> ERROR: compilation failed for package ‘lubridate’
> * removing ‘/data/exposure_response_course/lib/lubridate’

**Comment by vspinu** [comment]
Old Rcpp. I guess I can make an explicit dependence on 0.12.13 then. Is this the reason why you have opened this issue?

**Comment by drexell0680** [comment]
Yeah, it is why I opened the issue -- feel free to close.  I just wanted to
have the solution somewhere for posterity.
