### ISSUE TITLE
Changes in calculated intervals when left_joining

### ISSUE THREAD

**Issue by Stighebbelstrup** [tidyverse/lubridate#614]
Why does the calculated interval of dates change, when left_joining?

library(dplyr)
library(lubridate)

#works in the expected way and the calculated interval is the same before and after left-joining
dates1<-c("2016-02-08", "2016-02-10")
dates2<-c("2016-02-11", "2016-02-13")
interval1<-interval(dates1, dates2)
id<-1:2
id2<-c(1,1)

collected_df<-data.frame(dates1, dates2, interval1, id, id2)
df1<-collected_df[1,]
df2<-collected_df[2,]
merged_df<-left_join(df1, df2, by="id2")

#does not work. The calculated interval has changed after joining.
empty1<-c(1,1)
empty2<-c(1,1)
empty3<-c(1,1)
empty4<-c(1,1)
empty5<-c(1,1)
collected_df_2<-data.frame(dates1, empty1,empty2, dates2, empty3,empty4,interval1, id, id2)
df3<-collected_df[1,]
df4<-collected_df[2,]
merged_df2<-left_join(df3, df3, by="id2")

**Comment by vspinu** [comment]
It's dplyr problem. It doesn't handle generalized S4 vectors well. There is little we can do at lubridate side at the moment.

**Comment by Stighebbelstrup** [comment]
Ok. Thank you for your quick response!

**Comment by mustafaascha** [comment]
Just wanted to echo that I also ran into this issue. It would be really helpful to see a warning when trying joins with intervals :)

**Comment by vspinu** [comment]
> warning when trying joins with intervals :)

That's again, something that only dplyr itself can do.

For reference:

hadley/vctrs#27
tidyverse/dplyr#2432
tidyverse/dplyr#1581
