### ISSUE TITLE
Dekadal intervals and dekadal date format

### ISSUE THREAD

**Issue by mbacou** [tidyverse/lubridate#617]
In the biophysical sciences I often have to deal with dekadal time series (periods of 10 days, 3 each month, usually broken at day 11 and day 21 of the month). I find myself relying on naive helpers (e.g. below) to create these periods and to convert any date-time to its dekadal representation. What about adding dekadal sequences to `lubridate::interval(..., by="dekad")` and a `dekad()` method similar to `day()` to get/set the dekadal component of a date-time?

For info an example of dekadal calendar is e.g. here:
https://earlywarning.usgs.gov/fews/product/114 

Any feedback?

```r
#' Make dekadal (10-day) sequences
#'
#' @param x length-2 start and end dates
#' @param ... other argumnents passed to \code{\link{seq}}
#' @return dekadal 10-day sequence over \code{x}
#' @importFrom lubridate floor_date day
#' @export
dekads <- function(x, ...) {
  x <- as.Date(x)
  res <- unique(floor_date(seq.Date(x[1], x[2], by="day", ...), "10days"))
  res <- res[day(res)!=31]
  return(res)
}

#' Format date as yearly or monthly dekad (10-day period)
#'
#' @param x date to convert to dekad
#' @param type dekad of month (1:3) or year (1:36)
#' @param ... other arguments passed to \code{\link{as.Date}}
#' @return integer dekad
#' @importFrom lubridate floor_date day
#' @export
dekad <- function(x, type = c("month", "year"), ...) {
  type <- match.arg(type)
  x <- as.Date(x, ...)
  res <- ifelse(day(x) > 20,  3, ifelse(day(x) > 10, 2, 1))
  if(type == "year") res <- month(x)*3 + res - 3
  return(res)
}
```

**Comment by vspinu** [comment]
Is your `decads` same as floor_date to breaks of 11, 21,1?

```R
> floor_date(ymd("2017-12-2", "2017-12-13", "2017-12-23"), "10days")
[1] "2017-12-01" "2017-12-11" "2017-12-21"
```

Adding `dekad` and `dekad<-` is not a big deal, but how common is that? I never heard of such conventions and "dekad" rings as "decade" to me. I would be open to add those only if there is an some international convention on this.

**Comment by mbacou** [comment]
Yes, thx for pointing out the use of `floor_date()` (haven't scanned the entire lubridate doco yet!). Hard to gauge the use of dekadal intervals in the general sciences. They're very common in climatology though. I'll wait for others to weigh in.

**Comment by mcooper** [comment]
A little late to the conversation, but I found this thread by searching to see if lubridate supports dekads.  So at least one other scientist could benefit from that feature.

**Comment by danielreispereira** [comment]
+1

**Comment by hicardoso** [comment]
lllkl

**Comment by hicardoso** [comment]
`(days since 1960-01-01) ordered [ (1-10 Dec 1999) (11-20 Dec 1999) (21-31 Dec 1999) ... (1-10 Jan 2019)]`
How to write it in R script?

**Comment by mbacou** [comment]
2 simple functions here:

```r
#####################################################################################
#' Make dekadal (10-day) sequences
#'
#' @param x length-2 start and end dates
#' @inheritDotParams base::seq.Date
#' @return dekadal 10-day sequence over \code{x}
#' @importFrom lubridate floor_date day
#' @examples
#' dekads(Sys.Date() - c(50, 0))
#' @export
dekads <- function(x, ...) {
  x <- as.Date(x)
  res <- unique(floor_date(seq.Date(x[1], x[2], by="day", ...), "10days"))
  res <- res[day(res)!=31]
  return(res)
}

#####################################################################################
#' Format date as yearly or monthly dekad (10-day period)
#'
#' @param x date to convert to dekad
#' @param type dekad of month (1:3) or year (1:36)
#' @inheritDotParams base::as.Date
#' @return integer dekad
#' @importFrom lubridate floor_date day
#' @examples
#' dekad(Sys.Date())
#' @export
dekad <- function(x, type = c("month", "year"), ...) {
  type <- match.arg(type)
  x <- as.Date(x, ...)
  res <- ifelse(day(x) > 20,  3, ifelse(day(x) > 10, 2, 1))
  if(type == "year") res <- month(x)*3 + res - 3
  return(res)
}
```

**Comment by hicardoso** [comment]
Mrs. Mbacou,

Thanks for your quick replay.

I tried to run the function it done for a single month, how to use for a year (36 decades)?

I've a series of data 1969 to 2018, and I want to calculate decades values for all series.

best regards

**Comment by hadley** [comment]
I think this is out of scope for lubridate, but would be an excellent idea for a new package!

**Comment by mbacou** [comment]
@hicardoso see ` @param type` in the 2nd function.

**Comment by peetmate** [comment]
> 2 simple functions here:
> 
> ```r
> #####################################################################################
> #' Make dekadal (10-day) sequences
> #'
> #' @param x length-2 start and end dates
> #' @inheritDotParams base::seq.Date
> #' @return dekadal 10-day sequence over \code{x}
> #' @importFrom lubridate floor_date day
> #' @examples
> #' dekads(Sys.Date() - c(50, 0))
> #' @export
> dekads <- function(x, ...) {
>   x <- as.Date(x)
>   res <- unique(floor_date(seq.Date(x[1], x[2], by="day", ...), "10days"))
>   res <- res[day(res)!=31]
>   return(res)
> }
> 
> #####################################################################################
> #' Format date as yearly or monthly dekad (10-day period)
> #'
> #' @param x date to convert to dekad
> #' @param type dekad of month (1:3) or year (1:36)
> #' @inheritDotParams base::as.Date
> #' @return integer dekad
> #' @importFrom lubridate day
> #' @examples
> #' dekad(Sys.Date())
> #' @export
> dekad <- function(x, type = c("month", "year"), ...) {
>   type <- match.arg(type)
>   x <- as.Date(x, ...)
>   res <- ifelse(day(x) > 20,  3, ifelse(day(x) > 10, 2, 1))
>   if(type == "year") res <- month(x)*3 + res - 3
>   return(res)
> }
> ```

This should definitely be in the package! it's very useful.
