### ISSUE TITLE
Issue with Installing R packages on R server

### ISSUE THREAD

**Issue by ArpitJainGrab** [tidyverse/lubridate#623]
Hi Hadley,

I have an AWS EMR server (with CentOS 7 as its OS). I want to run R scripts on it.

 After installing R, when I tried installing R packages, in most cases I was getting the following errors in the results. 

1.   Error in .shlib_internal(args) : 
  C++11 standard requested but CXX11 is not defined
 2.  installation of package 'lubridate' had non-zero exit status

Some sources said there is an issue with CentOS 7 (the Server OS), and the gcc compiler in it, but am not sure how to fix it. Please help me.

Best Regards,
Arpit Jain

**Comment by vspinu** [comment]
You need gcc 4.8+. See #601. That's the requirement from CCTZ which we really need to push things forward.

**Comment by ArpitJainGrab** [comment]
I have 
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9) installed, but am still getting the same error
C++11 standard requested but CXX11 is not defined

**Comment by vspinu** [comment]
Strange. A cursory search shows that C++11 [works on gcc4.8.1](https://stackoverflow.com/questions/21221411/when-will-gnu-c-support-c11-without-explicitly-asking-for-it). So looks like some local issue. What is the full output of the instalation? Are you sure R picks the right compiler? Do you see -std=c++11 in the compilation command? 

I haven't tried 4.8 myself. I picked that number from the description of [rcppcctz](https://github.com/eddelbuettel/rcppcctz/blob/master/DESCRIPTION). Lubridate uses a smaller subset of cctz, so whatever works for them should work for lubridate as well. Could you try and install rcppcctz to see if it works?
