### ISSUE TITLE
Century conversion is not proper (using version 1.7.1)

### ISSUE THREAD

**Issue by vidyasagarbhargava** [tidyverse/lubridate#624]
I have dates like in format "30/11/56", "23/08/68", "01/01/69", "06/04/76" etc in a column name date_of_birth. Using lubridate package for conversion from character to date like below:

 

>    library(lubridate)
>     df$date_of_birth<-dmy(df$date_of_birth)

But this is giving me output like "2056-11-30", "2068-08-23" "1969-01-01","1976-04-06" etc. However it should be like "1956-11-30",1968-08-23" for first two date.
Issue is with year before 1969 only.

**Comment by vspinu** [comment]
68 is the cutoff for "y" format (when century is not available). You will see this with strptime as well not only lubridate parsing. Use this instead:

```R
> parse_date_time2("01/01/10", "dmy", cutoff_2000 = 0)
[1] "1910-01-01 UTC"
```

There is no way to bring this cutoff to higher level functions like `ymd` because base R doesn't support.
