### ISSUE TITLE
Update local tidytemplate w/ fixed pkgdown link

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/lubridate#627]

**Comment by vspinu** [comment]
Dare to elaborate?

**Comment by batpigandme** [comment]
Sorry about that: a recent PR to tidytemplate fixed the broken pkgdown link that goes to (the now defunct) hadley.github.io/pkgdown. So, hadley asked me to ensure that the tidyverse package maintainers had updated versions locally for subsequent builds:
https://github.com/tidyverse/tidytemplate/pull/6#issuecomment-359265304
