### ISSUE TITLE
Conflict between packages 'here' and 'lubridate'

### ISSUE THREAD

**Issue by curtisburkhalter** [tidyverse/lubridate#632]
Not a big issue, but I was recently trying to use the 'here' function from package 'here' and lubridate masks the 'here' function. When writing scripts to be 'transportable' it's nice to use the 'here' function.  I know I can override this using something like 'here <- package::here', but I wanted to let you know in case anyone else was interested.

**Comment by vspinu** [comment]
`here` in lubridate is deprecated and will be removed soon. Just load `here` after lubridate for now.

**Comment by curtisburkhalter** [comment]
Thank you Vitalie

On Feb 5, 2018 2:19 PM, "Vitalie Spinu" <notifications@github.com> wrote:

here in lubridate is deprecated and will be removed soon. Just load here
after lubridate for now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tidyverse/lubridate/issues/632#issuecomment-363191731>,
or mute the thread
