### ISSUE TITLE
Vector repetition warning

### ISSUE THREAD

**Issue by antbbn** [tidyverse/lubridate#634]
Hello, 
This morning I encountered a strange Warning when performing interval division by a period using vectors.
I'm using lubridate version 1.6.0.  and I tested with R version 3.4.0 (2017-04-21) and R version 3.4.1 (2017-06-30).

This example reproduces the warning,
```
library(lubridate)

start_date_str <- '2015-04-21'
end_date_str <- '2017-01-20'

vec1 <- c(ymd(start_date_str),ymd(start_date_str))
vec2 <- c(ymd(end_date_str),ymd(end_date_str))
vec3 <- c(months(1),months(2))

vec4 <- interval(vec1,vec2)
vec4/vec3
vec4[1]/vec3[1]
vec4[2]/vec3[2]
```

For me the output looks like this:
```
[1] 21.48387 10.48387
Warning message:
In NextMethod(.Generic) :
  number of items to replace is not a multiple of replacement length

[1] 21.48387

[1] 10.48387
````

So the result is correct,  but I don't understand that warning, and most importantly it does not happen when I perform the division element by element.

What do you guys think?

Thanks,
Antonio Bibiano

**Comment by vspinu** [comment]
1.6 is a pretty old version by now. I don't see this in 1.7.2.

**Comment by antbbn** [comment]
Thanks for checking!

I updated my lubridate package and I can confirm that the warning does not appear anymore.

I will close this one.
