### ISSUE TITLE
Support lunar and martian calendars

### ISSUE THREAD

**Issue by perrystephenson** [tidyverse/lubridate#636]
It's only a matter of time before someone will be working with time-stamped data from a mission to the Moon or Mars, and despite our use of Coordinated "Universal" Time, we don't really have a way to convert and manage these times.

If lubridate can provide this functionality, then there is a good chance that R/tidyverse could become the number 1 programming language on Mars.

**Comment by vspinu** [comment]
I am sure someone will create `lubrimoon` and `lubrimars` packages by then ;)

**Comment by perrystephenson** [comment]
https://www.reuters.com/science/white-house-directs-nasa-create-time-standard-moon-2024-04-02/
