### ISSUE TITLE
Put Dates and Times Cheat Sheet thumbnail in README

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/lubridate#641]

**Comment by vspinu** [comment]
Do you expect me to read your mind? It's the second time you post like this here. Please describe the issue and the proposed solution.

**Comment by batpigandme** [comment]
Hi @vspinu,

Sorry. @hadley had asked me to file issues in the affiliated repos to add thumbnails of cheatsheet images to the READMEs. I'm not sure exactly how he'd like things arranged, so I don't yet have a proposed solution. However, when the desired implementation is clear (I'm not sure hadley knows either at this point, so telepathy wouldn't necessarily help), I can take care of it and/or propose an appropriate solution here.

So, in sum:
**Issue**
Hadley asked me to file issues in the tidyverse repos with associated cheat sheets for adding thumbnails of said cheat sheets to their respective READMEs.
**Proposed solution**
Yet to be determined.

**Comment by batpigandme** [comment]
Meta-proposed-solution: (cc @hadley)
I've forked the repo and opened up issues in there, so I can track lubridate-related non-code tasks there and in my projects without disturbing @vspinu.

**Comment by vspinu** [comment]
Ok. Thanks. I am still confused of what this is all about, but well ... let me know when and how I can help.

**Comment by hadley** [comment]
I think the title is fairly self-explanatory - it would be nice if the readme linked to the lubridate cheatsheet (using thumbnails of the pages)

**Comment by vspinu** [comment]
Well, I wasn't even aware that Rstudio made a cheatsheet for lubridate. So I inferred from the title that the OP wants me to do the cheatsheet.

**Comment by batpigandme** [comment]
Indeed it does. Unfortunately, the links on the cheat sheet page all ⇨ download prompts, which makes linking to them ~awkward. (When I do so on twitter or wherever, I often just say which cheat sheet's been updated, and then link to rstudio.com/resources/cheatsheets).
[![image](https://user-images.githubusercontent.com/831732/36491529-f05e5b5c-16f8-11e8-9bef-9554ad6fa2d4.png)](https://www.rstudio.com/resources/cheatsheets/)

**Comment by garrettgman** [comment]
@batpigandme for a less awkward link, you could link straight to the cheatsheets in their github repository, https://github.com/rstudio/cheatsheets
