### ISSUE TITLE
ifelse behavior

### ISSUE THREAD

**Issue by agricolamz** [tidyverse/lubridate#644]
I found a strange behavior of `lubridate` package with `ifelse` statement:
```
ifelse(hm("25:00") > hm("24:00"), hm("24:00")+hm("24:00"), hm("24:00"))
```
returns `0` instead of `"48H 0M 0S"`.

[This question](https://stackoverflow.com/questions/32013013/ifelse-statement-returning-number-instead-of-date) looks like to mention the same topic.

Is it possible to change it?

**Comment by yutannihilation** [comment]
As described in the SO, it's `ifelse()`'s fault and cannot be fixed on lubridate's side, unfortunately. If you try `ifelse(TRUE, Sys.Date(), Sys.Date())` or `ifelse(TRUE, factor("a"), factor("a"))`, the problem may be a bit more clearer.

I recommend using `dplyr::if_else()` always.

**Comment by agricolamz** [comment]
Cool! Thank you!

**Comment by vspinu** [comment]
This is due to the internal S4 representation of periods which many R (and dplyr) functions don't understand.  In the potential rewrite of lubridate this should be taken care of.

**Comment by yutannihilation** [comment]
@vspinu IIUC, this is merely the problem of `ifelse()`'s implementation. Here's simplified version of `ifelse()`:

```r
ifelse_ <- function(test, yes, no) {
  # wat??
  ans <- test
  
  ans[test]  <- rep(yes, length.out = length(ans))[test]
  ans[!test] <- rep(no, length.out = length(ans))[!test]
  
  ans
}
```

As you see, any type of `yes` or `no` is roughly thrown into `test`, a logical vector. So, there's no hope that the type will be preserved...
