### ISSUE TITLE
Make cut method for instants

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/lubridate#65]
A cut function would be sensible for any date-time class that measures an instant, such as POSIXct, POSIXlt, Date, and well all of them except difftime and the ones we've created: period, duration, interval.

As long as the date-times of x are measured in classes we've made compatible with lubridate, we can turn the range into an interval object. From there we could turn it into a duration to do an exactly spaced cut, or a period to cut by units such as days, hours, etc. Once we do the cut, we can assign each x its marker variable and let it keep its orginal date-time stamp in whatever class it came in.

**Comment by xhdong-umd** [comment]
@garrettgman I found `cut.POSIXt` has serious limitations. Basically it will not give proper break values if the breaks didn't match the original input.

In [this bug report](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=14288) the purposed fix is kept until today. However it didn't work with this simple case:

```
x <- seq(as.POSIXct("2000-01-01"), by = "days", length = 20)
> cut(x, breaks = 30)
Error in `levels<-.factor`(`*tmp*`, value = as.character(if (is.numeric(breaks)) x[!duplicated(res)] else breaks[-length(breaks)])) : 
  number of levels differs
```

The code used cut on numeric values, then it didn't bother to convert the break values into date-time, instead [it picked from the original input](https://github.com/wch/r-source/blob/trunk/src/library/base/R/datetime.R#L882). So this will not work if the breaks didn't match the original values.

I think to fix the bug will need either
- get the actual numeric value of the breaks from `cut`, modify `cut` if needed. Then convert the numeric value back to date-time.
- or use regex to extract the break value then convert to date-time. This will be ugly but maybe it's the only way if we don't change the return value of `cut`.

I sent a bug report to `r-devel`, but if it cannot be fixed properly, `lubridate` could have a proper version of `cut`.

**Comment by xhdong-umd** [comment]
This is a simple version that only focused on cut POSIXt into even spaced intervals:

```
# focused on one case: cut x into intervals given a number of interval count

# divide x into interval_count intervals. Taken from https://github.com/wch/r-source/blob/trunk/src/library/base/R/cut.R
divide <-
  function (x, interval_count)
  {
      if (is.na(interval_count) || interval_count < 2L)
        stop("invalid number of intervals")
      nb <- as.integer(interval_count + 1) # one more than #{intervals}
      dx <- diff(rx <- range(x, na.rm = TRUE))
      if(dx == 0) {
        dx <- abs(rx[1L])
        breaks <- seq.int(rx[1L] - dx/1000, rx[2L] + dx/1000,
                          length.out = nb)
      } else {
        breaks <- seq.int(rx[1L], rx[2L], length.out = nb)
        breaks[c(1L, nb)] <- c(rx[1L] - dx/1000, rx[2L] + dx/1000)
      }
    return(breaks)
  }

cut_date_time <- function(x, interval_count) {
  brks <- divide(as.numeric(x), interval_count)
  return(cut(x, as_datetime(brks)))
}

divide_date_time <- function(x, interval_count) {
  return(as_datetime(divide(as.numeric(x), interval_count)))
}

```
