### ISSUE TITLE
Error when using weeks() in conjunction with Sys.time()

### ISSUE THREAD

**Issue by MartenMM** [tidyverse/lubridate#650]
I've just upgraded to lubridate 1.7.3 and am thrown an error when using `weeks()` in conjunction with `Sys.time()`:
```
Sys.time() - weeks(2)
Error in (function (dt, year, month, yday, mday, wday, hour, minute, second,  : 
  Invalid timezone of input vector: ""
```

If I wrap `Sys.time()` in `as_datetime()`, it works (but the timezone is shifted to UTC, which is no problem for my specific case but may be unexpected). 
```
as_datetime(Sys.time()) - weeks(2)
```

The error is also thrown when using `Sys.time()` in conjunction with similar function to `weeks()` (e.g. `months()`), so this may be a feature. In lubridate versions prior to 1.7.3 that I have used, `Sys.time() - weeks(2)` always worked. 
I think the right solution would be to assume timezone is UTC if timezone is not set (i.e. `tz(x) == ""`), and warn the user about this.

**Comment by vspinu** [comment]
Could you please check the github version? I thought this issue was fixed in 1.7.3 but it wasn't (#648).

> I think the right solution would be to assume timezone is UTC 

This would violate R's default behavior with tz="". It's a bit complicated.  On lubridate rewrite this will be the case.

**Comment by MartenMM** [comment]
Thanks! The github version seems to solve this issue.

**Comment by dlebauer** [comment]
FWIW I also had this error and it was resolved by installing from github `devtools::install_github('tidyverse/lubridate')`
