### ISSUE TITLE
Eastern Time has wrong difference to UTC (5hrs instead of 4hrs)

### ISSUE THREAD

**Issue by AgatheBauer** [tidyverse/lubridate#654]
According to my research, EST is UTC - 4hrs.

`library('lubridate')

Sys.setenv(TZ='UTC')
UTC <- Sys.time()
Sys.setenv(TZ='EST')
EST <- Sys.time()
EST <- as_datetime(as.character(EST), tz = "UTC")

difference <- difftime(UTC, EST, units = "hours")
print(difference)`

Output:

Time difference of 5.000131 hours

**Comment by vspinu** [comment]
You get what you ask for. Current eastern time is EDT not EST. It's not lubridate specific:

```R
> .POSIXct(as.POSIXct("2018-03-15", tz="UTC"), tz="EST")
[1] "2018-03-14 19:00:00 EST"
> .POSIXct(as.POSIXct("2018-03-15", tz="UTC"), tz="America/New_York")
[1] "2018-03-14 20:00:00 EDT"
```

To avoid such nonesense always use proper time zones. EST/EDT and others are not timezones but offsets.

**Comment by AgatheBauer** [comment]
Yes, indeed! Thank you @vspinu
