### ISSUE TITLE
Feature request: a function to return both year and month, something like quarter()

### ISSUE THREAD

**Issue by aetiologicCanada** [tidyverse/lubridate#657]
For multi-year boxplots stratified by quarter, the function lubridate::quarter(x, with_year=TRUE) function works wonderfully. quarter() does this by returning a numeric, e.g 2017.1, 2017.2 which strikes me as not exactly "true", but be that as it may, I often find myself using the construct:

geom_boxplot(aes(x=x, y=y, group=as.factor(quarter(x, with_year=TRUE))))

However, when monthly boxplots are required across multiple years I find myself constructing various, never-quite-satisfactory, hacked variants of quarter.  My feature request is for a lubridate function that  returns both the year and month in a single result.

It might be that this is part of month(), or perhaps it needs to be a separate function.

The central challenge is what should be returned?  I suspect a string with values something like:
"YEAR-MONTH", where month has a  leading zero for January to September., e.g. "2017-09".
I think this suggestion conforms with ISO 8601.

However, this suggestion of returning a string would be at odds with  quarter()'s returning of a real (as discussed above). 

A welcome alternative/supplementary suggestion would be to revise month() revised so that it can return not only a numeric or an abbreviation (which are existing features) but also a zero-padded string representing the month number.

Many thanks,

R

**Comment by vspinu** [comment]
You can easily do this with:

```R
> format(now(), "%Y-%m")
[1] "2018-03"
```
