### ISSUE TITLE
Unable to install lubridate  CentOS 6.9

### ISSUE THREAD

**Issue by saberbouabid** [tidyverse/lubridate#659]
Hi guys,
I can't install tidyverse because i'm not able to install lubridate package first. I tried to upgrade my C compiler to 4.9.3 but nothing happen. 

My server is Centos 6. 64 

```shell
> install.packages("lubridate")
Installing package into ‘/home/admin/R/x86_64-redhat-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
essai de l'URL 'https://cran.rstudio.com/src/contrib/lubridate_1.7.3.tar.gz'
Content type 'application/x-gzip' length 447719 bytes (437 KB)
==================================================
downloaded 437 KB

* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ correctement décompressé et sommes MD5 vérifiées
** libs
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c datetime.c -o datetime.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c period.c -o period.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c tparse.c -o tparse.o
tparse.c: In function ‘C_parse_dt’:
tparse.c:338:26: attention : ‘oMIN’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oMIN)[i] = M;
                          ^
tparse.c:337:27: attention : ‘oHOUR’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oHOUR)[i] = H;
                           ^
tparse.c:336:26: attention : ‘oDAY’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oDAY)[i] = d;
                          ^
tparse.c:335:28: attention : ‘oMONTH’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oMONTH)[i] = m - 1;
                            ^
tparse.c:334:27: attention : ‘oYEAR’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         INTEGER(oYEAR)[i] = y - 1900;
                           ^
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c update.cpp -o update.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c utils.c -o utils.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
g++ -m64 -std=gnu++0x -shared -L/usr/lib64/R/lib -o lubridate.so RcppExports.o datetime.o period.o tparse.o update.o utils.o -L. -lcctz -L/usr/lib64/R/lib -lR
installing to /home/admin/R/x86_64-redhat-linux-gnu-library/3.4/lubridate/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘lubridate’
    finding HTML links ... fini
    DateCoercion                            html  
    DateTimeUpdate                          html  
    Deprecated                              html  
    Duration-class                          html  
    Interval-class                          html  
    Period-class                            html  
    Timespan-class                          html  
    am                                      html  
    as.duration                             html  
    as.interval                             html  
    as.period                               html  
    as_date                                 html  
    date                                    html  
    date_decimal                            html  
    day                                     html  
    days_in_month                           html  
    decimal_date                            html  
    dst                                     html  
    duration                                html  
    fit_to_timeline                         html  
    force_tz                                html  
    guess_formats                           html  
    hidden_aliases                          html  
    hms                                     html  
    hour                                    html  
    interval                                html  
    is.Date                                 html  
    is.POSIXt                               html  
    is.difftime                             html  
    is.instant                              html  
    is.timespan                             html  
    lakers                                  html  
    leap_year                               html  
    local_time                              html  
    lubridate-package                       html  
    make_datetime                           html  
Rd warning: /tmp/Rtmpp2bNtP/R.INSTALL1a9d4dd42dcf/lubridate/man/make_datetime.Rd:30: missing file link ‘ISOdate’
    make_difftime                           html  
    minute                                  html  
    month                                   html  
    mplus                                   html  
    now                                     html  
    origin                                  html  
    parse_date_time                         html  
    period                                  html  
    period_to_seconds                       html  
    pretty_dates                            html  
    quarter                                 html  
    reclass_date                            html  
    reclass_timespan                        html  
    rollback                                html  
    round_date                              html  
Rd warning: /tmp/Rtmpp2bNtP/R.INSTALL1a9d4dd42dcf/lubridate/man/round_date.Rd:50: missing file link ‘round’
Rd warning: /tmp/Rtmpp2bNtP/R.INSTALL1a9d4dd42dcf/lubridate/man/round_date.Rd:147: missing file link ‘round’
    second                                  html  
    stamp                                   html  
    time_length                             html  
    timespan                                html  
    today                                   html  
    tz                                      html  
    week                                    html  
    with_tz                                 html  
    within-interval                         html  
    year                                    html  
    ymd                                     html  
    ymd_hms                                 html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘lubridate’ in dyn.load(file, DLLpath = DLLpath, ...):
 impossible de charger l'objet partagé '/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/lubridate/libs/lubridate.so':
  /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/admin/R/x86_64-redhat-linux-gnu-library/3.4/lubridate/libs/lubridate.so)
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/home/admin/R/x86_64-redhat-linux-gnu-library/3.4/lubridate’
Warning in install.packages :
  installation of package ‘lubridate’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpgBPpgF/downloaded_packages’
```

Please help me to understand all requirements and how to resolve this issue
Best,
Saber

**Comment by vspinu** [comment]
Could it be that you installed gcc-4.9 but left alone libstdc++? Or some path messup? 

Judging from [this page](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) gcc-4.9 needs GLIBCXX_3.4.2 on your system.

This is what I have on my ubuntu machine (found [here](https://stackoverflow.com/a/10355215/453735)):

```
~$ /sbin/ldconfig -p | grep stdc++
        libstdc++.so.6 (libc6,x32) => /usr/libx32/libstdc++.so.6
        libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (libc6) => /usr/lib/i386-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (libc6) => /usr/lib32/libstdc++.so.6
~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6  | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by sakshisharma28** [comment]
Getting this error on applying the fix @saberbouabid . What should I do? My version is Centos 6.10

$ make install


make[1]: Entering directory `/home/ssharma4/gcc-4.9.0'
/bin/sh ./mkinstalldirs /usr/local /usr/local
make[2]: Entering directory `/home/ssharma4/gcc-4.9.0/host-x86_64-unknown-linux-gnu/fixincludes'
rm -rf /usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.0/install-tools
/bin/sh ../.././fixincludes/../mkinstalldirs /usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.0/install-tools
mkdir -p -- /usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.0/install-tools
mkdir: cannot create directory `/usr/local/libexec/gcc': Permission denied
make[2]: *** [install] Error 1
make[2]: Leaving directory `/home/ssharma4/gcc-4.9.0/host-x86_64-unknown-linux-gnu/fixincludes'
make[1]: *** [install-fixincludes] Error 2
make[1]: Leaving directory `/home/ssharma4/gcc-4.9.0'
make: *** [install] Error 2

**Comment by sakshisharma28** [comment]
Apply the fix above still getting error. What should I do ?@saberbouabid @vspinu 

> install.packages('tidyverse')
Installing package into ‘/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
also installing the dependency ‘lubridate’

trying URL 'https://cran.rstudio.com/src/contrib/lubridate_1.7.4.tar.gz'
Content type 'application/x-gzip' length 449850 bytes (439 KB)
==================================================
downloaded 439 KB

trying URL 'https://cran.rstudio.com/src/contrib/tidyverse_1.2.1.tar.gz'
Content type 'application/x-gzip' length 61647 bytes (60 KB)
==================================================
downloaded 60 KB

* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ successfully unpacked and MD5 sums checked
** libs
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c datetime.c -o datetime.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c period.c -o period.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c tparse.c -o tparse.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c update.cpp -o update.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c utils.c -o utils.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
g++ -m64 -std=gnu++0x -shared -L/usr/lib64/R/lib -o lubridate.so RcppExports.o datetime.o period.o tparse.o update.o utils.o -L. -lcctz -L/usr/lib64/R/lib -lR
installing to /home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/lubridate/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘lubridate’
    finding HTML links ... done
    DateCoercion                            html  
    DateTimeUpdate                          html  
    Deprecated                              html  
    Duration-class                          html  
    Interval-class                          html  
    Period-class                            html  
    Timespan-class                          html  
    am                                      html  
    as.duration                             html  
    as.interval                             html  
    as.period                               html  
    as_date                                 html  
    date                                    html  
    date_decimal                            html  
    day                                     html  
    days_in_month                           html  
    decimal_date                            html  
    dst                                     html  
    duration                                html  
    fit_to_timeline                         html  
    force_tz                                html  
    guess_formats                           html  
    hidden_aliases                          html  
    hms                                     html  
    hour                                    html  
    interval                                html  
    is.Date                                 html  
    is.POSIXt                               html  
    is.difftime                             html  
    is.instant                              html  
    is.timespan                             html  
    lakers                                  html  
    leap_year                               html  
    local_time                              html  
    lubridate-package                       html  
    make_datetime                           html  
Rd warning: /tmp/RtmpBBcXCO/R.INSTALL2ae322e33d83/lubridate/man/make_datetime.Rd:30: file link ‘ISOdate’ in package ‘base’ does not exist and so has been treated as a topic
    make_difftime                           html  
    minute                                  html  
    month                                   html  
    mplus                                   html  
    now                                     html  
    origin                                  html  
    parse_date_time                         html  
    period                                  html  
    period_to_seconds                       html  
    pretty_dates                            html  
    quarter                                 html  
    reclass_date                            html  
    reclass_timespan                        html  
    rollback                                html  
    round_date                              html  
Rd warning: /tmp/RtmpBBcXCO/R.INSTALL2ae322e33d83/lubridate/man/round_date.Rd:50: file link ‘round’ in package ‘base’ does not exist and so has been treated as a topic
Rd warning: /tmp/RtmpBBcXCO/R.INSTALL2ae322e33d83/lubridate/man/round_date.Rd:147: file link ‘round’ in package ‘base’ does not exist and so has been treated as a topic
    second                                  html  
    stamp                                   html  
    time_length                             html  
    timespan                                html  
    today                                   html  
    tz                                      html  
    week                                    html  
    with_tz                                 html  
    within-interval                         html  
    year                                    html  
    ymd                                     html  
    ymd_hms                                 html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘lubridate’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/lubridate/libs/lubridate.so':
  /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/lubridate/libs/lubridate.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/lubridate’
Warning in install.packages :
  installation of package ‘lubridate’ had non-zero exit status
* installing *source* package ‘tidyverse’ ...
** package ‘tidyverse’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error : package ‘nlme’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package ‘tidyverse’
* removing ‘/home/sakshi/R/x86_64-redhat-linux-gnu-library/3.5/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpyvCw8v/downloaded_packages’
