### ISSUE TITLE
round_date interprets secs > 60 in unexpecteed way

### ISSUE THREAD

**Issue by Holzhauer** [tidyverse/lubridate#661]
Thanks a lot for the helpful package!

>x <- lubridate::ymd_hms("2009-08-03 12:01:57.11")
lubridate::round_date(x, "2 mins")
[1] "2009-08-03 12:02:00 UTC"

but

>lubridate::round_date(x, "120 secs")
[1] "2009-08-03 12:01:00 UTC"

This is dangerous when handling durations e.g. in seconds, only: when the durations exceeds a minute, the result is unexpected. In this case, at least a warning should be issued.

**Comment by vspinu** [comment]
Actually truncation with seconds > 60 was never intended. So I would rather make this an error.

**Comment by rok** [comment]
> Actually truncation with seconds > 60 was never intended. So I would rather make this an error.

@vspinu do you know what was the reason for this design? How about rounding to say 90 minutes?

**Comment by vspinu** [comment]
I thin the main reason is the complexity of implementation. I just didn't have enough time to push it through back then. No conceptual limitation AFAICJ.

**Comment by rok** [comment]
Would you be open to a PR changing this?

**Comment by vspinu** [comment]
Sure!

**Comment by vspinu** [comment]
I have just added a major enhancement to rounding functions - unit can be a date-time vector for arbitrary rounding.

**Comment by rok** [comment]
@vspinu great, I'll try to do something this weekend!
