### ISSUE TITLE
feature request: add argument so wday and month can return an unordered factor

### ISSUE THREAD

**Issue by vnijs** [tidyverse/lubridate#663]
`wday` and `month` are really convenient functions in `lubridate`. It would be great if these two functions had an option to determine if the returned factor should (not) be ordered. I'd prefer the default value for `ordered` would be `FALSE` but I assume that is unlikely

```
wday(
  x, label = FALSE, abbr = TRUE,
  week_start = getOption("lubridate.week.start", 7),
  locale = Sys.getlocale("LC_TIME"),
  ordered = FALSE
)

month(
  x, label = FALSE, abbr = TRUE, locale = Sys.getlocale("LC_TIME"),
  ordered = FALSE
)
```

**Comment by vspinu** [comment]
This one is too small to be worth an extra argument. Week days are ordered, so it's natural to have them ordered. You could use `factor(wday(x), ordered=F)` for this.
