### ISSUE TITLE
months() no longer part of the lubridate namespace ?

### ISSUE THREAD

**Issue by mlobier** [tidyverse/lubridate#665]
Hi,

After getting NA results from some previously working code using the months() function on a Date object: 

`new_date = date - months(6)`

I modified the code to read:
`new_date = date - lubridate::months(6)` 

which throws the error:
Evaluation error: 'months' is not an exported object from 'namespace:lubridate'.

**Comment by vspinu** [comment]
I think @cderv assessment is correct. Your previously working code was on a `date` which resulted in existing date. New `date - month(6)` results in a non-existing date.
