### ISSUE TITLE
Error installing on Debian

### ISSUE THREAD

**Issue by lucadelu** [tidyverse/lubridate#666]
I'm trying to install tidyverse on Debian 9 but I get the following error

```
* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ successfully unpacked and MD5 sums checked
** libs
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:131: recipe for target 'RcppExports.o' failed
make: [RcppExports.o] Error 127 (ignored)
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c datetime.c -o datetime.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c period.c -o period.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c tparse.c -o tparse.o
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c update.cpp -o update.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:131: recipe for target 'update.o' failed
make: [update.o] Error 127 (ignored)
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"   -fpic  -O3 -pipe  -g  -c utils.c -o utils.o
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_fixed.o' failed
make: [cctz/src/time_zone_fixed.o] Error 127 (ignored)
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_if.o' failed
make: [cctz/src/time_zone_if.o] Error 127 (ignored)
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_impl.o' failed
make: [cctz/src/time_zone_impl.o] Error 127 (ignored)
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_info.o' failed
make: [cctz/src/time_zone_info.o] Error 127 (ignored)
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_libc.o' failed
make: [cctz/src/time_zone_libc.o] Error 127 (ignored)
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_lookup.o' failed
make: [cctz/src/time_zone_lookup.o] Error 127 (ignored)
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
/bin/bash: I/usr/share/R/include: No such file or directory
/usr/lib/R/etc/Makeconf:129: recipe for target 'cctz/src/time_zone_posix.o' failed
make: [cctz/src/time_zone_posix.o] Error 127 (ignored)
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
ar: ./cctz/src/time_zone_fixed.o: No such file or directory
Makevars:18: recipe for target 'libcctz.a' failed
make: *** [libcctz.a] Error 1
ERROR: compilation failed for package ‘lubridate’
* removing ‘/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/lubridate’
* restoring previous ‘/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/lubridate’
* installing *source* package ‘tidyverse’ ...
** package ‘tidyverse’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  object 'vI' not found
ERROR: lazy loading failed for package ‘tidyverse’
* removing ‘/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/tidyverse’

The downloaded source packages are in
	‘/tmp/RtmpS5pP5J/downloaded_packages’
```

However `/usr/share/R/include` exists, my gcc version is 6.3.0

Any suggestions?

**Comment by vspinu** [comment]
```
I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/lucadelu/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"      -c update.cpp -o update.o
/bin/bash: I/usr/share/R/include: No such file or directory
```

Looks like something is truncating the gcc command but `I/usr/share/R/include` is not a command so bash chokes. It should look like all others

```
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I. -I.
```

This is my output on Ubuntu

```
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
gcc -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c datetime.c -o datetime.o
gcc -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c period.c -o period.o
gcc -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c tparse.c -o tparse.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c update.cpp -o update.o
gcc -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c utils.c -o utils.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
g++ -std=gnu++11 -I"/home/vspinu/bin/R-latest/include" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/vspinu/.lib/R/Rcpp/include" -I/usr/local/include  -std=c++11 -fpic  -g -O2 -UNDEBUG -Wall -pedantic -g -Og -fdiagnostics-color=always -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
g++ -std=gnu++11 -shared -L/usr/local/lib -o lubridate.so RcppExports.o datetime.o period.o tparse.o update.o utils.o -L. -lcctz
installing to /tmp/RtmpsTtZkr/devtools_install_43b13fd595b7/lubridate/libs
* DONE (lubridate)
```

**Comment by davidlamcm** [comment]
similar issue here:
`
The downloaded source packages are in
	‘/tmp/RtmplMw0wV/downloaded_packages’
> install.packages("lubridate")
Installing package into ‘/home/david/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/lubridate_1.7.4.tar.gz'
Content type 'application/x-gzip' length 449850 bytes (439 KB)
==================================================
downloaded 439 KB

* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ successfully unpacked and MD5 sums checked
** libs
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
gcc  -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-rAT5Oi/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c datetime.c -o datetime.o
gcc  -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-rAT5Oi/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c period.c -o period.o
gcc  -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-rAT5Oi/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c tparse.c -o tparse.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c update.cpp -o update.o
gcc  -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-rAT5Oi/r-base-3.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utils.c -o utils.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
g++ -std=c++11   -I/usr/share/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/  -I"/home/david/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"      -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o 
-L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o lubridate.so RcppExports.o datetime.o period.o tparse.o update.o utils.o -L. -lcctz -L/usr/lib/R/lib -lR
/bin/bash: line 2: -L/usr/lib/R/lib: No such file or directory
/usr/share/R/share/make/shlib.mk:6: recipe for target 'lubridate.so' failed
make: *** [lubridate.so] Error 127
ERROR: compilation failed for package ‘lubridate’
* removing ‘/home/david/R/x86_64-pc-linux-gnu-library/3.4/lubridate’
Warning in install.packages :
  installation of package ‘lubridate’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmplMw0wV/downloaded_packages’`

**Comment by vspinu** [comment]
Ok. I have a hunch. I think different sh/bash versions treat comments and continuation lines differently. Could you please try github?

**Comment by davidlamcm** [comment]
My issue is now solved. I cannot pinpoint which step solve my issue exactly but below is what I have done:
It seems my error was coming somewhere from my version of r-base-core or Rcpp. As the command that generated error didn't seem originated from lubridate package. After reinstalling my r-base-core with the latest binary from CRAN and install.package("Rcpp") , I am able to install lubridate with install.pacage("lubridate") now. 

Replying to Vspinu: Thanks for the suggestion. I am not sure how to change the BASH to SH or another version of shell. As changing the ubuntu system default BASH doesn't seems to change the BASH that was used by R.

**Comment by vspinu** [comment]
Thanks for the update. I have changed the bash commands in Makvars on lubridate side. I was suggesting to try lubridate from github.
