### ISSUE TITLE
lubridate is giving error when the leading zero is missing for either day or month in ymd format.

### ISSUE THREAD

**Issue by CodingTigerTang** [tidyverse/lubridate#669]
Recently I have found that **lubridate** will give NA when the leading zero is missing for either day or month in ymd format.

For example, when you run
```R
datetest <- c("201711","2017092","2017110")
lubridate::ymd(datetest)     
[1] NA NA NA
Warning message:
All formats failed to parse. No formats found. 
```
_This will return NAs._  

For as.Date(), it is evaluating from left to right and assuming double digit for month and day. Therefore, if the day is missing a leading zero, it will still return.

Below is what I have for current situation.
```R
ymd_add_o1 <- function(date) {
  # filter out the date that has one digit in mm, as if it is two digit, as.Date() will be able to parse it
  na_date <- date[is.na(as.Date(date,format="%Y%m%d"))]
  # get the first 4 digit
  na_date_yyyy <- substr(na_date,1,4)
  # get the digit for mmdd
  na_date_mmdd <- substr(na_date,5,nchar(na_date))
  # adding 0 to date object to ensure the order of output
  date[is.na(as.Date(date,format="%Y%m%d"))] <- paste0(na_date_yyyy,"0",na_date_mmdd)
  # use as.Date() to parse the date with leading zero added
  as.Date(date,format="%Y%m%d")
}


ymd_add_o1(datetest)
[1] "2017-01-01" "2017-09-02" "2017-11-01"
```
It would be great if ymd() can have an option to add the leading zero and parse the date.

**Comment by cderv** [comment]
in lubridate, you have a `truncated ` argument to deal with missing element in strings comparing to format. In your case if you use that, first date is parsed. 
Then, know that lubridate use a guessing mechanism. When it is not working as desired, you could try parsing date with a specific format (when you know it). It is the second example with `parse_date_time` and `exact = TRUE`. This way the second date is parsed correctly. 
For the last one, it is difficult to know if it is 2017-01-10 or 2017-10-01, 2017-10-02, 2017-10-03, ...


``` r
datetest <- c("201711","2017092","2017110")
# guessing format 
lubridate::ymd(datetest, truncated = 1)  
#> Warning: 2 failed to parse.
#> [1] "2017-11-01" NA           NA
# no guessing - format is passed in argument
lubridate::parse_date_time(datetest, orders = "%Y%m%d", exact = TRUE, truncated = 1)  
#> Warning: 1 failed to parse.
#> [1] "2017-11-01 UTC" "2017-09-02 UTC" NA
```

Created on 2018-04-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


In your case, you know that you have missing leading 0, so it helps you guess. However, I think it is difficult for Lubridate to deal with all the sort of specificities. As `as.Date` has a way of dealing with that, the parsing code of lubridate could maybe be adjusted but I can't say. I just wanted to highlight current solution to deal with incomplete date.

Personnaly, I think the data with this kind of string date should be pre-processed as string before converted to date objects.

**Comment by vspinu** [comment]
Making this to work would require quite some algorithmic tweakery at the very low level of parsing. Parser will be extracted out of lubridate and I will take care of it then.

**Comment by hadley** [comment]
I think it's too much to expect lubridate to figure out how to automatically parse `c("201711","2017092","2017110")`. All of those dates are fundamentally ambiguous, and I think you should be using your own algorithm to parse.
