### ISSUE TITLE
Conflict between `lubridate::hms` and `hms::hms`

### ISSUE THREAD

**Issue by NikNakk** [tidyverse/lubridate#673]
Depending on the order of package loading, `hms` may refer to either `lubridate::hms` or `hms::hms`, which have incompatible syntax and functionality. Since both are part of `tidyverse`, is this by design? I wasn't sure which package to post the issue in, so I've cross-posted at present (https://github.com/tidyverse/hms/issues/55). It's certainly a cause for confusion.

```
library(lubridate)
#Attaching package: ‘lubridate’
#The following object is masked from ‘package:base’:
#
#    date
library(hms)
#Attaching package: ‘hms’
#
#The following object is masked from ‘package:lubridate’:
#
#    hms
hms("11:23:00")
#Error: All arguments must be numeric or NA
```

```
library(hms)
library(lubridate)
#Attaching package: ‘lubridate’
#
#The following object is masked from ‘package:hms’:

#    hms

#The following object is masked from ‘package:base’:

#    date
hms("11:23:00")
#An object of class "Period"
#[1] 0
#Slot "year":
#[1] 0
#
#Slot "month":
#[1] 0
#
#Slot "day":
#[1] 0
#
#Slot "hour":
#[1] 11
#
#Slot "minute":
#[1] 23
```

**Comment by vspinu** [comment]
Naming conflicts are common in R's world. In case lubridate is loaded first, you either have to make an alias like `lhms <- lubridate::hms` or use explicit `lubridate::hms` in your code. Nothing to be done about this at the moment. `hms` in lubridate is a parser producing periods, in `hms` it's a constructor producing durations.

**Comment by tbuckl** [comment]
sorry for the naive question, but it seems like i can't load both lubridate::hms and hms::hms without failing checks. is this by design?

i get the following serious warning:

```
Warning: replacing previous import ‘hms::hms’ by ‘lubridate::hms’ when loading ‘tidytransit’
```
