### ISSUE TITLE
fiscal_start argument on the year() command

### ISSUE THREAD

**Issue by statsandthings** [tidyverse/lubridate#680]
A current feature of lubridate allows you to get fiscal information from a date.

```
library(lubridate)
x <- ymd(c("2012-03-26", "2012-05-04", "2012-09-23", "2012-12-31"))
quarter(x, with_year = TRUE, fiscal_start = 11)
semester(x, with_year = TRUE, fiscal_start = 11)
```
I'd like to see this `fiscal_start` argument offered across the board for lubridate, in particular for the year command.

`year(x, with_year = TRUE, fiscal_start = 11)`

would yield the fiscal year for any given date (currently does not, throws an error).

**Comment by awfrankwils** [comment]
**I might also point out that there currently appears to be a bug in the way the `quarter()` function appends a year with_year.**
`x <- ymd(c("2012-03-26", "2012-05-04", "2012-09-23", "2012-12-31"))`
`quarter(x, with_year = TRUE, fiscal_start = 11)`
`[1] 2012.2 2012.3 2012.4 2013.1`
This works fine with the december 2012 date reported as fiscal year 2013 Q1; however if I move the fiscal start to April, we don't see similar treatment for fiscal year of the first date -- which should be **2011 Q4** based on this formatting.
`quarter(x, with_year = TRUE, fiscal_start = 4)`
`[1] `**2012.4**` 2012.1 2012.2 2012.3`

**Comment by cderv** [comment]
Just to help cross linked as @awfrankwils opened an issue on quarter in #682

**Comment by hadley** [comment]
I think this is really outside of the scope of lubridate and you'd be better of using a package that provides specialised tools for fiscal date/times.
