### ISSUE TITLE
Add CODEOWNERS

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/lubridate#686]
Hi @vspinu,

A heads up: at this past RStudio work week, we decided to try to formally implement "understudies" for all the packages (i.e. having a second person to help increase our code reviews, etc.). I'll submit a PR with a `CODEOWNERS` file. The link in it currently goes to nothing, but will ultimately go to a description of this process for the tidyverse.org page development practices).

Thanks,
Mara

**Comment by vspinu** [comment]
Thanks for the heads up. Does this mean that the contribution/authoring process will automatically slow down because of a necessary(?) second-person review?
