### ISSUE TITLE
Feature Request: Extend Partial Date Support

### ISSUE THREAD

**Issue by billdenney** [tidyverse/lubridate#690]
I need to load medical data which often has incomplete dates (as implemented in #4) for instance for questions like "When were you diagnosed with the condition?" and answers of "Some time in 2000."  I tend to load data as:

```r
ymd_hms("2000", truncated=5)
```
But this implicitly adds a lot of information that I don't actually have: the month, day, hour, minute, and second.  My preferred output structure would have explicit `NA` values where the information is unknown.  This won't work with either POSIXct or the print method for POSIXlt, but something like the following is what I'd like:

``` r
library(lubridate)                 
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
foo <- ymd_hms("2000", truncated=5)
foo2 <- as.POSIXlt(foo)            
foo2$mon <-                        
foo2$mday <-                       
foo2$hour <-                       
foo2$min <-                        
foo2$sec <-                        
foo2$wday <-                       
foo2$yday <-                       
foo2$isdst <- NA_integer_          
foo2                               
#> [1] NA
dput(foo2)                         
#> structure(list(sec = NA_integer_, min = NA_integer_, hour = NA_integer_, 
#>     mday = NA_integer_, mon = NA_integer_, year = 100L, wday = NA_integer_, 
#>     yday = NA_integer_, isdst = NA_integer_), .Names = c("sec", 
#> "min", "hour", "mday", "mon", "year", "wday", "yday", "isdst"
#> ), class = c("POSIXlt", "POSIXt"), tzone = "UTC")
```

I know that this would not be good default behavior, but I'm curious if you see a use for it in general?

**Comment by vspinu** [comment]
POSIXlt is not a good data structure to work with. So, no, never as POSIXlt.

As to the general idea of oteher partials than Date (the only partial in R so far) it's unlikely to happen soon. It's just too much work for little added value. Your use case is a valid one, but I guess you could do just fine with having 3 (6) columns in a data frame: year, month, and date, right?

**Comment by billdenney** [comment]
That makes sense.  I was specifically wanting to use lubridate because of the ability to easily work with the structures.  May it be reasonable to add an attribute of “precision” to POSIXct that would indicate the parsed precision like “y”, “ym”, “ymd”, “ymdh”, “ymdhm”, or “ymdhms” (with an optional “z” at the end of any of those to indicate timezone)?

**Comment by vspinu** [comment]
POSIXct is core R function. We cannot change that. With lubridate you can use custom formats. For example

```R
parse_date_time("2000Z-08:00", "Yz")
## "2000-06-30 08:00:00 UTC"
``` 

Is this what you mean? 

Unfortunately it will fill in missing components with current day. This is inherited from strptime and will be changed some day after the lubridate rewrite.

**Comment by billdenney** [comment]
My general interest is a partial date/time and date format.  What would you think about a new partial date and partial time class?  (I’m not familiar with the rewrite; might this be reasonable after that?)

**Comment by vspinu** [comment]
I think it's too much work, but I will evaluate that possibility in due time.

**Comment by billdenney** [comment]
As I’m thinking about it more, I agree that the core functionality of partial dates seems out of the scope of lubridate.  There are lots of operations that would need to be handled in different ways (min and max come to mind where `min(as_partial_date(“2015”))` would be 2015-01-01 and max would be 2015-12-31.

If I were to make a separate package that handled the complexity of partial dates, do you think you would accept a pull request for lubridate to support it?  I would think that it would have many small modifications to lubridate within most or all of the parsing functions (and probably other functions that I’m not thinking of with first considerations).

**Comment by vspinu** [comment]
> If I were to make a separate package that handled the complexity of partial dates, do you think you would accept a pull request for lubridate to support it? I would think that it would have many small modifications to lubridate within most or all of the parsing functions

Parsing will be a separate package and supporting partials wouldn't be a problem. If you manage to pull something feature complete and which would operate smoothly with Date and POSIX then for sure, why not. 

The main issue is not in having a bunch of partial classes with some basic operations on them. It's how those classes interact between them is a real issue. Defining arithmetics and rounding on those is a non-trivial task. Please have a look at CCTZ documentation before you attempt this; it should give ideas of how to manage partials. Also have a look at my new package for various time manipulation utilities [timechange](https://github.com/vspinu/timechange), particularly for rounding semantics.

**Comment by dgkf** [comment]
Hi @billdenney, 

I'm also in the medical field and have found it really burdensome to work with incomplete datetimes. I see I'm late to this party, but I wanted to mention that I've been toying around with implementing something like this at my place of work. It's a rough prototype that I felt reluctant to release more generally in its current state, but seeing as there's possibly a wider need for it, I decided to open it up so we can at least try to centralize efforts.

Expect bugs and half baked features. At this point even the internal representation has been fluctuating as I've been hitting walls with different attempts. I'm also quite daunted by the breadth of bizarre time considerations that need to be taken into account (thanks for the **timechange** package, that seems like a very useful dependency!)

Please take a look! 
[parttime](https://github.com/dgkf/parttime)

**Comment by hadley** [comment]
Partial dates are out of scope for lubridate so I'm going to close this issue.
