### ISSUE TITLE
Conflict between dplyr and lubridate for `union`, `setdiff`, `intersect`

### ISSUE THREAD

**Issue by NikNakk** [tidyverse/lubridate#693]
dplyr and lubridate both redefine the base functions, `union`, `setdiff`, `intersect`. dplyr makes these S3 generics with a special case for `data.frame`. `lubridate` makes them S4 generics with a special case for `Interval`. Depending on the order of package loading, only one of these possibilities will be available. Would it be possible to co-ordinate the approach used, since the packages are often used together?

One thing to note is that executing:

```
library(dplyr)
loadNamespace(lubridate)
```

allows both `union(my_interval, my_interval)` and `union(my_data_frame, my_data_frame)` to work as expected, but if `library(lubridate)` is called, the S3 methods defined in `dplyr` are lost.

Tested using R 3.5.0, lubridate 1.7.4 and dplyr 0.7.6 on Windows 7 and RStudio 1.1.1453.

**Comment by vspinu** [comment]
I don't think moving from S3 to S4 or the other way around is an option for either package. But I wonder if that would help. If two packages define their S3 (or S4) generics for same function won't they overwrite each other anyhow?

I don't see a clean solution for this. Maybe @hadley could suggest something.

In any event namespaced call `lubridate::union` should work as expected.

**Comment by NikNakk** [comment]
I may have missed something, but it strikes me that the most straightforward solution would be to change lubridate to use S3 methods for `Interval`. It would mean that the method would need to check the class of the second parameter, since method dispatch is only based on the first, but otherwise I can't see any big issues. I'd be interested to see what @hadley has to say, since he clearly understands S3/S4 far better than I ever will!

**Comment by vspinu** [comment]
Indeed, that could be in this particular case because we don't have methods where first argument is non-interval. But then still, will there be any inter-operational issues given those two S3 generics? 

This issue will require a bit of digging and, unfortunately, I won't have time to  investigate this in the near future. 

For the record, there are also `setdiff` and `intersect` which we `setGeneric`, which should be changed as well.

**Comment by vspinu** [comment]
Or one can check for existence of the generic and define new one if none has been defined.

**Comment by jimhester** [comment]
Bioconductor defines a intersect generic in BiocGenerics https://github.com/Bioconductor/BiocGenerics/blob/c7ed1f9e8350a65e6d495e53a7d529a14716a46c/R/sets.R#L19-L23.

I think the most proper way to do this would be to have an equivalent generics package on CRAN that defines the generics, which dplyr and lubridate could both import. However if that is too heavyweight we could probably define the generics on demand at runtime.

**Comment by AshesITR** [comment]
Is there any update on this issue? It's the only thing left that's blocking [lubridate from becoming a tidyverse core package](https://github.com/tidyverse/tidyverse/issues/157)
`generics` is on CRAN and exports the discussed generics.

**Comment by hadley** [comment]
Fixed in #717
