### ISSUE TITLE
How should I contribute to documentation?

### ISSUE THREAD

**Issue by rensa** [tidyverse/lubridate#694]
I saw a few typos in the documentation, as found at https://lubridate.tidyverse.org/reference. If I want to submit a PR to fix them, should I manually edit `docs/reference/` in this repo? Or are these HTML files generated through a build process like Roxygen? The typos I found aren't present in the code comments in the `R/` source files (eg. 'tockens' instead of 'tokens' in `parse_date_time`).

**Comment by vspinu** [comment]
This was fixed some time ago, but the html docs havent been updated. It's `pkgdown` site. Thanks for bringing this to our attention.
