### ISSUE TITLE
Compare method needed between Duration and numerics for plotting in ggplot2 

### ISSUE THREAD

**Issue by dpseidel** [tidyverse/lubridate#695]
Plotting Duration objects in `ggplot2` fails because there is no defined `Compare` method between numeric and Duration objects which is required by the underlying continuous scale calculations (reprex and discussion @ tidyverse/ggplot2#2414). 

Is there a good reason why this method hasn't been implemented? I'm happy to submit a PR adding it if deemed appropriate.

**Comment by vspinu** [comment]
No good reason. difftime works with numeric so should durations. Would appreciate a PR for this (with a news entry). Thanks!

**Comment by mrucker** [comment]
FYI, for anybody who runs into this bug as of April 2020 this fix still hasn't been released even though the issue is closed. Hopefully this will save others from spending a lot of time scratching their heads.
