### ISSUE TITLE
Lubridate failed to compile with Intel compiler: issue with std::vector::shrink_to_fit

### ISSUE THREAD

**Issue by wirawan0** [tidyverse/lubridate#697]
On my site, I have R 3.4 which is compiled with Intel compiler (I am using Intel compiler version "18.0.3 20180410"). I tried to install package "lubridate" and ran into the following problem (I include the last Intel C++ invocation):

    icpc -std=gnu++11 -I/cm/shared/applications/R/3.4.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/home/wpurwant/local/R-3.4.0/lib/R/site-libraries/Rcpp/include" -I/usr/local/include   -fpic  -O3 -ipo -qopenmp -xHost -fpic -fPIC -I/cm/shared/applications/zlib/1.2.8/include -I/cm/shared/applications/bzip2/1.0.6/include -I/cm/shared/applications/xz/5.2.3/include -I/cm/shared/applications/build_essential/1.0/include -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
    cctz/src/time_zone_info.cc(245): error: class "std::vector<cctz::Transition, std::allocator<cctz::Transition>>" has no member "shrink_to_fit"
	transitions_.shrink_to_fit();
		     ^

    cctz/src/time_zone_info.cc(592): error: class "std::vector<cctz::Transition, std::allocator<cctz::Transition>>" has no member "shrink_to_fit"
	transitions_.shrink_to_fit();
		     ^

    cctz/src/time_zone_info.cc(648): error: no suitable constructor exists to convert from "std::nullptr_t" to "std::unique_ptr<cctz::ZoneInfoSource, std::default_delete<cctz::ZoneInfoSource>>"  
	if (fp == nullptr) return nullptr;
				  ^

    compilation aborted for cctz/src/time_zone_info.cc (code 2)
    make: *** [cctz/src/time_zone_info.o] Error 2

This appears to be some language compliance issue? My understanding is that shrink_to_fit method exists in C++11. Any thoughts what's wrong and how to solve this?

Thanks.

**Comment by vspinu** [comment]
This is strange.  icpc is fully c++11 compliant since quite a while. Do you have multiple versions of icpc and R uses an old one by accident? No other ideas, sorry. I would have tried it myself if there were a straightforward way to install intel compiler on Ubuntu but there seem not to be one.

**Comment by wirawan0** [comment]
Vitalie... I found the reason. I was on a computer where the system G++ version is way too old (g++ 4.4.7). Here are some supporting docs:

https://software.intel.com/en-us/forums/intel-c-compiler/topic/517887  (see Tim P. posting dated 07/09/2014).

https://software.intel.com/en-us/node/522750
This page says specifically: "The Intel compiler driver uses the default version of gcc/g++, or the version you specify, to extract the location of the headers and libraries."

I don't know the oldest version supported by Intel compiler for successful C++11 compilation, but I can confirm that switching the GCC version to 6.4.0 does the compilation just fine.  From https://gcc.gnu.org/projects/cxx-status.html , it looks like one needs to use at least gcc 4.8.1 to be ensured of successful build.

**Comment by vspinu** [comment]
>  I found the reason. 

Great! Indeed, with hindsight all compilers use standard library, so that's should have been checked first. 

>  it looks like one needs to use at least gcc 4.8.1 to be ensured of successful build.

Indeed. This is also stated in the lubridates "System Requirements" field.
