### ISSUE TITLE
Special-case lubridate::date() if x is missing

### ISSUE THREAD

**Issue by hadley** [tidyverse/lubridate#699]
i.e.

```R
date <- function (x) {
  if (missing(x)) {
    return(base::date())
  }

  UseMethod("date")
}
```

This ensures that `lubridate::date()` follows the superset principle, only adding functionality when overriding a base function.

**Comment by vspinu** [comment]
It's there in the [default method](https://github.com/hadley/lubridate/blob/master/R/accessors-date.R#L29).

```R
> library(lubridate)
> date()
[1] "Wed Jul 25 12:40:02 2018"
> 
```

**Comment by hadley** [comment]
Oh nice! In that case, can I request that behaviour be documented?

(Also I'm surprised that a missing argument calls the default method; good to know)

**Comment by hadley** [comment]
I meant just a single line like "lubridate::date() obeys the superset principle so for compatibility with base R..."
