### ISSUE TITLE
(Minor thing) Consistancy Input Naming with_tz and force_tz 

### ISSUE THREAD

**Issue by bjoerm** [tidyverse/lubridate#701]
Hey guys,
just a minor thing I noted: Most lubridate functions (e.g. ymd) call any input about a set timezone "tz". However, _with_tz_ and _force_tz_ call this input "tzone" instead of "tz". There might be other cases but these two are the ones I noted.

Thanks a lot for your work and this great package. :-)

**Comment by vspinu** [comment]
It's a known inconsistency and it's too late to change. Will be fixed during the package rewrite some day.
