### ISSUE TITLE
period() not accepting vector input

### ISSUE THREAD

**Issue by rrohwer** [tidyverse/lubridate#702]
Example:
```
months(c(0,3)) # this works
# [1] "0S"             "3m 0d 0H 0M 0S"

period(num = 0, units = "month") # this works
# [1] "0S"

period(num = 3, units = "month") # this works
# [1] "3m 0d 0H 0M 0S"

period(num = c(0,3), units = "month") # oops, documentation clearly says it doesn't accept that
# Error in .period_from_num(num, units) : 
#   Arguments `num` and `units` must have same length

period(num = c(0,3), units = c("month","month")) # this is the bug
# Error: Invalid unit name: month

period(num = c(1,3), units = c("month","month")) # and it's not because of weird zero behavior
# Error: Invalid unit name: month
```

According to the documentation `period()` should accept "a numeric or character vector," and the shortcut call `months()` does, so I think this is a bug. Thanks for all you do supporting this awesome package!

**Comment by cderv** [comment]
This works when you do not try to provide same units twice:
``` r
lubridate::period(num = c(1,3), units = c("month","hour")) 
#> [1] "1m 0d 3H 0M 0S"
lubridate::period(num = c(0,3), units = c("month","hour")) 
#> [1] "3H 0M 0S"
```

Created on 2018-08-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I am not sure what you try is correct use of `period`. The vectorization in `num` and `units` helps create complex period like this `period(c(3, 1, 2, 13, 1), c("second", "minute", "hour", "day", "week"))` but you can't repeat a unit twice as it make no sense in this case. 

to create a vector of period you can use the `...` and named period argument.
``` r
lubridate::period(months = c(0,3)) 
#> [1] "0S"             "3m 0d 0H 0M 0S"
lubridate::period(months = c(1,3)) 
#> [1] "1m 0d 0H 0M 0S" "3m 0d 0H 0M 0S"
```
or the character vector format for `num` argument:
``` r
lubridate::period(c("0 month", "3 months")) 
#> [1] "0S"             "3m 0d 0H 0M 0S"
lubridate::period(c("1 month", "3 months")) 
#> [1] "1m 0d 0H 0M 0S" "3m 0d 0H 0M 0S"
```

However, it seems to me taht the error message is not very clear and I think there should be a check to stop before error if there is twice the same units in `units=`. Also, the documentation could also be more precise.

**Comment by rrohwer** [comment]
Thanks! Your explanation of the multi-unit vector arguments`period()` is designed to accept makes sense. 

In addition to the documentation you suggest, my confusion also came from the lubridate "cheat sheet" which describes `period()` as "An automation friendly period constructor." That's part of why I expected the same behavior as with `months()` when I tried to substitute `period(,unit = "month")` in a function I made that can accept days, months, or years (automation attempt).

**Comment by cderv** [comment]
I'll see how it could be improve in the cheatsheet. I am not sure where it lives.

> That's part of why I expected the same behavior as with months()

I would say you have the same behaviour using the correct syntax. Either build a string of period you want or use the named argument syntax. For the fist choice, something like that could work for you as a wrapper
``` r
automated_period <- function(num, units) {
  list_period  <- paste(num, units)
  lubridate::period(list_period)
}
automated_period(c(1, 2), c("month", "days"))  
#> [1] "1m 0d 0H 0M 0S" "2d 0H 0M 0S"
```

Created on 2018-08-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by vspinu** [comment]
@rrohwer the interface you are using is the least convenient of all but was historically the first one in lubridate. Vectorization is usually achieved either through explicit components in `...` or through a string input:

```R
> period(months = c(0, 10, 12))
[1] "0S"              "10m 0d 0H 0M 0S" "12m 0d 0H 0M 0S"
> period(c("0m", "10m", "12m"))
[1] "0S"              "10m 0d 0H 0M 0S" "12m 0d 0H 0M 0S"
```

I think the documentation of period constructor and examples are pretty clear. But I agree that this interface is not idiomatic nor vectorization friendly and maybe should be removed on potential lubridate rewrite.
