### ISSUE TITLE
leap_year() not working for a new class "yearmonth"

### ISSUE THREAD

**Issue by earowang** [tidyverse/lubridate#703]
There's a new class "yearmonth" from the **tsibble** package. Its underlying class is Date. `year()` works for it but `leap_year()` doesn't. This is due to  [`recognize()`]( https://github.com/tidyverse/lubridate/blob/547f87d15da96ddddbf07fbbb2f597691d85525b/R/util.r#L18) is too strict using `all()`. Can we use `any()` instead? I'm happy to give a pull request too. Thanks.

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
x <- tsibble::yearmonth(Sys.Date())
x
#> [1] "2018 Aug"
class(x)
#> [1] "yearmonth" "Date"
leap_year(x)
#> Error in leap_year(x): unrecognized date format
year(x)
#> [1] 2018
```

Created on 2018-08-07 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Are you still interested in doing a PR? I think the right approach would be to eliminate `recognize()`  and instead make `leap_year()` a generic.

**Comment by earowang** [comment]
Yep, happy to do a PR.

A better approach would be to simplify the code and just rely on the `year()` (already S3 generic) internally?

https://github.com/tidyverse/lubridate/blob/6b028a8d28d428ad3f25bcf81974ed9915a4ac15/R/leap-years.r#L21

**Comment by hadley** [comment]
Oh yeah, totally 😅

**Comment by vspinu** [comment]
Thanks @earowang!
