### ISSUE TITLE
Add a function for calculating an accounting calendar (4-4-5 and others)

### ISSUE THREAD

**Issue by Mako21** [tidyverse/lubridate#704]
I've recently been working with a lot of data that follows a 4-4-5 accounting calendar, and I realized it would be helpful to have a function that calculates those month breaks. It seemed simple enough to implement and I thought I'd propose it as an addition.

The goal here is to calculate the date breaks for a calendar that follows a certain week pattern, that deviates from the actual calendar. In accounting 4-4-5 (4 weeks, 4 weeks, 5 weeks) is a common pattern, and other retail calendars follow similar patterns. 

`x` - a date from the first month of the desired calendar
`weekStart` - set the day of the week each break is calculated from
`pattern` - pattern of weeks, i.e. 4-5-4, 4-4-5, 4-5, etc.
`month1_weeks` - if the first month has a different number of weeks than the pattern
`firstWeek` - specify an offset if the year does not start in the first week of the month

```
accountingCalendar <- function(x, weekStart = 7, pattern = c(4,4,5), month1_weeks = NULL, firstWeek = 1){
	# get the first of the month, offset by firstWeek
	start_month <- 	floor_date(x, 'month') + weeks(firstWeek-1)

	# create a vector of weeks in each month, limit length to twelve
	# but allow for a pattern of varying length
	week_breaks <- c(0, month1_weeks, rep(pattern,12))[1:12]

	# adjust date to the start of the week based on week_start
	cal_breaks <- floor_date(start_month, 'week', 
		week_start = getOption('lubridate.week.start', weekStart))+
	# then generate the date vector by addting the cumulative vector of weeks
		weeks(cumsum(week_breaks))
	return(cal_breaks)
}
```

This is the first time I've suggested something for a R library, so I'd certainly appreciate any feedback on how to improve this as well, and how relevant it is.

**Comment by vspinu** [comment]
Thanks for the suggestions but I don't quite understand the aim of the function. What is `x`? Is it a singleton or a vector?  What do you want to do with such a function in the first place?

**Comment by Mako21** [comment]
`x` would be a single value:

```
accountingCalendar(as.Date("2018/01/01"))
 [1] "2017-12-31" "2018-01-28" "2018-02-25" "2018-04-01" "2018-04-29"
 [6] "2018-05-27" "2018-07-01" "2018-07-29" "2018-08-26" "2018-09-30"
[11] "2018-10-28" "2018-11-25" "2018-12-30"
```

And this is needed for working with a non-standard calendar, where, as an example, the first week of February is considered part of January for accounting/reporting purposes, and you need to be able to appropriately place a date of say 2018/02/02 as part of January.

This would be true in the case of `accountingCalendar(as.Date("2018/01/01"), month1_weeks = 5)`

**Comment by stegerj** [comment]
I think yes, the function should work the same way as isoweek() or epiweek() does.
> epiweek(as.Date("2018-04-29"))
[1] 18
_> epimonth(as.Date("2018-04-29"))
[1] 5_

to compare with standard calendar output:
> week(as.Date("2018-04-29"))
[1] 17
> month(as.Date("2018-04-29"))
[1] 4

**Comment by hadley** [comment]
Specialised calendars are out of scope for lubridate. You might want to try https://davisvaughan.github.io/almanac/ or similar packages.
