### ISSUE TITLE
as.duration.Period and dyears are inconsistent

### ISSUE THREAD

**Issue by hadley** [tidyverse/lubridate#708]
Wouldn't you expect these two results to be the same?

``` r
library(lubridate)

as.duration(years(1))
#> [1] "31557600s (~1 years)"
dyears(1)
#> [1] "31536000s (~52.14 weeks)"
```

**Comment by vspinu** [comment]
Indeed. It think different approximation logic crept in over the years.

**Comment by hadley** [comment]
Changing this is simple:

```
# old
dyears <- function(x = 1) new("Duration", x * 60 * 60 * 24 * 365)
# new
dyears <- function(x = 1) new("Duration", x * 60 * 60 * 24 * 365.25)
```

But it breaks a lot of unit tests, and is likely to affect existing code in ways that are difficult to track down. For that reason, I think removing this inconsistency is likely to cause more trouble than its worth.
