### ISSUE TITLE
lubridate issue in getting last 6 month from this specific day

### ISSUE THREAD

**Issue by paliwal90** [tidyverse/lubridate#711]
> as.Date("2018-08-28") - lubridate::period(6, units = "months")
[1] "2018-02-28"
> as.Date("2018-08-29") - lubridate::period(6, units = "months")
[1] NA

> as.Date("2018-08-29") %m-% months(6) 

works though

**Comment by cderv** [comment]
In the vignette of the 📦 
>  if adding or subtracting a month or a year creates an invalid date, lubridate will return an NA.

You need to use the special `%m-%` (or %m+%) operator to do this kind of arithmetic with date. 
``` r
library(lubridate)
# result is a valid date so no problem
as.Date("2018-08-28") - period(6, units = "months")
#> [1] "2018-02-28"
# result is not a valid date so NA
as.Date("2018-08-29") - period(6, units = "months")
#> [1] NA
# use the operator to prevent that
as.Date("2018-08-29") %m-% period(6, units = "months")
#> [1] "2018-02-28"
```

Please, see the documention this special point for explanation
https://lubridate.tidyverse.org/articles/lubridate.html#if-anyone-drove-a-time-machine-they-would-crash

**Comment by paliwal90** [comment]
Thanks ! You might even extend functionality of package to find valid dates only. 29 february is not valid, but then 28 february is expected (if - months used). Or 1 March expected (if + months used).
