### ISSUE TITLE
Midnight timestamp not returning expected result

### ISSUE THREAD

**Issue by JegorG** [tidyverse/lubridate#712]
library(lubridate)

dmy_hm("Tuesday, 16 Mar 1999, 00:01")
# "1999-03-16 00:01:00 UTC"
dmy_hm("1999-03-16 00:00:00 UTC")
# "1999-03-16 UTC"

I expect

"1999-03-16 00:00:00 UTC"

**Comment by vspinu** [comment]
You are confused about printed representation and actual object. These are the same. Whenever in doubt use `str`.

**Comment by challisd** [comment]
You can get what you want with `format(consolDate, "%Y-%m-%d %H:%M:%S %Z")`

**Comment by challisd** [comment]
Also I agree with the original poster that this is a bug. I understand the underlying representation is currently the same, but if a user has a string with hours and minutes, parses it with a function called dmy_hm and then converts back to a string it is perfectly reasonable to expect you'll get back a string with hours and minutes. Technical justification aside, this is a bug in that it does not behave the way virtually all users will expect it to.

**Comment by vspinu** [comment]
> you'll get back a string with hours and minutes.

It's not a string that is returned but a `POSIXct` object. The issue here is that R prints the midnight `POSIXct` objects without the trailing `00:00:00` for the space efficiency reasons. It's not such a big deal to get used to this, or if you are really troubled by it, you could write your own `print.POSIXct` method and place it in .Rprofile. In any case it's not lubridate's issue, it's how R prints things.

**Comment by JBrocklyAnderson** [comment]
So does this mean that the 00:00:00 time value still exists in the cell?

**Comment by srlamunion** [comment]
> So does this mean that the 00:00:00 time value still exists in the cell?

That is my question also. It doesn't appear to be when written to .csv for example. The cell shows just the date and not the trailing 00:00:00 to go with it.

**Comment by hrdawson** [comment]
> > So does this mean that the 00:00:00 time value still exists in the cell?
> 
> That is my question also. It doesn't appear to be when written to .csv for example. The cell shows just the date and not the trailing 00:00:00 to go with it.

I've landed in this issue for this exact reason. For anyone else struggling to export to CSV with trailing 00:00:00, I fixed this problem by exporting with `data.table::fwrite` instead of `utils::write.csv`.
