### ISSUE TITLE
as_datetime returns POSIXlt

### ISSUE THREAD

**Issue by adfi** [tidyverse/lubridate#713]
I ran into a problem when using `as_datetime` in combination with `dplyr::mutate`. The latter doesn't accept `POSIXlt` which was being returned by `as_datetime`. However looking into the documentation there is no mention of `POSIXlt`. The documentation states: "These are drop in replacements for as.Date() and as.POSIXct()". 

So is the documentation incomplete or should the function be changed?

Example:
`library(lubridate)`
`class(as_datetime("2018-09-05 09:41:31", format="%Y-%m-%d %H:%M:%S"))`
`[1] "POSIXlt" "POSIXt"`

**Comment by vspinu** [comment]
There might have been a reason for that. If not, the output type should be changed indeed.  Will have a look.

**Comment by hadley** [comment]
Minimal reprex illustrating inconsistency:

``` r
library(lubridate, warn.conflicts = FALSE)
class(as_datetime("2018-09-05 09:41:31"))
#> [1] "POSIXct" "POSIXt"
class(as_datetime("2018-09-05 09:41:31", format="%Y-%m-%d %H:%M:%S"))
#> [1] "POSIXlt" "POSIXt"
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
