### ISSUE TITLE
as.period is not defined for class 'data.frame'

### ISSUE THREAD

**Issue by dillalan** [tidyverse/lubridate#715]
Hey guys, I'm new in R, so please, I'm sorry if this is too silly, but I have been strugling to create a scatter plot from my data frame. So I'm using lubridate to measure time between the beggining to sentence of a lawsuit, in regular courts to specialized courts. I think I coded right until then, but now I want to put this in a scatter plot, but I keep failing.

Here's the code:
`
as.Date(Tabela_Tempo_Julgamento$DataDistACR)
as.Date(Tabela_Tempo_Julgamento$DataJulgACR)  
as.Date(Tabela_Tempo_Julgamento$DataDistDenuncia)  
as.Date(Tabela_Tempo_Julgamento$DataJulgDenuncia)

#Measuring the interval between the begining of a trial to its end
JULG2 <- interval(Tabela_Tempo_Julgamento$DataDistACR, Tabela_Tempo_Julgamento$DataJulgACR)

JULG1 <- interval(Tabela_Tempo_Julgamento$DataDistDenuncia, Tabela_Tempo_Julgamento$DataJulgDenuncia)

#Geting the mean of JULG1
JULG1 <- as.data.frame(as.period(JULG1), row.names("Cases"), col.names("Tempo"))
summary(JULG1)

JULG2 <- as.data.frame(as.period(JULG2), row.names("Cases"), col.names("Tempo"))
summary(JULG2)

as.Date(BD_especializadas$DataDistDenuncia)
as.Date(BD_especializadas$DataJulgDenuncia)
JULGesp <- interval(BD_especializadas$DataDistDenuncia, BD_especializadas$DataJulgDenuncia)

JULGesp <- as.data.frame(as.period(JULGesp, row.names("Cases"), col.names("Tempo")))
summary(JULGesp)

require(ggplot2) 
ggplot(data = JULG1)+
  geom_point(aes(x = Cases, y = Tempo))` 

Everything works fine if I dont put names in columns ans rows, except that I dont know how to code in this way in the ggplot part of the code.

What am I doing wrong?

Thanks in advance for your patience

**Comment by dillalan** [comment]
Thanks for the reply, I'll try to elaborate. With lubridate package I believe I got to measure the time span that I wanted. Now I want to put every case and it time span in a graph. I learned to do a scatter plot on R following the example in the online book "R for data science", but in that example the data frame have names on its columns and rows. So I tried to put names on my data frame, I altered then the code to "JULG1 <- as.data.frame(as.period(JULG1), **row.names("Cases"), col.names("Tempo")**)". But when I run this line, the console return "as.period is not defined for class 'data.frame'"


I followed your code, the console returned this:

```
structure(list(`as.period(JULG1)` = structure(c(NA, 0, NA, NA, 
NA, NA), year = c(NA, 1L, NA, NA, NA, NA), month = c(NA, 8L, 
NA, NA, NA, NA), day = c(NA, 2, NA, NA, NA, NA), hour = c(NA, 
0L, NA, NA, NA, NA), minute = c(NA, 0L, NA, NA, NA, NA), class = structure("Period", package = "lubridate"))), .Names = "as.period(JULG1)", row.names = c(NA, 
6L), class = "data.frame")
```

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by dillalan** [comment]
Okay, I created a topic [over there](https://community.rstudio.com/t/struggling-to-create-a-scatter-plot-with-time-span/14023) :)

And thanks for your book

**Comment by vspinu** [comment]
Yeh. You are doing something that doesn't make much sense. You should read a bit more about data.frames I guess.  The lines like the following shouldn't be in your code:

```R
JULG1 <- as.data.frame(as.period(JULG1), row.names("Cases"), col.names("Tempo"))
```

**Comment by dillalan** [comment]
Ok, I'll do. Thanks
