### ISSUE TITLE
Negative durations are displayed as positive

### ISSUE THREAD

**Issue by jfritzemeier** [tidyverse/lubridate#719]
Title says it all (sry for the bad formatting):

> x
>[1] "47s"                   "221s (~3.68 minutes)"  "31s"                  
>[4] "7s"                    "791s (~13.18 minutes)" "29s"                  
> dput(x)
> new("Duration", .Data = c(47, -221, 31, 7, -791, 29))
>

Here the -221 seconds are displayed as ~3.68 minutes. There is no clue that this is actually negative. This is a major issue when debugging. Especially when doing comparisons like:

`x <= dseconds(59)`

**Comment by hglanz** [comment]
I am working on this for Tidyverse Dev Day 2019
