### ISSUE TITLE
Error in addition of POSIXt and Period

### ISSUE THREAD

**Issue by quantitative-technologies** [tidyverse/lubridate#720]
I encountered the following bug adding a Period to a POSIXct type:

    time <- as.POSIXct("2017-11-06 04:00:00", tz = 'America/New_York')

   > time + 10902601
    [1] "2018-03-12 09:30:01 EDT"

However, the following calculation give an incorrect result:

    > time + lubridate::seconds(10902601)
    [1] "2018-03-12 08:30:01 EDT"

**Comment by vspinu** [comment]
Arithmetics with periods has some peculiarities across DST repats and gaps. Compare

```R
> time <- ymd_hms("2018-03-11 00:00:00", tz = 'America/New_York')
> time + hours(3)
[1] "2018-03-11 03:00:00 EDT"
> time + seconds(3600*3)
[1] "2018-03-11 03:00:00 EDT"
> time + 3600*3
[1] "2018-03-11 04:00:00 EDT"
```

First two add periods, the last one ads durations. Periods compute on "clock time" while "durations" on actual time spent.
