### ISSUE TITLE
is.period fails with sapply

### ISSUE THREAD

**Issue by Superstud** [tidyverse/lubridate#723]
`is.period(months(1))`
returns TRUE 

`sapply(months(1), is.period)`
returns FALSE

R version 3.5.1 Windows, lubridate 1.7.4

**Comment by vspinu** [comment]
`months(1)` is not a vector or list so you cannot map over it.

**Comment by Superstud** [comment]
I was trying to make a minimal replicable example. Let me make it into a vector then:

`sapply(c(months(1), months(1)), is.period)
[1] FALSE FALSE`

`map(c(months(1), months(1)), is.period)
[1] TRUE TRUE`

I realize I should use map instead, but I prefer to minimize dependencies on libraries. Maybe this is more of a problem with sapply than is.period?

**Comment by vspinu** [comment]
By map I meant sapply actually . 

```R
sapply(list(months(1), months(1)), is.period)
> sapply(list(months(1), months(1)), is.period)
[1] TRUE TRUE
```

`c` is a concatenation which creates another period object. Use `str` to see things more clearly.
