### ISSUE TITLE
Suggestion to support ISO week in the lubridate functions  

### ISSUE THREAD

**Issue by kbzsl** [tidyverse/lubridate#729]
Is it possible to implement the  isoweek (%V) support in lubridate date parsers? 
(for example 2017-W2-3, in case of isoweek is 2017-jan-11)

**Comment by vspinu** [comment]
Everything is possible but there should be a demand for this. I am afraid this is low priority and probably will happen only on parser rewrite/extraction from lubridate.

**Comment by hadley** [comment]
Duplicate of #506 — you might want to thumbs up that issue just to register your interest.
