### ISSUE TITLE
request: year/quarter/month/week/day sine/cosine for Machine Learning

### ISSUE THREAD

**Issue by EngrStudent** [tidyverse/lubridate#731]
Most linear models have no way to know that December 31st and January 1st are adjacent in some sense.  If we convert day of year to a pair of columns then we can give a clean way to make that "numerically obvious" to the "machine learner".  In the same way that without some transformation it is against the data to assert that the first follows the 31st, or hour 0 follows hour 24, or day 7 is followed by day 1, and putting these additional columns can make the analysis better.

I think that a few clean functions that give the cosine and sine of "2 * pi * subperiod_index / subperiods_per_period" could be useful for a wide variety of numeric models.  The characteristic times that I run into include, year, quarter, month, week, and day.  Sometimes year and quarter are fiscal, instead of calendar.  I have seen chrono-biological segments of hours in the day: vespertine, matutinal, crepuscular, diurnal, and nocturnal.

References: 
- https://ianlondon.github.io/blog/encoding-cyclical-features-24hour-time/
- https://www.avanwyk.com/encoding-cyclical-features-for-deep-learning/ 
- https://www.kaggle.com/avanwyk/encoding-cyclical-features-for-deep-learning
- https://datascience.stackexchange.com/questions/5990/what-is-a-good-way-to-transform-cyclic-ordinal-attributes

**Comment by vspinu** [comment]
Good idea. I don't mind having this in the package. 

Would you mind giving it a stab with a documentation and reference links? 

What should be the API for it?

How about `cyclic_expansion(date-time, periods=xxx)` where `xxx` is a character vector of period specification like `c("3m2w", "w", "2hours", ...). See `period` and internal parser for what kind of specs could be parsed:

```r
lubridate:::parse_period("3m2w")
[1] "3m 14d 0H 0M 0S"
```

I am not sure if this generality is warranted though. Maybe just stick with exact calendar cycles like you propose and be done with it. Then `cyclic_expansion(date-time, periods=`y3md`)` could expand into 3col data.frame (or matrix?) of year, quarter and day expansions.

**Comment by EngrStudent** [comment]
@vspinu - I am very open to doing this.  Would you please point me to where something like it was done well, so I can have a clearer idea of your expectations, and do well with the work that I do?  I think the offset is powerful with this, so there would be three inputs.  `cyclic_expansion(date_time, characteristic_period, offset) `.  

Where you say `periods=xxx` I like it, because I find that I put several of these together and as candidate inputs, and let the process say which are more important.  It is a really good point that the `xxx` could be a vector of characteristic periods, for which the output could have a pair of columns.  If that were the case, the `offset` should be `offsets`, and supply either a scalar, or a vector the same size as `characteristic_periods`.

Thank you.

**Comment by vspinu** [comment]
What is `offset` more concretely?

**Comment by m-r-munroe** [comment]
It is like "origin" for dates.  In trigonometric terms, for "y = sin(a*t + b)" it is the "b".  It moves the upward crossing of zero by the sin, translating it along the domain.  It can give a "hook" for the learner, because at that critical time, the sine function has a linear relationship.  It is a poor mans way of putting ephemeris information into the variable.

**Comment by EngrStudent** [comment]
An example: year sine and cosines:

No offset:    
day_of_year <- "today" - "jan 1 this year"
y_sin = sin(2*pi*day_of_year/days_in_year)
y_cos = cos(2*pi*day_of_year/days_in_year)

with_offset:
day_of_year_given_origin <- ("today" - "origin") %% 365
y_sin = sin(2*pi*day_of_year_given_origin/days_in_year)
y_cos = cos(2*pi*day_of_year_given_origin/days_in_year)

**Comment by solalatus** [comment]
@EngrStudent did you implement this at the end? Any news? This would be highly appreciated!

**Comment by vspinu** [comment]
Guys, I am on it finally. What about naming/UI? 

Do we really need both cos and sin expansion? I think it can just be an argument to `cyclic_expansion` function, like `cyclic_expansion(x, "2m", type="cos")`? 

Regarding the offset I think it's easier to just offset the datetime first by bringing the desired "hook" time into the origin and then get the expansion.

**Comment by solalatus** [comment]
Only argument for both sin and cos is, that only sin and only cos maps eg. certain hours of the day to the same values. The combination of sin and cos ensures uniqueness. (As far as I understand.)

**Comment by vspinu** [comment]
Not sure I understand. There is a one to one relationship between cos and sin, so having sin you can get the cos. I doubt one would need both in ML tasks. In any case, one could call `cyclic_expansion` twice to get both, so not a big deal I would guess. Also one could think of non-trigonometric expansions of this sort, so now I am quite strongly inclined to have one function for all such expansions.

**Comment by solalatus** [comment]
https://ianlondon.github.io/blog/encoding-cyclical-features-24hour-time/ 
But I agree, one can call it twice, not a big hassle.

**Comment by vspinu** [comment]
Right. Both are needed simultaneously. I have overlooked this uniqueness "side effect".

**Comment by vspinu** [comment]
Hi guys, this is what I have cooked up so far. Will commit in the evening after adding some tests. Please have a look and test/comment if you have time:

```R

#' Cyclic encoding of date times
#'
#' Encode a date-time object into a cyclic coordinate system in which the
#' distance between two pairs of dates separated by the same time period would
#' be the same.
#'
#' Machine learning models don't know that December 31st and January 1st are
#' close in our calendar sense. `cyclic_encoding` makes it obvious to the
#' machine learner that two calendar dates are close in some numeric sense by
#' mapping the dates onto the circle.
#'
#' @param x a date-time object
#' @param periods a character vector of periods. Follows same specification as
#'   [period] and [floor_date] functions.
#' @param types types of encoding to produce. Defaults to "sin" and "cos". Names
#'   of any predefined functions accepting a numeric input are allowed.
#' @param week_start day starting a week (used for weekly periods).
#' @return a numeric matrix with number of columns equal `length(periods) *
#'   length(types)`.
#' @examples
#' times <- ymd_hms("2019-01-01 00:00:00") + hours(0:23)
#' cyclic_encoding(times, c("day", "week", "month"))
#' plot(cyclic_encoding(times, "1d"))
#' plot(cyclic_encoding(times, "2d"), xlim = c(-1, 1))
#' plot(cyclic_encoding(times, "4d"), xlim = c(-1, 1))
#' @export
cyclic_encoding <- function(x, periods, types = c("sin", "cos"),
                             week_start = getOption("lubridate.week.start", 7)) {
  Nt <- length(types)
  Np <- length(periods)
  out <- matrix(0, nrow = length(x), ncol = Nt * Np)
  colnames(out) <- paste(rep.int(types, Np),
                         rep(periods, each = Nt),
                         sep = ".")
  for (pix in seq_along(periods)) {
    p <- periods[[pix]]
    beg <- as.numeric(floor_date(x, unit = p, week_start = week_start))
    end <- as.numeric(ceiling_date(x, unit = p, week_start = week_start))
    diff <- (2*pi)*(as.numeric(x) - beg)/(end - beg)
    diff[end == beg] <- 0
    for (tix in seq_along(types)) {
      out[, (pix - 1)*Nt + tix] <- do.call(types[[tix]], list(diff))
    }
  }
  out
}

```

**Comment by solalatus** [comment]
I can"t test it now, but as a first: it looks cool and general! Great!
