### ISSUE TITLE
Mathematical operations with infinite dates and datetimes

### ISSUE THREAD

**Issue by keesdeschepper** [tidyverse/lubridate#732]
Philosophical considerations aside, I think that last one should be TRUE as well.

```
library(lubridate)
infinity <- as_date(Inf)
is.infinite(infinity)
# TRUE
is.infinite(infinity + make_difftime(12, "hours"))
# TRUE
is.infinite(infinity + hours(12))
# FALSE
```

**Comment by keesdeschepper** [comment]
Something like:
```
library(lubridate)
library(tidyverse)

add_period_to_date <- function(per, date) {
  
  if(is.infinite(per) || is.infinite((date))){
    return(as_date(as.numeric(per) + as.numeric(date)))
  }
  
  # normal path
}
```
seems to do the trick:
```
walk2(
  c(30,  Inf, Inf, -Inf,  Inf, -Inf),
  c(Inf, 30,  Inf, -Inf, -Inf,  Inf),
  ~ add_period_to_date(period(.x), as_date(.y)) %>% 
    {message(is.Date(.), " ", as.numeric(.))}
)
# TRUE Inf
# TRUE Inf
# TRUE Inf
# TRUE -Inf
# TRUE NaN
# TRUE NaN
```

**Comment by hadley** [comment]
Minimal reprex, also showing issue with durations:

``` r
library(lubridate, warn.conflicts = FALSE)
inf <- as_date(Inf)

unclass(inf)
#> [1] Inf
unclass(inf + dhours(12))
#> Error in if (all(hour(na.omit(ans)) == 0 & minute(na.omit(ans)) == 0 & : missing value where TRUE/FALSE needed
unclass(inf + hours(12))
#> [1] NA
unclass(inf + make_difftime(12, "hours"))
#> [1] Inf
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by keesdeschepper** [comment]
Would a post-processing step like reclass_date be the way to go?
Something like:
```
account_for_infinity.POSIXct <- function(new, old1, old2){
  indices_infinity <- is.infinite(as.numeric(old1)) | is.infinite(as.numeric(old2))
  new[indices_infinity] <- as_datetime((as.numeric(old1) + as.numeric(old2))[indices_infinity])
  new
}
```

**Comment by hadley** [comment]
I think it would be better to fix in the date-time arithmetic code.

**Comment by keesdeschepper** [comment]
Okay let me see what I can do

**Comment by keesdeschepper** [comment]
One more problem is that a Date plus e.g. an hour period will give a POSIXlt, which is a class that does not handle infinity well. This is a problem when finite and infinite dates are mixed:
```
class(as_date(c(0, Inf)) + hours(1))
#> "POSIXlt" "POSIXt" 
as.numeric(as_date(c(0, Inf)) + hours(1))
#> 3600   NA
```
Not sure why this has to be a POSIXlt, but in test-settors.R it is enforced by "hours settor retains object class" and "minutes settor retains object class" (does not follow from test titles though). (And strangely, "seconds settor retains object class" tests the `day` settor for Dates instead of the `second` settor).

**Comment by hadley** [comment]
That should almost certainly be a POSIXct; it might be better to fix that in a separate PR first.

**Comment by jwilliman** [comment]
Is the following the same problem, or could it have a clearer error message? `

``` r

library(lubridate, warn.conflicts = FALSE)

as.period(Sys.Date() %--% as_date(Inf), "days")
#> Error in if (sum(values - trunc(values))) {: argument is not interpretable as logical
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
Has been fixed.
