### ISSUE TITLE
A function to get the time component of a date-time

### ISSUE THREAD

**Issue by IndigoJay** [tidyverse/lubridate#740]
A partner to the lubridate::date() function, which returns the H:M:S time component of a date-time. 

In the lubridate cheat sheet there is an example for date():

> **2018-01-31** 11:59:59 - date(x) Date component. date(dt)

I propose the need for a similar function on the time side:

> 2018-01-31 **11:59:59** - get_time(x) Time component. get_time(dt)

My function:
```
get_time <- function(t = now()) {
  strftime((t), format="%H:%M:%S", tz = tz(t)) 
}
```
_edit: pass time zone_

**Comment by vspinu** [comment]
From the docs of `local_time`:

```R

> x <- ymd_hms(c("2009-08-07 01:02:03", "2009-08-07 10:20:30"))
> local_time(x, units = "secs")
Time differences in secs
[1]  3723 37230
> local_time(x, units = "hours")
Time differences in hours
[1]  1.034167 10.341667
> local_time(x, "Europe/Amsterdam")
Time differences in secs
[1] 10923 44430
> local_time(x, "Europe/Amsterdam") == local_time(with_tz(x, "Europe/Amsterdam"))
[1] TRUE TRUE
> 
> x <- ymd_hms("2009-08-07 01:02:03")
> local_time(x, c("America/New_York", "Europe/Amsterdam", "Asia/Shanghai"), unit = "hours")
Time differences in hours
[1] 21.034167  3.034167  9.034167
> 
```

Is this what you are after?

**Comment by vspinu** [comment]
There is a `hms` package which defines a specialized `hms` class for intraday time.

**Comment by IndigoJay** [comment]
Hi VSpinu, thank you for your comments. 

I realized I needed to perform my analysis in seconds() (not at HH:MM:SS).

And, although I am working with intraday time - it is better to use the whole date-time class properly. 

Thank you, Have a great 2019!
