### ISSUE TITLE
Automatically build web site with travis?

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/lubridate#743]
Hi @vspinu,

We've now set things up such that the pkgdown website for several of the tidyverse packages are automatically built through travis. If you're ok with that for lubridate, @hadley said he'd be happy to set that up here as well.

Thanks,

Mara

**Comment by vspinu** [comment]
Yes, of course. Thanks!

**Comment by hadley** [comment]
All plumbed up now 😄
