### ISSUE TITLE
Unit test fails on the day before the change to or from savings time.

### ISSUE THREAD

**Issue by bruc** [tidyverse/lubridate#757]
During routine testing of lubridate, I had a test failure:

Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
      date
  
  ── 1. Failure: difftime comparison with periods works (@test-ops-compare.R#63)  
  days(1) == (t + days(1)) - t isn't true.
  
  ── 2. Failure: difftime comparison with periods works (@test-ops-compare.R#64)  
  (t + days(1)) - t == days(1) isn't true.
  
I instrumented the test-ops-compare.R to see why, and the problem is that tonight, the timezone changes. The test then fails. Here's the instrumented code:

```r
test_that("difftime comparison with periods works", {
    t <- now()
    print(t)
    print(days(1))
    print(t + days(1))
    print(t + days(1) - t)
  expect_true(days(1) == (t + days(1)) - t)
  expect_true((t + days(1)) - t == days(1))
})
```
and here is the output:
```r
> source("test-ops-compare.R")
[1] "2019-03-09 11:21:00 EST"
[1] "1d 0H 0M 0S"
[1] "2019-03-10 11:21:00 EDT"
Time difference of 23 hours
Error: Test failed: 'difftime comparison with periods works'
* days(1) == (t + days(1)) - t isn't true.
* (t + days(1)) - t == days(1) isn't true.
```
I suggest modifying t <- now() to instead use a fixed date that's not near a time change anywhere on earth for this test.

**Comment by vspinu** [comment]
Thanks for so carefully identifying this!
