### ISSUE TITLE
Enhancement request: special periods for accounting

### ISSUE THREAD

**Issue by RAPosthumus** [tidyverse/lubridate#761]
I work in the world of accounting. We use "special" periods e.g. a period 14 that updates the final figures for a book year, but these amendments are made in a new fiscal year. See e.g. [special periods in SAP](https://help.sap.com/doc/saphelp_sfin100/1.10/en-US/22/52d7531a4d424de10000000a174cb4/content.htm?no_cache=true)

Could you add functionality for handling these special periods, I'm thinking of:
specifying the special period e.g. P14: starts two periods after 31/12, the Posting Date = last day of the fiscal year (eg 12/31/2019) AND if there is a special Posting Period value to 13 or 14 or 15 or 16, then these postings end up in the special period, that is ordered like P12=month 12, P13, P14, P15, P16, P1=month 1, new book year, so we have  a way to keep those adjusting entries out of period 12 but still, include them in the fiscal year?

**Comment by hadley** [comment]
Unfortunately, this is outside the scope of lubridate — there are just too many domain specific calendars for us to support them all.
