### ISSUE TITLE
Inconsistent results summing 1 hour across daylight saving times

### ISSUE THREAD

**Issue by sbocconi** [tidyverse/lubridate#763]
Summing hours(1) to date across daylight saving time produces inconsistent results.

It seems to me that an hour is skipped dependently of the timezone used?

Example:

```r
> class(a)
[1] "POSIXct" "POSIXt" 

> a
[1] "2018-10-28 01:00:00 CEST"

<.POSIXct(a,tz="UTC")
[1] "2018-10-27 23:00:00 UTC"

# this seems to skip an hour
> a + hours(1)
[1] "2018-10-28 02:00:00 CET"

# the following results are not consistent?
>.POSIXct(a + hours(1),tz="UTC")
[1] "2018-10-28 01:00:00 UTC"

> .POSIXct(a,tz="UTC") + hours(1)
[1] "2018-10-28 UTC"
```

**Comment by vspinu** [comment]
Your problem is not clear. Do you expect DST in UTC? UTC has not DST.  The examples above are as expected. And yes, DST skips are time-zone (aka location/city dependent). There are many cities without DST skips and for a lot of locations DST changed over the history.

**Comment by sbocconi** [comment]
```
# this seems to skip an hour
> a + hours(1)
[1] "2018-10-28 02:00:00 CET"
```
Expected result is "2018-10-28 02:00:00 CEST".  "2018-10-28 02:00:00 CET" is one hour later.

```
# the following results are not consistent?
>.POSIXct(a + hours(1),tz="UTC")
[1] "2018-10-28 01:00:00 UTC"

> .POSIXct(a,tz="UTC") + hours(1)
[1] "2018-10-28 UTC"
```
In any reference system, adding one hour to the same date cannot have different outcomes in the same timezone (as happens above, there is one hour difference between the results), depending on whether the conversion to UTC is done before or after the sum.

I cannot imagine this is the expected behaviour

**Comment by vspinu** [comment]
> Expected result is "2018-10-28 02:00:00 CEST". "2018-10-28 02:00:00 CET" is one hour later.

Not quite. 2 - 1 = 1 hour in both cases, and this is how period differences on clock time work. Period arithmetic does not abide normal arithmetic rules, for sure not asociativity. It's a pseudo arithmetics with clock-time not absolute time. If you want arithmetics with absolute time use durations;

```R
a + dhours(1)
[1] "2018-10-28 02:00:00 CEST"
```

**Comment by sbocconi** [comment]
OK, thank you, I was not aware of the clock time nature of hours().
