### ISSUE TITLE
ymd_hms() function error

### ISSUE THREAD

**Issue by mccoy294** [tidyverse/lubridate#765]
I am trying to redefine dates so that they are recategorized as ymd_hms. I have installed lubridate but R is telling me that it doesn't recognize ymd_hms() function. Here is the code. Can someone tell me what I am doing wrong?

library(dslabs)
library(dplyr)
library(lubridate)

data("reported_heights")

dat <- mutate(reported_heights, date_time = ymd_hms(time_stamp,truncated = 0)) %>%
  filter(date_time >= make_date(2016, 01, 25) & date_time < make_date(2016, 02, 1)) %>%
  mutate(type = ifelse(day(date_time) == 25 & hour(date_time) == 8 & between(minute(date_time), 15, 30), "inclass","online")) %>%
  select(sex, type)

reported_heights
y <- factor(dat$sex, c("Female", "Male"))
x <- dat$type

```

**Comment by cderv** [comment]
Your code is working fine on my session
``` r
library(dslabs)
library(dplyr)
library(lubridate)
data("reported_heights")

dat <- mutate(reported_heights, date_time = ymd_hms(time_stamp,truncated = 0)) %>%
  filter(date_time >= make_date(2016, 01, 25) & date_time < make_date(2016, 02, 1)) %>%
  mutate(type = ifelse(day(date_time) == 25 & hour(date_time) == 8 & between(minute(date_time), 15, 30), "inclass","online")) %>%
  select(sex, type)

head(dat)
#>      sex    type
#> 1 Female inclass
#> 2 Female inclass
#> 3   Male inclass
#> 4 Female inclass
#> 5   Male inclass
#> 6   Male inclass
```

<sup>Created on 2019-04-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Don't know what is going on. 🤔 
I would try to reinstall the package and restart R and RStudio. 

For question of this type, to do hesitate to ask on https://community.rstudio.com. There is a broad community ready to help. Github issue are a better place for bug and feature request.

**Comment by mccoy294** [comment]
Thanks @cderv. Got it working again.

**Comment by ANOOPAANTO** [comment]
install.packages("dplyr")
will solve this issue..
also install all give packages in the code

**Comment by ANOOPAANTO** [comment]
also run the below codes for further problems..

**remove.packages('lubridate')

install.packages('Rcpp', dependencies = TRUE)
install.packages('lubridate', dependencies = TRUE)**

**Comment by AdityaUpmanyu** [comment]
Hey guys, I am facing the same issue as OP and I couldn't resolve it through the suggestion. It would be of great help if someone could have a look and point out my error. Here's the code:

data_2014 <- rbind(apr_data,may_data, jun_data, jul_data, aug_data, sep_data)
data_2014$Date.Time <- as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S")
data_2014$Time <- format(as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")
data_2014$Date.Time <- ymd_hms(data_2014$Date.Time)
data_2014$day <- factor(day(data_2014$Date.Time))
data_2014$month <- factor(month(data_2014$Date.Time, label = TRUE))
data_2014$year <- factor(year(data_2014$Date.Time))
data_2014$dayofweek <- factor(wday(data_2014$Date.Time, label = TRUE))

I have reinstalled all packages and restarted R Studio as well.
Below is the error I'm getting:
> data_2014$Date.Time <- ymd_hms(data_2014$Date.Time)
Error in ymd_hms(data_2014$Date.Time) : could not find function "ymd_hms"
> data_2014$day <- factor(day(data_2014$Date.Time))
Error in day(data_2014$Date.Time) : could not find function "day"
> data_2014$month <- factor(month(data_2014$Date.Time, label = TRUE))
Error in month(data_2014$Date.Time, label = TRUE) : 
  could not find function "month"
> data_2014$year <- factor(year(data_2014$Date.Time))
Error in year(data_2014$Date.Time) : could not find function "year"
> data_2014$dayofweek <- factor(wday(data_2014$Date.Time, label = TRUE))
Error in wday(data_2014$Date.Time, label = TRUE) : 
  could not find function "wday"
