### ISSUE TITLE
Expose lubridate:::lubridate_formats or set orders = lubridate_formats as default value in guess_formats()

### ISSUE THREAD

**Issue by DaniMori** [tidyverse/lubridate#768]
When one has no clue of a date format, or wants to use `guess_formats()` in other packages to automate format inferences, it would be very useful if `lubridate:::lubridate_formats` were exposed on the package interface.

Alternatively, argument `order` could be set by default to `order = lubridate_formats`.

``` r
library(lubridate, warn.conflicts = FALSE)


guess_formats("2019-04-26", order = lubridate:::lubridate_formats)
#>        yOmd        yOmd         ymd 
#> "%Y-%Om-%d" "%Y-%Om-%d"  "%Y-%m-%d"


## Not run:
guess_formats("2019-04-26")
#> Error in gsub("[^[:alpha:]]+", "", orders): el argumento "orders" está ausente, sin valor por omisión

## Not run:
guess_formats("2019-04-26", order = lubridate_formats)
#> Error in gsub("[^[:alpha:]]+", "", orders): objeto 'lubridate_formats' no encontrado
```

<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
I think there are very few cases where it makes sense to try every possible format, so I'd prefer not to make this easier than it already is.

**Comment by DaniMori** [comment]
I'm sorry to insist on this, but I have to disagree. This option would not only allow to test every possible format, but also to safely tell `guess_formats()` which formats you may want to test.
Take e.g. the following example, which tests all the formats that start with a year:

``` r
library(lubridate, warn.conflicts = FALSE)
library(stringr,   warn.conflicts = FALSE)

test_formats <- str_subset(lubridate:::lubridate_formats, "^y")
print(test_formats)
#>  [1] "ymdTz" "ymdT"  "ymdR"  "ymdr"  "ydmT"  "ydmR"  "ydmr"  "ymd"  
#>  [9] "ydm"   "ym"    "y"

guess_formats("2019-11-20", order = test_formats)
#>         ydOmr          yOmd          ydmr           ymd 
#> "%y%d-%Om-%H"   "%Y-%Om-%d"  "%y%d-%m-%H"    "%Y-%m-%d"
```

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In addition, I also think it would be good if `order` were safely parsed with (in addition to the parsing with `gsub`, or maybe instead of):

```
order <- match.arg(order, lubridate_formats, several.ok = TRUE)
```

Hope this helps somehow. It would make me really happy if you reconsidered this issue :)

**Comment by vspinu** [comment]
I agree with @hadley. This shouldn't be done. First, it's practically impossible to distinguish between some formats as two or more formats could parse same string and which string will be parsed is decided heuristically or by FIFO. So such blind strategy will likely to cause a crazy amount of pain. Second, if that list is changed in the future it will likely cause problems with existing code. So you shouldn't relying on it in your code anyhow. Third, if your situation is so messy that you don't know the formats, it's likely that `lubridate_formats` won't be enough. Finally, using the internal structure is trivial in development  or interactive use. Once figured out the formats, plug them in your code.
