### ISSUE TITLE
how not to lose information after using lubridate?

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/lubridate#771]
Consider this simple example

```
tibble(time = '2018-01-01 15:30:00.100') %>% 
  mutate(timestamp = lubridate::parse_date_time(time,'%Y-%m-%d %H:%M:%OS3'),
         character_time = strftime(timestamp, '%Y-%m-%d %H:%M:%OS3'))
 1 parsed with %Y-%Om-%d %H:%M:%OS
# A tibble: 1 x 3
  time                    timestamp               character_time         
  <chr>                   <dttm>                  <chr>                  
1 2018-01-01 15:30:00.100 2018-01-01 15:30:00.099 2018-01-01 10:30:00.099
```

Typically, one receives timestamps stored as characters (the `time` column), then process them with `lubridate` and finally convert to character before writing the file as a `csv`.

Here you can see a major issue: the millisecond part is wrongly kept to `.099` after the conversion to character.

My understanding was that the `.099` millisecond rounding in the `datetime` from `lubridate` was just a printing error (that is, internally this is a `100` millisecond). If so, why is the conversion to character wrong?

Thanks!!!

**Comment by vspinu** [comment]
These are the joys of floating point representation of POSIXct objects in R. Ideally the `sprtime` should be able to deal with it correctly but it doesn't. Lubridate has nothing to do with it:

```R
> options(digits = 20)
> x <- '2018-01-01 15:30:00.100'
> y <- parse_date_time(x, 'YmdHMS')
> unclass(y)
[1] 1514820600.0999999046
attr(,"tzone")
[1] "UTC"
> 1514820600.1
[1] 1514820600.0999999046
> 
```

So I am afraid you are stuck. A workaroud is to manipulate the digits yourself. Something like:

```R
> options(digits.secs = 0)
> paste0(format(y), ".", sprintf("%02.0f", (n - round(n))*100))
[1] "2018-01-01 15:30:00.10"
```

**Comment by randomgambit** [comment]
interesting, thanks! but coming back to `lubridate` is the representation correct at least internally? I am afraid this is not working correctly here

```
ymd_hms('2018-01-01 15:30:00.100') + dseconds(0.001)
 1 parsed with %Y-%Om-%d %H:%M:%OS
[1] "2018-01-01 15:30:00.100 UTC"
```

**Comment by randomgambit** [comment]
at the same time this is working OK

```
ymd_hms('2018-01-01 15:30:00.100') == 
  (ymd_hms('2018-01-01 15:30:00') + dseconds(0.1))
[1] TRUE
```

I am PUZZLED @vspinu !

**Comment by randomgambit** [comment]
@vspinu so should I think that, although the 100 millisecond appears as .999 on the console, internally all the computations will be as if the timestamp was correctly stored?

**Comment by vspinu** [comment]
>  is the representation correct at least internally?

It is correct internally. Don't be confused by the printed version. The R printer is buggy. It doesn't deal correctly with fractions of the second. There is a bug report somewhere. 

> as .999 on the console, internally all the computations will be as if the timestamp was correctly stored?

This is the floating number representation, which is not exact by definition. The consequence of this is that R POSIXct is good for storing times up to micro-seconds. You should be fine for your use case as you deal with miliseconds. There are plenty of blogs out there explaining floating points. I would suggest you dig into those a bit.

**Comment by randomgambit** [comment]
Thanks @vspinu for the nice clarification!
