### ISSUE TITLE
Time zone argument returning opposite of expected for GMT+/-

### ISSUE THREAD

**Issue by johngayler** [tidyverse/lubridate#773]
When using the `now()` function with `tzone = "Etc/GMT-7"`  or `as.POSIXct()` the object that is returned is set to the "Etc/GMT+7" timezone instead. 

This output is the opposite to what I would expect. To return an current date time in the correct (GMT-7) timezone, you are required to instead call `now(timezone= "Etc/GMT+7")`.

---
tz / tzone arguments are returning the inverse of what is expected. 

```r
# insert reprex here
> as.POSIXct("2019-01-01 00:00:01", tz = "Etc/GMT-7")
[1] "2019-01-01 00:00:01 +07"
> as.POSIXct("2019-01-01 00:00:01", tz = "Etc/GMT+7")
[1] "2019-01-01 00:00:01 -07"

```

**Comment by vspinu** [comment]
First, it's the printer. The time zone attribute is the same that you provided:

```R
> attributes(now("Etc/GMT-7"))
$class
[1] "POSIXct" "POSIXt" 

$tzone
[1] "Etc/GMT-7"
```

Second, this is how GMT+N is defined. See [here](https://stackoverflow.com/a/21058381/453735) and [here](https://www.tickcounter.com/worldclock/416/etc-gmt-7).
