### ISSUE TITLE
day("01-01-2016") returns day 20 with no warning of 4 digit input.

### ISSUE THREAD

**Issue by jaracklawrence** [tidyverse/lubridate#774]
The day() function (and week() function similarly) returns the first two digits from year in the following examples so long as those first two digits are between 1 and 31. This somewhat makes sense given it's expecting the format ymd. However, an error or warning should be present where the expected day figure is more than two digits, rather than just ignoring all extra digits.

> day("01-01-20")
[1] 20
> day("01-01-2016")
[1] 20
> day("01-01-3016")
[1] 30
> day("01-01-3116")
[1] 31
> day("01-01-3199")
[1] 31
> day("01-01-319999999999999999")
[1] 31
> day("01-01-4000")
Error in as.POSIXlt.character(x, tz = tz(x)) : 
  character string is not in a standard unambiguous format

**Comment by vspinu** [comment]
You call day on character which is converted internally with as.POSIXct which has the issue which you have discovered. To avoid such issues parse with lubridate functions explicitely:

```R
> day(ymd("01-01-319999999999999999"))
[1] NA
Warning message:
All formats failed to parse. No formats found. 
```
