### ISSUE TITLE
feature request: proper resampling functions (Pandas-like)

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/lubridate#782]
Hello,

I wonder if `lubridate` could contain some functions to resample time series indexes in the vein of Pandas:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

Resampling time series data is the bread and butter of TS analysis, and I dont think there is a tidyverse-like package that allows doing that. Yes, we can always use `reticulate` but this is not very efficient in many cases.

What do you think?

**Comment by hadley** [comment]
This is outside of the scope of lubridate; you might try a package that's designed more for timeseries like zoo or tsibble.
