### ISSUE TITLE
lubridate won't build, Centos 6.9 (source R-3.4, R-3.6, various gcc)

### ISSUE THREAD

**Issue by jbsysadmin** [tidyverse/lubridate#784]
Greetings. Can you post a series of steps & pre-reqs to install lubridate version 1.7.4? 

Assumptions:
	Centos 6.9
	R-3.6.0 compiled from vanilla source
	Either gcc versions 6.4.0 or 8.2.0 from vanilla source

Someone wanted "tidyverse" installed, but that install fails because of the lubridate dependency.
Both "R CMD INSTALL lubridate" and install.packages("lubridate") fail. No problems in the least on Centos 7.x (and in-OS resources) but that might not be an option yet.

**Comment by hadley** [comment]
It builds for us on travis using standard gcc and R 3.2-3.6, so it's likely to be something you'll need to track down on your end.
