### ISSUE TITLE
Incorrect parsing with microseconds and time zone offsets

### ISSUE THREAD

**Issue by tonytonov** [tidyverse/lubridate#786]
An unexpected behavior occurs when trying to parse timestamps with microseconds and time zone offsets.

```r
library(lubridate)
dates <- c("20190730-100000.001+0200", "20190730-100000+0100", "20190730-100000+0000",
           "20190730-100000.001-0100", "20190730-100000-0200")

strptime(dates, format = "%Y%m%d-%H%M%OS%z", tz = "UTC")
parse_date_time(dates, orders = "%Y%m%d-%H%M%OS%z", tz = "UTC", exact = TRUE, train = FALSE)
fast_strptime(dates, format = "%Y%m%d-%H%M%OS%z", tz = "UTC")
```

Output:

```
[1] "2019-07-30 08:00:00.001 UTC" "2019-07-30 09:00:00.000 UTC" "2019-07-30 10:00:00.000 UTC"
[4] "2019-07-30 11:00:00.001 UTC" "2019-07-30 12:00:00.000 UTC"
[1] "2019-07-30 08:00:00.000 UTC" "2019-07-30 09:00:00.000 UTC" "2019-07-30 10:00:00.000 UTC"
[4] "2019-07-30 11:00:00.000 UTC" "2019-07-30 12:00:00.000 UTC"
[1] "2019-07-30 08:00:-7199.999 UTC" "2019-07-30 09:00:-3600.000 UTC" "2019-07-30 10:00:00.000 UTC"   
[4] "2019-07-30 11:00:3600.001 UTC"  "2019-07-30 12:00:7200.000 UTC" 
```

Session info:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.7.4 magrittr_1.5   

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    Rcpp_1.0.2     stringi_1.4.3  stringr_1.4.0 
```

**Comment by vspinu** [comment]
This is a printer issue (which is a bit buggy on R side). All of the datetimes are the same. Note that `fast_strptime` returns POSIXlt.

``` r
library(lubridate, warn.conflicts = FALSE)
dates <- c("20190730-100000.001+0200", "20190730-100000+0100", "20190730-100000+0000",
           "20190730-100000.001-0100", "20190730-100000-0200")
options(digits.secs = 5)
sx <- strptime(dates, format = "%Y%m%d-%H%M%OS%z", tz = "UTC")
px <- parse_date_time(dates, orders = "YmdHMSz", tz = "UTC")
fsx <- fast_strptime(dates, format = "%Y%m%d-%H%M%OS%z", tz = "UTC")
px2 <- parse_date_time2(dates, orders = "YmdHMOSz", tz = "UTC")

all.equal(sx, px)
#> [1] TRUE
all.equal(sx, fsx)
#> [1] TRUE
all.equal(sx, as.POSIXct(fsx))
#> [1] TRUE
all.equal(sx, px2)
#> [1] TRUE

class(fsx)
#> [1] "POSIXlt" "POSIXt"
class(px2)
#> [1] "POSIXct" "POSIXt"
```

<sup>Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tonytonov** [comment]
Thanks. How do you know that this is an R issue? Is there a bug report or a discussion at R-core?
I appreciate the explanation and the workaround via `as.POSIXct`, however I don't think this is related to the `print` S3 method: `fsx[1]$sec` returns -7199.999. The help page `?POSIXlt` clearly states that the expected range for seconds is 0-61. So if one uses the combination of `fast_strptime` and then retrieves entries from this class, this would be highly unexpected, even though technically the coercion to `POSIXct` is correct.

**Comment by vspinu** [comment]
> How do you know that this is an R issue? Is there a bug report or a discussion at R-core?

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17350

> The help page ?POSIXlt clearly states that the expected range for seconds is 0-61

This part is not enforced, so fast_strptime didn't enforce it either for efficiency reasons. To fix this would require `as.POSIXct -> as.POSIXlt` cycle which is very expensive. 

```R
> x <- as.POSIXlt(now())
> x
[1] "2019-12-03 22:41:43 CET"
> x$sec <- 100
> x
[1] "2019-12-03 22:42:40 CET"
> second(x)
[1] 100
```

We are generally downplaying POSIXlt gradually and its practical use should be rather limited. But I agree, fast_strptime should be consistent with strptime whenever possible (#840).

**Comment by tonytonov** [comment]
Fair points. And I indeed stumbled upon this when trying to speed up `strptime`. Thanks again.
