### ISSUE TITLE
suggestion to add attribute "approx" to Duration class

### ISSUE THREAD

**Issue by mgacc0** [tidyverse/lubridate#787]
In my code, I usually define a function `to_approx_duration`:
``` r
library(stringr)
library(lubridate)

to_approx_duration <- function (time) str_replace(as.duration(time), ".*\\((.*)\\)$", "\\1")

to_approx_duration(minutes(3473))
#> [1] "~2.41 days"

to_approx_duration(hours(9939))
#> [1] "~1.13 years"
```
---
Would you consider interesting to add a public attribute `approx` to the `Duration` class?
So it would be possible to obtain something like:
``` r
as.duration(minutes(3473))$approx
#> [1] "~2.41 days"
```

**Comment by hadley** [comment]
This feels like a very specialised use case, so I think is out of scope for lubridate.
