### ISSUE TITLE
Determine if interval is greater than or less than a time

### ISSUE THREAD

**Issue by yogat3ch** [tidyverse/lubridate#788]
>=, <=, >, < with intervals?

---
It would be great if simple boolean >=, <=, >, < would work for times compared to intervals. %within% allows one to determine if a time falls inside an interval, but what if one wants to know if a time is in the past relative to an interval or in the future relative to an interval?
I'm not sure how difficult/easy/possible it is to modify the function of primitives relative to the classes involved but the functionality would be nice.

```r
isTRUE(lubridate::interval(start = lubridate::ymd("2019-08-12"), end = lubridate::ymd("2019-08-20")) < lubridate::ymd("2019-08-24")) # Should be true
isTRUE(lubridate::interval(start = lubridate::ymd("2019-08-12"), end = lubridate::ymd("2019-08-20")) > lubridate::ymd("2019-08-25")) # should be false
```

**Comment by vspinu** [comment]
You can just `int_start(int) < date`. IMO it's more readable this way as the semantics of `<` is immediately clear.

**Comment by yogat3ch** [comment]
Indeed, this is what I ended up doing. It seems like a common use case and thus I suggested that the primitive might function differently when applied to this class. I'm imagining it might be difficult to create such functionality though - so I'll just go ahead and close this. Thanks!
