### ISSUE TITLE
tz() should error on non-dates

### ISSUE THREAD

**Issue by NanisTe** [tidyverse/lubridate#790]
We unfortunately had lost some time to figure out, that the input of the tz() function is not what is expected, the return of the function is always "UTC" if a not supported type is passed. This is unexpected behaviour and can lead to very strange things further on ones code.

---

Where not able to make reprex working in my machine for this example.

```r
x <- data.frame(datetime = as.POSIXct("2010-01-01 00:00:00", tz = "Europe/Zurich"))
tz (x$datetime)
tz (x["datetime"])
tz (x[["datetime"]])
tz("fajhgoiuwnrlk")
tz(500)
```
Results are
```
> x <- data.frame(datetime = as.POSIXct("2010-01-01 00:00:00", tz = "Europe/Zurich"))
> tz (x$datetime)
[1] "Europe/Zurich"
> tz (x["datetime"])
[1] "UTC"
> tz (x[["datetime"]])
[1] "Europe/Zurich"
> tz("fajhgoiuwnrlk")
[1] "UTC"
> tz(500)
[1] "UTC"
```

**Comment by hadley** [comment]
Fixing this would involve replacing `tz.default()` with `tz.POSIXt()`, `tz.Date()` (for backward compatibility, probably should return `NA` with warning), and new `tz.default()` that displays an informative error message.

**Comment by hadley** [comment]
The challenge with making this change is that many existing lubridate functions assume that `tz()` returns "UTC" for dates and character vectors, so this probably needs a new helper that can be used internally. This makes the problem quite a bit harder than I'd originally thought.

**Comment by vspinu** [comment]
I think this one can be considered taken care of. We now return "UTC" only on Dates, characters and logical NA. Those types are automatically promoted all over the place and "UTC" is the lubridate-wide default time-zone. So, it's a good compromise IMO.
