### ISSUE TITLE
Handling of `NA` values in `ymd`

### ISSUE THREAD

**Issue by carloscinelli** [tidyverse/lubridate#791]
This is related to https://github.com/rstudio/distill/issues/104

Currently `lubridate::ymd` throws the following error if `tz = NA`,

``` r
lubridate::ymd("2019/09/10", tz = NA)
#> Error in if (tz != "UTC") {: missing value where TRUE/FALSE needed
```

Maybe `NA`'s should be handled differently? Or at least I guess the error message should be more informative.

**Comment by vspinu** [comment]
Yes. More informative error would make sense here.

**Comment by hadley** [comment]
The current warning doesn't seem too bad to me since it includes both `tz` and `missing value`
