### ISSUE TITLE
Suggestion to add function to find next / last weekday

### ISSUE THREAD

**Issue by TimTeaFan** [tidyverse/lubridate#794]
When dealing with dates finding the next (or last) weekday (w) of a certain date (d) is a common problem. For example: Finding the next Monday after Sep 13, 2019 (Fri) which would be Sep 16, 2019 (Mon). It would be great to have such a function in lubridate.

Below is the core (without checks of parameters w, d) of a function called `next_wday()` and ist equivalent  `last_wday() `, which make use of `lubridate::wday()`.

Would this be worth a pull request? If yes, I would give it a try and flesh out the function below.

```
# a function to find the next weekday w of date d

next_wday <- function(d, w) { 

  d + (seq(w - 1, length = 7) %% 7 + 1L)[8 - lubridate::wday(d)] 

}

# a function to find the last weekday w of date d

last_wday <- function(d, w) {
  
  d - (seq(-w, length = 7) %% 7 + 1L)[lubridate::wday(d)] 
  
}

# Example
df <- data.frame(date=seq.Date(from=as.Date('2019-09-11'), to=as.Date('2019-09-21'), by= 1))
df$next_wednesday <- next_wday(df$date, 4)
df$last_monday <- last_wday(df$date, 2)

      date         next_wednesday   last_monday
> 1  2019-09-11     2019-09-18      2019-09-09
> 2  2019-09-12     2019-09-18      2019-09-09
> 3  2019-09-13     2019-09-18      2019-09-09
> 4  2019-09-14     2019-09-18      2019-09-09
> 5  2019-09-15     2019-09-18      2019-09-09
> 6  2019-09-16     2019-09-18      2019-09-09
> 7  2019-09-17     2019-09-18      2019-09-16
> 8  2019-09-18     2019-09-25      2019-09-16
> 9  2019-09-19     2019-09-25      2019-09-16
> 10 2019-09-20     2019-09-25      2019-09-16
> 11 2019-09-21     2019-09-25      2019-09-16
```

**Comment by vspinu** [comment]
You can do this with `round_date` and specify week_start.

**Comment by TimTeaFan** [comment]
@vspinu thanks for pointing this out. Based on this function family possible convenience wrappers could be:

```
next_wday <- function(d, w) {
  
  lubridate::ceiling_date(d, unit=c('week'),  week_start = w - 1)
  
}

last_wday <- function(d, w) {
  
  lubridate::ceiling_date(d-7, unit=c('week'),  week_start = w - 1)
  
}

```

**Comment by vspinu** [comment]
For the second case you better use floor_date, otherwise it won't work for posix objects. Also your week_start - 1 hack doesn't seem natural to me.
