### ISSUE TITLE
add_with_rollback with roll_to_first = TRUE not working

### ISSUE THREAD

**Issue by jonmcalder** [tidyverse/lubridate#796]
When using `add_with_rollback()` with `roll_to_first = TRUE`, it seems the rollback isn't necessarily applied.

---

``` r
lubridate::add_with_rollback(lubridate::ymd("2019-09-27"), months(12), 
    roll_to_first = TRUE)
#> [1] "2020-09-27"
```

<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
lubridate::add_with_rollback(Sys.Date(), lubridate::years(1), 
    roll_to_first = TRUE)
#> [1] "2020-09-27"
```

<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Surely in both of the above cases the result should be "2020-09-01"?

My guess is that `roll <- day(new) < day(e1)` on [line 111](https://github.com/tidyverse/lubridate/blob/master/R/ops-m%2B.r#L111) should maybe instead be `roll <- day(new) <= day(e1)` to suit the cases where exact months or years are added or subtracted, but I'm not sure about the nuances of other possible edge cases.

**Comment by vspinu** [comment]
No. `add_with_rollback` is only useful when you land on non-existing dates. Otherwise it computes as the default `+` or `-` operators would work.  It's basically `%m+%` but with more control of what happens when the result is a non-existing date.

```R
> add_with_rollback(ymd("2019-01-31"), months(1), roll_to_first = TRUE)
[1] "2019-03-01"
```

What you want is `date_ceiling` with unit month instead.

**Comment by jonmcalder** [comment]
Ah ok - it wasn't clear to me that the rollback is only applicable to non-existent dates.

My expectation was that `add_with_rollback()` would behave as a combination of `%m+%` and `rollback()`, since both functions have similar names and share the same `roll_to_first` argument.

i.e. `rollback()` always returns either the last or first day of a month

The documentation also does not contain any example usage of `add_with_rollback()`.

Might I suggest extending the `leap %m+% years(1)` example to demonstrate `add_with_rollback()`?

```
leap <- ymd("2012-02-29")

leap %m+% years(1)
leap %m+% years(-1)
leap %m-% years(1)

add_with_rollback(leap, years(1), roll_to_first = TRUE)
```
