### ISSUE TITLE
More robust format handling in ymd_hms()

### ISSUE THREAD

**Issue by EricGoldsmith** [tidyverse/lubridate#797]
This works as desired:
```
> tmp <- as.POSIXct("2019-09-01 01:00:00")
> attributes(tmp)
$class
[1] "POSIXct" "POSIXt" 

$tzone
[1] ""
> ymd_hms(tmp)
[1] "2019-09-01 01:00:00 UTC"
```
But this fails:
```
> tmp <- as.POSIXct("2019-09-01 00:00:00")
> ymd_hms(tmp)
[1] NA
Warning message:
All formats failed to parse. No formats found.  
```

The failure is presumably because the coercion of `POSIXct` to character string results in omitted hh:mm:ss when it's midnight (i.e. 00:00:00). 

**Background:**
Many database access packages return datetimes as either character strings (e.g. `RMySQL`) or as `POSIXct` but without the tzone attribute set (e.g. `RMariaDB`, `RPostgres`). 

It's common practice in databases to store datetimes in UTC timezone. And the pattern of transforming query results with `ymd_hms()` is a simple way to a) convert to `POSIXct` type if character string, and b) assign UTC timezone (it's the default `tz` argument). 

As `ymd_hms()` is currently implemented, this works in all cases but for a `POSIXct` type and a time of midnight. 

There are two existing *solutions* to this:

```
> ymd_hms(tmp, truncated = 3)
[1] "2019-09-01 UTC"
```
and
```
> ymd_hms(format(tmp, format = "%F %T"))
[1] "2019-09-01 UTC"
```

But both require changes to existing code.

Would prefer that `ymd_hms()` be modified to behave more consistently with input of a `POSIXct` type and a time of midnight.

**Comment by vspinu** [comment]
ymd_hms is a parser and converts its input to character. I think it makes sense to leave posixct as it is though. People can do this inadvertently in their code. 

In any case, in your case `as_datetime` is what you need.

**Comment by EricGoldsmith** [comment]
With a character string input, `as_datetime()` does the expected - sets the `tzone` attribute, without modifying the datetime:

```
> as_datetime("2019-09-01 00:00:00")
[1] "2019-09-01 UTC"
```

But, with a `POSIXt` input, `as_datetime()` *converts* from the user's current timezone (EDT, in my case) to UTC - despite the original datetime (e.g. `tmp`) not having the `tzone` attribute set:
```
> tmp <- as.POSIXct("2019-09-01 00:00:00")
> as_datetime(tmp)
[1] "2019-09-01 04:00:00 UTC"
```
While I can see an argument for that behavior, it's not what I'm after.

**Comment by vspinu** [comment]
I am not entirely sure what you are after, but relying on your computer time zone is a bad practice (especially if you query the remote database!). The R's default pick-tz-from-the-thin-air practice is an awful idea. 

In any case, UTC or not it's the same time instant. So either use the `tz` explicitly or `with_tz` function. Even if `ymd_hms` could treat the posix without conversion it will respect the `tz` argument as well, which is `UTC` by default.

**Comment by EricGoldsmith** [comment]
Upon further testing, `as_datetime()` does appear to Do The Right Thing™ in response to datetime types returned by database connector packages. Thanks for the tip.
