### ISSUE TITLE
PROBLEM: subtract years and intervals with LEAP YEAR's date

### ISSUE THREAD

**Issue by martinocrippa** [tidyverse/lubridate#798]
Morning,

i've problem in substracting years for leap year date. 
R give me NA if i substract or add 1 years to 2020 - february -29th.

Example:
```r

library("lubridate")
# subsctrac year to leap year date
ymd('2020-02-29') - years(1)
# or
interval(ymd('2017-01-02'), ymd('2020-02-29') - years(1))

```
the only solutions is using the function for imaginary date:
```r

library("lubridate")

ymd('2020-02-29') %m-% years(1)

```
?

thanks in advance
bye
MC

**Comment by vspinu** [comment]
Yes. Unfortunately the original design of period arithmetics is not that most people expect. So your only option for now is to use `%m+%` or `add_with_rollback` functions. I will likely be changing the internals of lubridate by the end of the year and there might be a global user option to configure this behavior.

**Comment by martinocrippa** [comment]
Thank you very much!

Il giorno gio 3 ott 2019 alle 10:23 Vitalie Spinu <notifications@github.com>
ha scritto:
