### ISSUE TITLE
tz function not behaving as expected

### ISSUE THREAD

**Issue by NathanWhitmore** [tidyverse/lubridate#802]
A little issue: in lubridate_1.7.4 the default timezone cannot be changed by the tz function (as per the example in the documentation).  Additionally, contrary to the documentation tz() function default returns "UTC" not "GMT". When a time zone or a format with hours & mutes is  stipulated the function behaves as expected:

```r
library(tidyverse)
library(lubridate) 

## These work:
# ymd_hm("2012-03-26 01:55") 
# ymd("2012-03-26", tz = "Pacific/Fiji")

# But not the documentation example:
x <- ymd("2012-03-26")   

# returns "UTC" not "GMT" as suggested in documentation (not a big deal)
tz(x)       

# try to force change:
tz(x) <- "America/Chicago"

# returns "UTC" not "America/Chicago" as expected
tz(x) 

```

**Comment by vspinu** [comment]
Has to bee fixed indeed.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(lubridate, warn.conflicts = FALSE) 

x <- ymd("2012-03-26")   
tz(x)       
#> [1] "UTC"

tz(x) <- "America/Chicago"
class(x)
#> [1] "Date"
```

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think this is a combination of two exiting issues: #790 and #675
