### ISSUE TITLE
Unexpected output of date with 00:00:00 for hours:min:sec.

### ISSUE THREAD

**Issue by DonBunk** [tidyverse/lubridate#803]
---

ymd_hms() does not give expected output when the hours:min:sec = 00:00:00

```r
ymd_hms("2019-10-18 00:00:00")
```
Yields:  "2019-10-18 UTC". Expected output is "2019-10-18 00:00:00 UTC" as is the case with:

```r
ymd_hms("2019-10-18 00:00:01")
```
Yields: "2019-10-18 00:00:01 UTC"

**Comment by vspinu** [comment]
Sorry for being late on this. 

This is how R prints round date-times. You can distinguish POSIXct and Date by the time zone string UTC

```R
> ymd_hms("2019-10-18 00:00:00")
[1] "2019-10-18 UTC"
> ymd("2019-10-18")
[1] "2019-10-18"
> 
```
