### ISSUE TITLE
Incorrect rounding of new-year dates before 1971

### ISSUE THREAD

**Issue by fuleky** [tidyverse/lubridate#804]
For years before 1971, the round_date function produces an incorrect date for time 00:00:00 on new-year day. Once the time is nudged away from 00:00:00 on 01/01, the rounding seems to produce the correct result.

```r
library(lubridate)
  as.numeric(1958-1/12) %>% date_decimal() %>% round_date(unit = "month") # produces "1958-12-01 UTC"
  as.numeric(1958) %>% date_decimal() %>% round_date(unit = "month") # produces "1957-02-01 UTC" which is INCORRECT
  as.numeric(1958+0.0001) %>% date_decimal() %>% round_date(unit = "months")  # produces "1958-01-01 UTC"
  as.numeric(1958+1/12) %>% date_decimal() %>% round_date(unit = "month") # produces "1958-02-01 UTC"

```

**Comment by vspinu** [comment]
This is no longer there in the development version, could you please try?

**Comment by hadley** [comment]
I still see the problem in the dev version, but it is fixed in timechange:

``` r
library(lubridate, warn.conflicts = FALSE)

x <- make_datetime(year = 1958)
x
#> [1] "1958-01-01 UTC"

round_date(x, unit = "month")
#> [1] "1957-02-01 UTC"
timechange::time_round(x, "month")
#> [1] "1958-01-01 UTC"
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
@hadley @fuleky Both of you are on Mac right? I bet this has to do with the fact that as.POSIXlt doesn't work correctly for dates < 1970 on Mac.

**Comment by fuleky** [comment]
Yes, Mac.

**Comment by vspinu** [comment]
Related #769

**Comment by DavisVaughan** [comment]
Works with clock's month grouping

``` r
library(clock)

x <- date_time_parse("1958-01-01 00:00:00", "UTC")

date_group(x, "month")
#> [1] "1958-01-01 UTC"
```

**Comment by vspinu** [comment]
Fixed in devel
