### ISSUE TITLE
ceiling_date(, "day") doesnt round to next day at midnight

### ISSUE THREAD

**Issue by skr5k** [tidyverse/lubridate#806]
Hey,

Running
`ceiling_date(ymd_hms("2019-10-29 00:00:01", tz="Europe/Berlin"), "day")`
returns  `"2019-10-30 CET"` which is what I expect.

But running
`ceiling_date(ymd_hms("2019-10-29 00:00:00", tz="Europe/Berlin"), "day")`
returns  `"2019-10-29 CET"`. 

I would have expected that exactly midnight is the beginning of the day and that ceiling-rounding that to "day" should result in the end of the day, i.e. 2019-10-30 CET, shouldn't it?

Thanks!
skr5k

**Comment by vspinu** [comment]
That is by design/historical. You need `change_on_boundary` argument:

```R
> ceiling_date(ymd_hms("2019-10-29 00:00:00", tz="Europe/Berlin"), "day", change_on_boundary = T)
[1] "2019-10-30 CET"
```
