### ISSUE TITLE
Feature request: `int_overlaps` returning a numeric (amount), not a logical (boolean)

### ISSUE THREAD

**Issue by brianwdavis** [tidyverse/lubridate#807]
Based on a [StackOverflow question](https://stackoverflow.com/questions/58517015/lubridate-find-overlap-time-between-interval-and-a-date), it seems like there should be a function that returns the **amount** of overlap, not just a logical for overlap. Like so:

```r
int_overlaps_numeric <- function (int1, int2) {
  stopifnot(c(is.interval(int1), is.interval(int2)))

  x <- intersect(int1, int2)@.Data
  x[is.na(x)] <- 0
  as.duration(x)
}

# Examples:
int1 <- as.interval(5, Sys.time())
int2 <- as.interval(5, Sys.time()+3)
int3 <- as.interval(5, Sys.time()+1000)

int_overlaps(int1, int2)
> [1] TRUE

int_overlaps_numeric(int1, int2)
> [1] "1.99399495124817s"

int_overlaps(int1, int3)
> [1] FALSE

int_overlaps_numeric(int1, int3)
> [1] "0s"
```

This can still be used in the same code as the current `int_overlaps`, since `as.logical(as.duration(30))` evaluates to `TRUE` and `as.logical(as.duration(0))` evaluates to `FALSE`.

**Comment by brianwdavis** [comment]
The breaking case for this is when two intervals share an endpoint:

```r
int1 <- as.interval(5, ymd_hms("2019-10-30 12:47:00"))
int2 <- as.interval(5, ymd_hms("2019-10-30 12:47:05"))

int_overlaps(int1, int2)
> [1] TRUE
int_overlaps_numeric(int1, int2)
> [1] "0s"
```

But I would argue they don't actually overlap, since it's instantaneous, so I think the current behavior is misleading.

**Comment by hadley** [comment]
Isn't this just `as.duration()` + `intersect()`? 

``` r
library(lubridate, warn.conflicts = FALSE)

int1 <- as.interval(today() + minutes(5), today() + minutes(8))
int2 <- as.interval(today() + minutes(10), today() + minutes(20))
as.duration(intersect(int1, int2))
#> [1] NA

int3 <- as.interval(today() + minutes(8), today() + minutes(12))
as.duration(intersect(int1, int3))
#> [1] "0s"
as.duration(intersect(int2, int3))
#> [1] "120s (~2 minutes)"
```

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brianwdavis** [comment]
Essentially yes, so that's why my example is short. The only added behavior is checking if there's no overlap, where it's set to zero instead of `NA`. 

It just seems to me that the use case of wanting to know the extent of overlap is more prevalent than wanting to know yes/no. You could even make the argument that the added behavior is wrong (in which case the proposed `int_overlaps` would just be `as.duration(intersect(x, y))`), and it should be the following three cases:

Case | `int_overlaps` Output | proposed Output 
----|----|----
Overlaps unambiguously | `TRUE` | numeric amount
Overlaps only at endpoint | `TRUE` | 0
No overlap at all | `FALSE` | `NA` or 0
