### ISSUE TITLE
class Date introduces unexpected forced timezone change

### ISSUE THREAD

**Issue by NanisTe** [tidyverse/lubridate#809]
When creating a Date object from a POSIXct in a specific timezone and convert back the Date object to the same timezone the output of the POSIXct is not equal the POSIXct given as input.

```r
as.POSIXct(date(as.POSIXct("2015-01-01 00:00:00","Europe/Zurich")),"Europe/Zurich")
```
Result is:
```
> as.POSIXct(date(as.POSIXct("2015-01-01 00:00:00","Europe/Zurich")),"Europe/Zurich")
[1] "2015-01-01 01:00:00 CET"
```
Expectations are
```
> as.POSIXct(date(as.POSIXct("2015-01-01 00:00:00","Europe/Zurich")),"Europe/Zurich")
[1] "2015-01-01 00:00:00 CET"
```

**Comment by hadley** [comment]
You appear to be only using base R functions, not lubridate functions.
