### ISSUE TITLE
Improve localisation support

### ISSUE THREAD

**Issue by hadley** [tidyverse/lubridate#815]
Like `readr::locale()`, it would be nice to be able to supply local words for days of week, days of year, and am/pm.

**Comment by hadley** [comment]
Hmm I'm not sure I actually understand what's the common problem with these two issues. Maybe it's just that it's currently mediated by env vars or the `locale`, and you can't explicitly supply a  list of values?

**Comment by vspinu** [comment]
All parsing and stamp functions have locale arguments. 

The first issue is a limitation of `strptime` which doesn't parse `Y-m` strings, the second I have no idea and still have to replicate. 

If I understand correctly you want to be able to:

  - return localized names in accessors (`month`, `wday`)
  - allow localized names in (`month<-`, `wday<-`). 

If so then the other two issues are quite unrelated.

**Comment by hadley** [comment]
Yeah, I think I was confused when I opened this issue and it can just be closed.
