### ISSUE TITLE
Failed to parse months in French on macOS

### ISSUE THREAD

**Issue by martinjeanphd** [tidyverse/lubridate#830]
The following command works on Windows but not on macOS:

my_date <- ymd("2019-AOÛT-09")

The results should be 2019-08-09. On macOS, the object "my_date" is empty and the following warning is shown:

"All formats failed to parse. No formats found."

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by cderv** [comment]
Hi, 

did you check the locale ? 
It works on windows with default locale but it may be not the same on MacOS. 

Could you try this ? 
```r
lubridate::ymd("2019-AOÛT-09", locale = "French_France.1252")
```

**Comment by martinjeanphd** [comment]
Hi,

Thank you for your suggestion. With this, I found that there was a problem with RStudio instead of lubridate. I fixed it with the following command:

`system('defaults write org.R-project.R force.LANG fr_CA.UTF-8')`

**Comment by cderv** [comment]
Good to know. I did not know you would need to do that on mac
https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#Internationalization-of-the-R_002eapp
