### ISSUE TITLE
changing hour, minute or second of date should yield POSIXct

### ISSUE THREAD

**Issue by keesdeschepper** [tidyverse/lubridate#831]
See https://github.com/tidyverse/lubridate/issues/732#issuecomment-558321821.
Changing hour, minute or second of date now yields POSIXlt:
```r
class(as_date(0) + hours(1))
#> "POSIXlt" "POSIXt" 
```
POSIXct is the preferred class for datetimes, though (cf. `as_datetime`). Moreover, POSIXlt does not allow for infinity, leading to bugs like: 
```r
as.numeric(as_date(c(0, Inf)))
#> 0 Inf
as.numeric(as_date(c(0, Inf)) + hours(1))
#> 3600   NA
```

**Comment by vspinu** [comment]
This will be handled automatically by transitioning the arithmetics on top of the `timechange` package.
