### ISSUE TITLE
conversion between decimal_date and date_decimal yields 1 sec offset

### ISSUE THREAD

**Issue by chrisdane** [tidyverse/lubridate#833]
I dont know if the functions `decimal_date` and `date_decimal` are meant to work in both directions. However, there is a 1 second offset at some dates which I consider as wrong:
```r
(posixct1 <- structure(c(-686534400, -683942400), .Dim = 2L, class = c("POSIXct", 
"POSIXt"), tzone = "UTC"))
# "1948-03-31 UTC" "1948-04-30 UTC"
(decimal <- decimal_date(posixct1))
# 1948.246 1948.328
(posixct2 <- date_decimal(decimal, tz="UTC"))
# "1948-03-31 00:00:00 UTC" "1948-04-29 23:59:59 UTC" 2nd is wrong by 1 sec
```
A [similar problem](https://stackoverflow.com/questions/55511606/problems-with-date-decimal) was reported at SO but not solved afaik.

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example using the [reprex](http://reprex.tidyverse.org) package? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never made a minimal reprex before, there is lots of good advice [here](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).

**Comment by chrisdane** [comment]
Sure! (the `reprex` result is quasi the same as my initial post):
```
(posixct1 <- structure(c(-686534400, -683942400), .Dim = 2L, class = c("POSIXct", 
"POSIXt"), tzone = "UTC"))
#> [1] "1948-03-31 UTC" "1948-04-30 UTC"
(decimal <- lubridate::decimal_date(posixct1))
#> [1] 1948.246 1948.328
(posixct2 <- lubridate::date_decimal(decimal, tz="UTC")) # the 2nd is wrong
#> [1] "1948-03-31 00:00:00 UTC" "1948-04-29 23:59:59 UTC"
```

**Comment by vspinu** [comment]
This is a result of inaccurate math on double numbers and an incomplete POSIXct printer in R. The differential is not 1 second, but a much smaller fraction.

```R
options(digits.secs = 6)
> posixct2
[1] "1948-03-31 00:00:00.000001 UTC" "1948-04-29 23:59:59.999999 UTC"

> num2 <- as.numeric(posixct2)
> num2
[1] -686534400 -683942400
> num2 - round(num2)
[1]  1.549720764e-06 -3.576278687e-07
```

For this reason you cannot get a perfect round-trip with `date_decimal` and `decimal_date`.
