### ISSUE TITLE
Non-finite dates plus seconds / minutes / hours should yield datetime

### ISSUE THREAD

**Issue by keesdeschepper** [tidyverse/lubridate#834]
See https://github.com/tidyverse/lubridate/pull/828#discussion_r350776035. 
A non-finite date plus e.g. seconds now yields an object of class Date:
```r
class(as_date(NA) + seconds(1))
#> "Date"
```
It makes more sense if this yields an object of class POSIXct.

**Comment by vspinu** [comment]
This is internally the same as #831 , but ok.

**Comment by vspinu** [comment]
forgot to close this one
