### ISSUE TITLE
Get rid of intermediate page for making issues

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/lubridate#837]
@vspinu, I'm turning this into an issue (which, of course, meant I went through the intermediate page, ironically) to keep better track of it!

Per comment [here](https://github.com/tidyverse/lubridate/commit/208c8700e00cf651c99ce3d743f463bf9a60af0f#commitcomment-36184403)
> Do you know how to disable intermediate question-page with one option which creps between the user pressing [New Issue] button and the actual issue page? I find this intermediate page useless and slightly annoying. Thanks.

Goal is to get rid of the page that automatically appears when you go to create a new issue (see below).

![image](https://user-images.githubusercontent.com/831732/69872785-6d7b4680-1284-11ea-9e54-2267f594fa08.png)

Currently, you can create a blank issue by clicking on the <ins>Open a blank issue</ins> in the interface above, but you do need to go through that step.

Temporary fix would be to just get rid of the issue template (introduced in https://github.com/tidyverse/lubridate/commit/208c8700e00cf651c99ce3d743f463bf9a60af0f) entirely. 

Looking at GitHub's ["Configuring issue templates for your repository"](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) and ["About issue and pull request templates"](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates), it doesn't seem like there's currently a way to have the issue templates available without forcing the choosing interface.

**Comment by batpigandme** [comment]
@hadley, I can certainly submit a PR removing the issue template. 

I haven't found anything native to GitHub's community settings that would let the issue template be conditional (e.g. like the Code of Conduct is for first-time issue-openers/contributors).

I could also look into creating a button from the README that would create an issue _using_ a template for those who want it. There might be a GH action that allows something more elaborate (have yet to find one).

**Comment by vspinu** [comment]
I think this has to do with the `ISSUE_TEMPLATE` folder. If you just make it `ISSUE_TEMPLATE.md` the problem will be solved. Try [this repo](https://github.com/clojure-emacs/clojure-mode/tree/master/.github) for example.
