### ISSUE TITLE
Feature request: fail-noisy equivalents of `make_date`, `as_datetime`, etc.

### ISSUE THREAD

**Issue by Kodiologist** [tidyverse/lubridate#839]
Functions that return `NA` for invalid input like `2007-13-01` or `2007-02-29`, rather than raising an error, and don't even print a warning, feel dangerous to me. I need to remember to check for `NA`s every time or I could create a hard-to-find bug.

**Comment by Kodiologist** [comment]
Clarification: I got a little confused with respect to `as_datetime` and `as_date`. These do print warnings for invalid input, but in that way they differ from `as.Date` and `as.POSIXct`, which raise errors instead. This is not documented, although `as_datetime` and `as_date` are described as "drop-in replacements".

**Comment by vspinu** [comment]
What is easier to check for NAs or to figure out which element in a 1mil vector produced "character string is not in a standard unambiguous format"? In practice you often don't care about a few wrong time-stamps in the data, so NAs are generally useful. 

You are right, they are not "drop-in replacemnents", but that's too late to change and as said above, wouldn't be that useful. We can add a note in the docs. Also `make_date` and `make_datetime` should probably warn.

**Comment by Kodiologist** [comment]
> We can add a note in the docs. Also `make_date` and `make_datetime` should probably warn.

I think that'll suffice, actually.

If base R were sane, it would tell you the index of the offending value, but no sane person has ever accused base R of being sane.

**Comment by brunj7** [comment]
@Kodiologist @vspinu  I am looking at this issue for tidy-dev-day. Could you provide an example of `make_date` or `make_datetime` generating warnings? thx!

**Comment by Kodiologist** [comment]
@brunj7 The problem is that they don't: something like `make_datetime(2013, 2, 40)` ought to produce a warning or error, but it returns 2013-03-12 without complaint, which is even worse than returning `NA`.
