### ISSUE TITLE
There is no daylight saving time in Brazil anymore

### ISSUE THREAD

**Issue by nnsdtr** [tidyverse/lubridate#842]
Hello,

I've noticed a minor problem with the `"America/Sao_Paulo"` time zone.  There is no daylight saving time in Brazil anymore. Could you please change this?

Example:
```
> library(lubridate)

> ymd_hms('2019-04-28 11:05:13', tz = 'America/Sao_Paulo')
[1] "2019-04-28 11:05:13 -03"

> ymd_hms('2019-12-04 16:01:00', tz = 'America/Sao_Paulo')
[1] "2019-12-04 16:01:00 -02"

```

**Comment by hadley** [comment]
This data comes from the "zoneinfo" database provided by your operating system, so unfortunately it's out of scope for lubridate.

**Comment by nnsdtr** [comment]
Thanks for the info, Hadley.
