### ISSUE TITLE
'UTC' equality can be extended to other equivalent time zones

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/lubridate#844]
I just filed this at `data.table`: https://github.com/Rdatatable/data.table/pull/4117

And this fix for base R: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17674

I notice also several usages of `== 'UTC'` or `!= 'UTC'` in `lubridate`:

```
lubridate/R/parse.r:679:    if (tz == "UTC"){
lubridate/R/parse.r:703:    if (tz == "UTC") {
lubridate/R/parse.r:759:    if (tz != "UTC") {
lubridate/R/parse.r:802:      if (tz != "UTC"){
lubridate/R/stamp.r:110:          if (tz(x[[1]]) != "UTC")
lubridate/R/util.r:119:  if (tz == "UTC") utc
lubridate/R/POSIXt.r:35:  t0 <-if (tz == "UTC") origin else force_tz(origin, tz)
```

If you're amenable, I would file a PR to an equivalent `is_utc` internal utility & replace the above instances

**Comment by vspinu** [comment]
Yes, please.
