### ISSUE TITLE
parse_date_time 0.001 millisecond difference

### ISSUE THREAD

**Issue by ssh352** [tidyverse/lubridate#847]
<img width="540" alt="Screen Shot 2019-12-30 at 5 25 01 PM" src="https://user-images.githubusercontent.com/41779116/71575839-66688200-2b29-11ea-876e-4169a75a9d8e.png">

.333 is stored however 0.332 is displayed. Is this an issue with lubridate?

**Comment by vspinu** [comment]
It's a [printing issue in R](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17350).
