### ISSUE TITLE
Feature request: create interval from midpoint and duration padding

### ISSUE THREAD

**Issue by peterchristofferholm** [tidyverse/lubridate#848]
I'm often creating intervals using an index timepoint +/- a given duration as the respective endpoints. I was wondering if it would make sense to include something like this:

```r
int_width <- function(mid, num, units){
    pad <- duration(num, units)
    interval(mid - pad, mid + pad)
}
```

I'm not all to certain about the name. Maybe `time_pad` or something?

**Comment by vspinu** [comment]
Thanks for the proposal. But I think this is too specific. I have never needed this myself. It's also very easy to handle on the user end.
