### ISSUE TITLE
hms - omits hours 

### ISSUE THREAD

**Issue by FSantosCodes** [tidyverse/lubridate#849]
Dear developers,

I am using the function hms() to transform a string into hours, minutes and seconds. However, it omits the hours when data do not complete an hour, e.g.:
> hms("00:46:02")
[1] "46M 2S"
and I speck to have something like this:
00:46:02
this could be a potential problem because if you require to put these result into a string, merging later with a date and then putting back into a datetime object it will fail to parse, e.g..:
as_datetime(paste0("2019-08-21 ",as.character(hms("00:46:02"))))
[1] NA
Warning message:
All formats failed to parse. No formats found. 

Hope I can explain myself. Thanks for your attention.

Best,

Fabián.

**Comment by peterchristofferholm** [comment]
The "missing" hour is not really missing. If you try calling `str()` on the output of the `hms` call, you will see that the hour information is only absent from the string representation. 

```
str(hms("00:46:02"))
#> Formal class 'Period' [package "lubridate"] with 6 slots
#>   ..@ .Data : num 2
#>   ..@ year  : num 0
#>   ..@ month : num 0
#>   ..@ day   : num 0
#>   ..@ hour  : num 0
#>   ..@ minute: num 46
```
If you to combine this with a date to produce a datetime object, you can just add them like this:

```
ymd("2019-08-21") + hms("00:46:02")
#> [1] "2019-08-21 00:46:02 UTC"
```

**Comment by FSantosCodes** [comment]
I see, thanks for the reply. In this case, please delete this issue as is not really an "issue" but maybe this example in the vignette could improve understanding of lubridate.  Best.
