### ISSUE TITLE
Prepare for the release 1.7.8

### ISSUE THREAD

**Issue by vspinu** [tidyverse/lubridate#865]
Prepare for the release:
 - [x] Fix all milestone issues
 - [x] `devtools::check()`
-  [x] Change version (no-commit!)
 - [x] `devtools::check_win_devel()`
 - [x] `devtools::check_win_release()`
 - [x] `rhub::check_for_cran()`
 - [x] `rhub::check_for_cran(check_args = c('--no-stop-on-test-error'), platforms = 'solaris-x86-patched')`
 - [x] `revdepcheck::revdep_check(num_workers = 8)`
 - [x] Polish NEWS
 - [x] Polish pkgdown reference index
 - [x] Update dependencies
 - [x] Check revdeps
 - [x] Email reverse dependencies not to use it

Submit to CRAN:

 - [x] `usethis::use_version('minor')`
 - [x] Update `cran-comments.md`
 - [x] `devtools::submit_cran()`
 - [x] Approve email

Wait for CRAN...

 - [x] Accepted!!!!
 - [x] `usethis::use_github_release()`
 - [x] `usethis::use_dev_version()`

**Comment by hadley** [comment]
Could we please try and get #717 included in this release? @jimhester should be able to take a look in the next day or two

**Comment by vspinu** [comment]
Sure. I actually plan for another release in a month or two just for re-basing on `timechange`, so if it cannot be done now (within a week or so) it's not a big deal.
