### ISSUE TITLE
wday week_start documentation is incorrect or unituitive

### ISSUE THREAD

**Issue by estern95** [tidyverse/lubridate#866]
It looks like the documentation for week_start within `wday` is inaccurate or very unclear. Here is the doc string:
```
week_start: day on which week starts following ISO conventions - 1 means Monday, 7 means Sunday (default). You can set lubridate.week.start option to control this parameter globally.
```
However, when I put in the date, I get a different result than what the doc string would have me believe:

```r
Sys.setenv(TZ='UTC')

example_date = "2020-03-09"
lubridate::wday(example_date)
#> [1] 2
lubridate::wday(example_date, label = T)
#> [1] Mon
#> Levels: Sun < Mon < Tue < Wed < Thu < Fri < Sat
```

**Comment by vspinu** [comment]
If week starts on sunday then wday for Monday is 2, if it starts on monday, then it's 1. I don't see what exactly is unclear in the doc string. Do you have a concrete proposal?

```R
> wday("2020-03-09", week_start = 1)
[1] 1
> wday("2020-03-09", week_start = 1, label = T)
[1] Mon
Levels: Mon < Tue < Wed < Thu < Fri < Sat < Sun
```

**Comment by estern95** [comment]
I think the part that confused me and several colleagues was the `1 means Monday, 7 means Sunday (default)`. This initially led me to think that Monday would be level one in the factor levels.

**Comment by asadow** [comment]
> I think the part that confused me and several colleagues was the `1 means Monday, 7 means Sunday (default)`. This initially led me to think that Monday would be level one in the factor levels by default .

This exact confusion happened to me as well years ago. Today I still find the description confusing.
