### ISSUE TITLE
[Feature Request] add option "quarter" to period()

### ISSUE THREAD

**Issue by courtwarr** [tidyverse/lubridate#873]
Quarter seems to have its own function but is neglected in period(). A workaround is simple enough but inclusion in the library would be nice. Specifically, I have a Shiny app where the user dynamically assigns the date grouping units, For this use case, period() works nicely because I can feed the user input into a single function. Ie Sys.Date() + period(1,units=input$dateGroup)

```r
library(lubridate)

Sys.Date() + month(1)
Sys.Date() + period(1,"month")#should return equivalent

Sys.Date() + quarter(1)
Sys.Date() + period(1,"quarter")#should return equivalent
```

for me, the above code returns:
Error: Invalid unit name: quarter

**Comment by vspinu** [comment]
What about `period(months = 3)` instead? 

The problem with quarter is that it's not one of internal units used to represent the period object. I will have to see the code in order to judge if this is worth it. I expect it should be straightforward but one never knows.

**Comment by mdancho84** [comment]
I second this. The `quarter` functionality will definitely help with intuitive business calculations.

**Comment by hadley** [comment]
Given how easy it is to convert between quarters and months, I don't think it's worth adding this the period constructor. It would also suggest that `quarter` is a fundamental component of the `period` object, which it is not.

**Comment by vspinu** [comment]
I agree with @hadley. Let's not do this.
