### ISSUE TITLE
Eliminate stringr dependency

### ISSUE THREAD

**Issue by hadley** [tidyverse/lubridate#874]
Because stringr is quite a heavy dependency (due to its use of stringri). I'm not sure how much work this is, but it'd be worth at least looking into.

**Comment by vspinu** [comment]
This has been done more than a year ago :) 122080d
There is only Rcpp which we depend on and that will go once I move on top of timechange.

**Comment by hadley** [comment]
Oh sweet, sorry for not checking the dev DESCRIPTION!
