### ISSUE TITLE
Should hms follow parse_date_time behavior with as.character?

### ISSUE THREAD

**Issue by andresimi** [tidyverse/lubridate#876]
I see that hms() has different behavior than the  parse_date_time().

 Why this works:
``` r
library(dplyr); library(lubridate)

"09:05:30" %>% parse_date_time("HMS") %>% as.character("%H:%M")
#> [1] "09:05"
```

And this no?
``` r
"09:05:30" %>% hms() %>% as.character("%H:%M")
#> [1] "9H 5M 30S"
```
Is it right?
Thanx

<sup>Created on 2020-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
Your problem is with the `as.character`, not `parse_date_time` or `hms`. Those produce two different types, one is POSIXct, the second is period:

```
> str("09:05:30" %>% hms())
Formal class 'Period' [package "lubridate"] with 6 slots
  ..@ .Data : num 30
  ..@ year  : num 0
  ..@ month : num 0
  ..@ day   : num 0
  ..@ hour  : num 9
  ..@ minute: num 5
> str("09:05:30" %>% parse_date_time("HMS"))
 POSIXct[1:1], format: "0-01-01 09:05:30"
```
as.character method for POSIX has foromat argument, the one for period doesn't, this is why you get what you get.
