### ISSUE TITLE
Day and month names in Swedish should be in lowercase

### ISSUE THREAD

**Issue by gkaramanis** [tidyverse/lubridate#877]
When using the locale for Swedish, the day and month names should be in lowercase. For example:
```r
lubridate::wday(as.Date(2:3, origin = "1970-01-01"), label = TRUE, locale = "sv_SE")
```

returns
```r
[1] Lör Sön
Levels: Sön < Mån < Tis < Ons < Tor < Fre < Lör
```

while it should be returning
```r
[1] lör sön
Levels: sön < mån < tis < ons < tor < fre < lör
```

https://blogs.transparent.com/swedish/the-days-of-the-week-in-swedish/

**Comment by vspinu** [comment]
This is how they appear in your system locale. Try `strftime(now(), "%a %A")`. 

Also that article seems to be talking about days and months in the text context, not in day-stamp-cotext. In all other languages that I know they are not capitalized either, only in English. Still, abbreviations in `strftime` are always capitalized. Search for date-time stamps examples in Swedish. I bet they will be capitalized. Your local computer clock ;)

**Comment by gkaramanis** [comment]
I quickly realized that maybe it wasn’t lubricator and meant to close the issue but missed it. 

Thanks for taking the time to explain! ☺️
