### ISSUE TITLE
Unable to install lubridate, ggplot2 in R 3.5.2

### ISSUE THREAD

**Issue by Ismaeelrx2** [tidyverse/lubridate#878]
I am unable to install lubridate in R 3.5.2. Whenever i try to install by writing install.packages("lubridate") or install.packages("ggplot2"), it returns there warnings: "installation of package ‘lubridate’ had non-zero exit status"' and for ggplot2: "installation of package ‘ggplot2’ had non-zero exit status"

I will greatly appreciate your help on this!

Below is what i get when i tried to install lubridate:

> install.packages("lubridate") Installing package into ‘/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5’ (as ‘lib’ is unspecified) trying URL 'https://cran.rstudio.com/src/contrib/lubridate_1.7.8.tar.gz' Content type 'application/x-gzip' length 459456 bytes (448 KB) ================================================== downloaded 448 KB * installing *source* package ‘lubridate’ ... ** package ‘lubridate’ successfully unpacked and MD5 sums checked ** libs g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include -fpic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o In file included from ./cctz/include/civil_time.h:18, from ./cctz/include/time_zone.h:28, from cctz/src/time_zone_fixed.h:20, from cctz/src/time_zone_fixed.cc:15: ./cctz/include/civil_time_detail.h:37: error: expected nested-name-specifier before ‘year_t’ ./cctz/include/civil_time_detail.h:37: error: ‘year_t’ has not been declared ./cctz/include/civil_time_detail.h:37: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:37: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:41: error: expected nested-name-specifier before ‘diff_t’ ./cctz/include/civil_time_detail.h:41: error: ‘diff_t’ has not been declared ./cctz/include/civil_time_detail.h:41: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:41: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:46: error: expected nested-name-specifier before ‘month_t’ ./cctz/include/civil_time_detail.h:46: error: ‘month_t’ has not been declared ./cctz/include/civil_time_detail.h:46: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:46: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:47: error: expected nested-name-specifier before ‘day_t’ ./cctz/include/civil_time_detail.h:47: error: ‘day_t’ has not been declared ./cctz/include/civil_time_detail.h:47: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:47: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:48: error: expected nested-name-specifier before ‘hour_t’ ./cctz/include/civil_time_detail.h:48: error: ‘hour_t’ has not been declared ./cctz/include/civil_time_detail.h:48: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:48: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:49: error: expected nested-name-specifier before ‘minute_t’ ./cctz/include/civil_time_detail.h:49: error: ‘minute_t’ has not been declared ./cctz/include/civil_time_detail.h:49: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:49: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:50: error: expected nested-name-specifier before ‘second_t’ ./cctz/include/civil_time_detail.h:50: error: ‘second_t’ has not been declared ./cctz/include/civil_time_detail.h:50: error: expected ‘;’ before ‘=’ token ./cctz/include/civil_time_detail.h:50: error: expected unqualified-id before ‘=’ token ./cctz/include/civil_time_detail.h:54: error: expected ‘)’ before ‘year’ ./cctz/include/civil_time_detail.h:78: error: ‘cctz::detail::impl::is_leap_year’ declared as an ‘inline’ variable ./cctz/include/civil_time_detail.h:78: error: ‘year_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:78: error: expected ‘,’ or ‘;’ before ‘noexcept’ ./cctz/include/civil_time_detail.h:81: error: ‘cctz::detail::impl::year_index’ declared as an ‘inline’ variable ./cctz/include/civil_time_detail.h:81: error: ‘year_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:81: error: ‘month_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:81: error: initializer expression list treated as compound expression ./cctz/include/civil_time_detail.h:81: error: expected ‘,’ or ‘;’ before ‘noexcept’ ./cctz/include/civil_time_detail.h:84: error: ‘cctz::detail::impl::days_per_century’ declared as an ‘inline’ variable ./cctz/include/civil_time_detail.h:84: error: ‘year_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:84: error: ‘month_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:84: error: initializer expression list treated as compound expression ./cctz/include/civil_time_detail.h:84: error: expected ‘,’ or ‘;’ before ‘noexcept’ ./cctz/include/civil_time_detail.h:88: error: ‘cctz::detail::impl::days_per_4years’ declared as an ‘inline’ variable ./cctz/include/civil_time_detail.h:88: error: ‘year_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:88: error: ‘month_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:88: error: initializer expression list treated as compound expression ./cctz/include/civil_time_detail.h:88: error: expected ‘,’ or ‘;’ before ‘noexcept’ ./cctz/include/civil_time_detail.h:92: error: ‘cctz::detail::impl::days_per_year’ declared as an ‘inline’ variable ./cctz/include/civil_time_detail.h:92: error: ‘year_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:92: error: ‘month_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:92: error: initializer expression list treated as compound expression ./cctz/include/civil_time_detail.h:92: error: expected ‘,’ or ‘;’ before ‘noexcept’ ./cctz/include/civil_time_detail.h:95: error: ‘cctz::detail::impl::days_per_month’ declared as an ‘inline’ variable ./cctz/include/civil_time_detail.h:95: error: ‘year_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:95: error: ‘month_t’ was not declared in this scope ./cctz/include/civil_time_detail.h:95: error: initializer expression list treated as compound expression ./cctz/include/civil_time_detail.h:95: error: expected ‘,’ or ‘;’ before ‘noexcept’ cctz/src/time_zone_fixed.cc:129: error: expected ‘}’ at end of input cctz/src/time_zone_fixed.cc:129: error: expected ‘}’ at end of input cctz/src/time_zone_fixed.cc:129: error: expected ‘}’ at end of input make: *** [cctz/src/time_zone_fixed.o] Error 1 ERROR: compilation failed for package ‘lubridate’ * removing ‘/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5/lubridate’ Warning in install.packages : installation of package ‘lubridate’ had non-zero exit status The downloaded source packages are in ‘/tmp/RtmpH85OCu/downloaded_packages’

Below for ggplot2

> install.packages("ggplot2")   Installing package into ‘/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5’   (as ‘lib’ is unspecified)   also installing the dependencies ‘farver’, ‘scales’       trying URL   'https://cran.rstudio.com/src/contrib/farver_2.0.3.tar.gz'   Content type 'application/x-gzip' length 1279579 bytes (1.2   MB)   ==================================================   downloaded 1.2 MB       trying URL 'https://cran.rstudio.com/src/contrib/scales_1.1.0.tar.gz'   Content type 'application/x-gzip' length 510666 bytes (498 KB)   ==================================================   downloaded 498 KB       trying URL   'https://cran.rstudio.com/src/contrib/ggplot2_3.3.0.tar.gz'   Content type 'application/x-gzip' length 3031461 bytes (2.9   MB)   ==================================================   downloaded 2.9 MB       * installing *source* package ‘farver’ ...   ** package ‘farver’ successfully unpacked and MD5 sums checked   ** libs   g++ -m64 -std=gnu++0x -I"/usr/include/R" -DNDEBUG   -I/usr/local/include   -fpic    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions   -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c   ColorSpace.cpp -o ColorSpace.o   In file included from ColorSpace.cpp:1:   ColorSpace.h:19: error: ISO C++ forbids initialization of   member ‘valid’   ColorSpace.h:19: error: making ‘valid’ static   ColorSpace.h:19: error: ISO C++ forbids in-class initialization   of non-const static member ‘valid’   make: *** [ColorSpace.o] Error 1   ERROR: compilation failed for package ‘farver’   * removing ‘/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5/farver’   Warning in install.packages :     installation of package   ‘farver’ had non-zero exit status   ERROR: dependency ‘farver’ is not available for package   ‘scales’   * removing ‘/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5/scales’   Warning in install.packages :     installation of package   ‘scales’ had non-zero exit status   ERROR: dependency ‘scales’ is not available for package   ‘ggplot2’   * removing ‘/net3/home/iuy/R/x86_64-redhat-linux-gnu-library/3.5/ggplot2’   Warning in install.packages :     installation of package   ‘ggplot2’ had non-zero exit status       The downloaded source packages are in           ‘/tmp/RtmpH85OCu/downloaded_packages’
--

**Comment by vspinu** [comment]
You have a very old gcc which is not supported by many R packages,
including lubridate, and probably ggplot2.

**Comment by vspinu** [comment]
You need gcc with C++11 support. At least version 3.9, ideally higher.

**Comment by caodudu** [comment]
> 

My version of gcc is 4.7.7, but I meet the same error like him. Can you give me some advice?

**Comment by vspinu** [comment]
It's an ancient version of gcc. You need to install more modern gcc. Please search for how to do that on your platform.
