### ISSUE TITLE
[Feature Request]: fiscal date floor

### ISSUE THREAD

**Issue by markrazmandi** [tidyverse/lubridate#880]
This is a great package that I rely on heavily for my job. Thank you all for this.

I work with a lot of fiscal year data for timeseries analysis and forecasting. I use the floor_date functions in my pipelines and have to add wrappers to work with fiscal periods. I have read older issues related to this and was unsure if the below `functionality` --not necessarily the implementation-- would be re-considered as a standard feature in lubridate. Below is optimized for speed on larger datasets, but differs in implementation from what I have seen in the floor_date functions and the update methods.

```r
library(data.table)
library(lubridate)
library(magrittr)
rm(list=ls())

dt <- seq.Date(
  from=as.Date('2016-11-01'),
  to=as.Date('2020-10-31'),
  by='day'
) %>%
  rev() %>%
  rep(6000) %>%
  data.table(ds=.)

# round date variable to fiscal quarter floor-----------------------------------
floorFiscalQuarter <- function(x,fiscal_start=NULL) {
  
  ds <- data.table(ref=seq.Date(min(x)-92,max(x)+92,'day'))
  
  ds[,ds_floor := min(ref),by=quarter(ref,TRUE,fiscal_start)]
  
  x <- ds[match(x,ds$ref)]$ds_floor
  
  return(x)
  
}

# round date variable to unit floor---------------------------------------------
floorDate <- function(x,unit='second',
                      week_start=getOption('lubridate.week.start',7),
                      fiscal_start=1) {
  
  if (unit=='fiscal_quarter' & fiscal_start>1) {
    
    x <- floorFiscalQuarter(x,fiscal_start)
    
  } else {
    
    x <- floor_date(x,unit,week_start)
    
  }
  
  return(x)
  
}

dt[,ds_floor := floorDate(ds,'fiscal_quarter',fiscal_start=11L)]

```
Although I have been programming R for 5-6 years, this is my post on Github; please let me know if there is information I am missing. Thanks!

**Comment by hadley** [comment]
This is out of scope for lubridate. You should consider a package [almanac](https://davisvaughan.github.io/almanac/) instead.

**Comment by markrazmandi** [comment]
> This is out of scope for lubridate. You should consider a package [almanac](https://davisvaughan.github.io/almanac/) instead.

Thanks, Hadley. Will look into it; and thanks for everything you continue to do for the community.
