### ISSUE TITLE
tz() returns "", not "GMT", when there is no time zone

### ISSUE THREAD

**Issue by jennybc** [tidyverse/lubridate#882]
The return value of `tz()`, when no time zone is set, is documented to be "GMT":

> If no tzone attribute exists, `tz` returns "GMT".

However, this does not seem be true. Instead it returns the empty string `""`:

``` r
library(lubridate)

(x <- Sys.time())
#> [1] "2020-04-20 16:21:45 PDT"

dput(x)
#> structure(1587424905.2307, class = c("POSIXct", "POSIXt"))

attr(x, "tzone")
#> NULL

tz(x)
#> [1] ""
```

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

This then causes unexpected behaviour for, e.g., an extractor like `hour()`. I expected to get the hour based on GMT/UTC, but instead I'm getting it for local Pacific time, because `as.POSIXlt(x, tz = tz(x))` falls back to "current time zone" when `tz = ""`.

``` r
hour(x)
#> [1] 16
```

**Comment by hadley** [comment]
Looks like this is already better in the dev docs: https://lubridate.tidyverse.org/reference/tz.html

**Comment by vspinu** [comment]
The doc is fixed so I am closing this. The current behavior is the desired behavior.
