### ISSUE TITLE
with_tz is not working correctly for POSIXlt objects

### ISSUE THREAD

**Issue by btvedt-liquidnet** [tidyverse/lubridate#886]
`with_tz` does not seem to work correctly for `POSIXlt` objects. According to the documentation `with_tz` is not supposed to change the actual moment of time being represented. However, for `POSIXlt` objects it appears to be changing only the time zone.

I believe `with_tz` was working correctly for `POSIXlt` objects in `lubridate` version 1.6.0.

I would expect the following two `with_tz` calls to return the same moment in  time, but they do not. When I run this code using`lubridate` version 1.7.8 there is a difference of 5 hours according to `difftime`.

```r
x <- strptime("2020-04-01 12:34:56", "%Y-%m-%d %H:%M:%OS", tz="UTC")
with_tz(x, "America/New_York")
with_tz(as.POSIXct(x), "America/New_York")
```

**Comment by personlin** [comment]
I encounter the same issue!

**Comment by vspinu** [comment]
This is actually a bug in R itself. Setting tzone attribute on posixlt objects results in a mess :/. 

After [recent simplification](https://github.com/tidyverse/lubridate/commit/f7702c926e92559ae1e11929a8acacb8ac17ef0a) this re-emerged.
