### ISSUE TITLE
Error: 'new_period' is not an exported object from 'namespace:lubridate'

### ISSUE THREAD

**Issue by Rmonkey26** [tidyverse/lubridate#888]
Hello, I have legacy code that relies on an older function new_period from the lubridate package. As an example, it does date adjustments using some along the line of

date <- lubridate::ymd(20200101)

date_adjust <- date - lubridate::new_period(month = 6)

Error: 'new_period' is not an exported object from 'namespace:lubridate'

This is legacy code and now I would now just use period(month = 6) or the wrapper months(6).

However, the legacy code started breaking when I updated my lubridate package to 1.7.8

I am thinking perhaps this new_period has been deprecated, but why has it been removed from the lubridate package? Or this error entirely unique to me.

Thank you in advance.

**Comment by vspinu** [comment]
it was deprecated for many years now. 

`period` is a drop-in replacement. What is the error you are getting. If you post it, we might help.

**Comment by Rmonkey26** [comment]
Error: 'new_period' is not an exported object from 'namespace:lubridate'



This is the error. When I uploaded lubridate, this error started breaking some of my legacy code. Was this deprecated function removed in the new lubridate update?

**Comment by vspinu** [comment]
Yes, it was removed. You can do `new_period <- period` in your legacy code and it should work.

**Comment by beckandthebees** [comment]
Hello,
I'm having a similar issue with `new_interval`. I am trying to run `install_github("azvoleff/teamlucc")`, but am getting the error 
`Error: object 'new_interval' is not exported by 'namespace:lubridate'
Execution halted`
I attempted the strategy of 
`new_interval <- interval
install_github("azvoleff/teamlucc")`
but get the same error.

**Comment by vspinu** [comment]
The code is probably using `lubridate::new_interval`. You would need to contact the maintainer, or provide a PR to fix that.
