### ISSUE TITLE
years and dyears confusion (solution idea)

### ISSUE THREAD

**Issue by euklid321** [tidyverse/lubridate#891]
Referencing https://github.com/tidyverse/lubridate/issues/889  and https://github.com/tidyverse/lubridate/issues/708, I think the current behaviour of lubridate is very confusing at first glance, although everything works as expected.

> library(lubridate)
> a = as.Date("2020-01-01")
> a + years(1)
[1] "2021-01-01"
> a + dyears(1)
[1] "2020-12-31 06:00:00 UTC"
> years(1) == dyears(1)
[1] TRUE

Wouldnt it be easier to add a "year_base = 365.25" (similar for dmonths) option to dyears such that the user can actively decide whether they want a standard year to have a duration of 365 or 365.25 days?
This way users would also be more actively informed about what is happening under the hood.
And for people who are looking for a 365 base, they could use these functions as well.

**Comment by vspinu** [comment]
writing `dyear(x, year_base = 365)` is no better than writing `x*ddays(365)` IMO. I think people using dyear probably need `years` instead in most cases. So the current behavior generates more awareness for the distinction.

**Comment by vspinu** [comment]
I think the workaround is actually easy and cleaner than the extra argument, so I decided to leave it as it is.
