### ISSUE TITLE
Very basic beginner error-Error in as.POSIXlt.character(x, tz, ...) :   character string is not in a standard unambiguous format

### ISSUE THREAD

**Issue by GabriellaS-K** [tidyverse/lubridate#892]
Hi, 

Just started using the lubridate package! Running into the same error again and again. 
I have a StartDate column for a survey, which contains date and time in the format
2020-03-13 16:05:38
However I keep getting the error: 
```
Error in as.POSIXlt.character(x, tz, ...) :
  character string is not in a standard unambiguous format
```
if I check the class of the column:
```
> class(data_raw$StartDate)
[1] "POSIXct" "POSIXt" 
```
so I thought this means R interprets it as a date and time? But then I keep getting the error message. 

Grateful for any help!

**Comment by vspinu** [comment]
you need to provide a reporoucible example. How do you get to that error more concretely?

**Comment by carlosvargas9103** [comment]
data from: https://datahub.io/core/gold-prices

file = "TS_Gold_Dollar_Price.csv"

df_gold_000 <- read.zoo(file, header = TRUE, sep = ",", fill=TRUE, dec=".", colClasses=c("Date", "numeric"), tz = "")
df_gold_00 <- as.xts(df_gold_000)
class(df_gold_00)
head(df_gold_00)
length(df_gold_00)
df_gold_003 <- window(df_gold_00, start='1979-01-01')

tclass(df_gold_003)

df_gold_005 <- apply.monthly(df_gold_003, mean)
length(df_gold_005) # 495
tformat(df_gold_005) <- "%Y-%m-%d"
l_00 <- df_gold_005
length(l_00) # 495

l_0.96_00 <- as.integer(length(l_00)*0.96)
t_dates_00 <- l_00[l_0.96_00,0] # threshold of the dates at the 93% of the observations
t_d_00 <- index(t_dates_00)
# str(t_d)
# class(t_d)

gold_train_00 <- window(df_gold_005, end="2018-12-31")
gold_test_00 <-  window(df_gold_005, start="2018-12-31")

length(gold_train_00) # 8922 # 475 # 480
length(gold_test_00) # 1829 # 21 # 16

ly_train_00 <- log(gold_train_00)

sarima_test_000 <- arima(ly_train_00, order = c(12,1,1), seasonal=list(order=c(1,1,1), period=12))

fore_sarima_test_01 <- forecast(sarima_test_000, 16)

---
Error in try.xts(c(`481` = 7.14858692364586, `482` = 7.15079022887146,  : 
  Error in as.POSIXlt.character(x, tz, ...) :   character string is not in a standard unambiguous format

**Comment by vspinu** [comment]
@carlosvargas9103 AFAICS your example has nothing to do with lubridate. The error that you are seeing is the standard error from R which tells you that the character vector which is used as date-time object cannot be parsed into a date-time. You have to parse it explicitely using lubridate's parsing functions or any other means.
