### ISSUE TITLE
Order of operation matters with interval divisions

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/lubridate#895]
As seen on [StackOverflow](https://stackoverflow.com/a/39864214/3888000), one might want to measure time periods by dividing an interval by a standard time duration.

However, if the user wants to multiply this duration, the order of operations matters when it shouldn't:

``` r
library(lubridate)
x=interval(dmy("01/01/2020"), dmy("01/01/2021"))
(5*x)/years(1)
#> [1] 5.008219
5*(x/years(1))
#> [1] 5
```
<sup>Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To me, the second output makes more sense, but the default output (without any parenthesis) is the first one. The error is relatively weak anyway.

I'm not sure that modifying arithmetic operation order is within `lubridate`'s purview. 

If not, maybe this could be a bit more documented.  In fact, the whole StackOverflow division trick might deserve to be described in the `interval` documentation, along with a notice to use parenthesis if needed.

**Comment by vspinu** [comment]
Multiplication of an interval does not make a lot of sense. It works by converting internally to duration. I might have been a better idea to convert to periods but that's too late to change. 

You can do it yourself:

```r
> x <- as.period(interval(dmy("01/01/2020"), dmy("01/01/2021")))
> x
[1] "1y 0m 0d 0H 0M 0S"
> (5*x)/years(1)
[1] 5
> 5*x/years(1)
[1] 5
```
