### ISSUE TITLE
remove the depreciated `here` function

### ISSUE THREAD

**Issue by FabianRoger** [tidyverse/lubridate#900]
There is a really useful library to construct path in Rprojects called [here](https://github.com/r-lib/here)

The lubridate `here` function is depreciated. 

Given that the there is a [name conflict](https://github.com/r-lib/here/commit/a3ab1d09cdc49e2454e322e9c7444c1720cd0227) would it be possible to remove the here function from lubridate (or if it is required for backwards compatibility)  to not load it automatically in the namespace? 

It would make life with R, lubridate and here (both of which are really useful!) ever so slightly easier :-)

**Comment by vspinu** [comment]
I has been removed in version 1.7.8.
