### ISSUE TITLE
"week_of" for human-readable weeks

### ISSUE THREAD

**Issue by reisner** [tidyverse/lubridate#907]
The `lubridate::week` and `lubridage::isoweek` functions are great for grouping by week, but charts using weeks often use the "week of" for human readability. Most people don't know what month week 29 falls on. 

The existing functionality is:

```
dates = c(lubridate::ymd(20200101), lubridate::ymd(20200108))
> lubridate::isoweek(dates)
[1] 1 2
```

It'd be nice to have something like:

```
> lubridate::isoweek(dates, week_of = TRUE)
[1] "2019-12-30" "2020-01-06"
```

**Comment by vspinu** [comment]
Would `round_date(x, "week")` do?

**Comment by reisner** [comment]
@vspinu I think that would work! Although the `week_start` parameter doesnt seem to change it to what I need:

```
> dates = c(lubridate::ymd(20200101), lubridate::ymd(20200108))
> lubridate::round_date(dates, "weeks", week_start = 1)
[1] "2019-12-29" "2020-01-05"
> lubridate::round_date(dates, "weeks", week_start = 7)
[1] "2019-12-29" "2020-01-05"
```

**Comment by vspinu** [comment]
are you using an old version of lubridate?

**Comment by reisner** [comment]
Apologies for that, I've upgraded and that works now.

**Comment by vspinu** [comment]
no problem
