### ISSUE TITLE
Allow easily changing units on a "difftime" object

### ISSUE THREAD

**Issue by colearendt** [tidyverse/lubridate#913]
In many cases it is useful to alter difftime objects to have different units. The `as.difftime()` function does not do this today, which feels strange.

``` r
(dtime <- lubridate::today() - (lubridate::today() - 60))
#> Time difference of 60 days
lubridate::as.difftime(dtime, units = "month")
#> Time difference of 60 days
```

<sup>Created on 2020-08-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
Agreed, taking units into account would make sense. But this should be a request to R core. It would make it backward incompatible though.  Currently

 `base::as.difftime()` simply returns the object if it's a difftime. 

```R
function (tim, format = "%X", units = "auto", tz = "UTC") 
{
    if (inherits(tim, "difftime")) 
        return(tim)
```


It wouldn't be ok on lubirdate side to overwrite the core function. We define our methods only.
