### ISSUE TITLE
A 'rollforward' function?

### ISSUE THREAD

**Issue by kputschko** [tidyverse/lubridate#914]
I'm looking for a quicker way to roll a date to the end of the given month.  Currently it takes two functions, `ceiling_date` and subtracting `days`.  

```r

library(lubridate)

date_1 <- ymd("2020-01-15")

# rollback is simple and great
rollback(date_1)
rollback(date_1, roll_to_first = TRUE)

# but rolling forward looks a little clunky
ceiling_date(date_1, unit = "month") - days(1)
>"2020-01-31"

# maybe add an option to rollback?
rollback(date_1, roll_to_last = TRUE)
>"2020-01-31"

# or create a new function?
rollforward(date_1)
>"2020-01-31"
```

**Comment by vspinu** [comment]
"faster" as in "type faster" or "faster execution speed"?

I think it makes sense to add it for completeness, as a counterpart of rollback.

**Comment by seasmith** [comment]
```r
rollforward <- function (dates, roll_to_first = FALSE, preserve_hms = TRUE) 
{
  if (length(dates) == 0) 
    return(dates)
  day(dates) <- 1
  if (!preserve_hms) {
    hour(dates) <- 0
    minute(dates) <- 0
    second(dates) <- 0
  }
  if (roll_to_first) {
    dates + months(1)
  }
  else {
    dates + months(1) - days(1)
  }
}
```

**Comment by UweBlock** [comment]
Just saw the new function being mentioned in `News.md`.

For the sake of consistency with `rollback()`, I had expected

```
library(lubridate)

date_1 <- ymd("2020-01-15")

rollback(date_1)
# "2019-12-31" = last day of preceeding month

rollforward(date_1)
# "2020-02-01" = first day of succeeding month
#  equivalent to
ceiling_date(date_1, unit = "month")

rollback(date_1, roll_to_first = TRUE)
# "2020-01-01" = first day of given month

rollforward(date_1, roll_to_last = TRUE)
# "2020-01-31" = last day of given month
```

**Comment by vspinu** [comment]
This is an alternative notion of a symmetry, or probably better `asymetry`. What you propose is the mirror of `rollback`.

The advantage of the current design is that there is no extra argument (`roll_to_last`) and reasoning about the code is simpler because there is one pattern to remember - by default roll to last day, with the argument to first day etc.
