### ISSUE TITLE
quarter(with_year = TRUE) not working

### ISSUE THREAD

**Issue by annalibey** [tidyverse/lubridate#915]
I updated lubridate today, and even tried the github version and still have the same problem with the quarter function:

```
example <- tibble(local_date = ymd("2016-01-01"):today())

example %>%
    arrange(local_date) %>%
    mutate(quarter = quarter(local_date, with_year = TRUE)) %>%
    group_by(quarter)
```
> Error in quarter(local_date, with_year = TRUE) : 
>   unused argument (with_year = TRUE)

**Comment by vspinu** [comment]
At least two problems:

```R
> getAnywhere(quarter)
2 differing objects matching ‘quarter’ were found
in the following places
  package:lubridate
  package:data.table
  namespace:data.table
  namespace:lubridate
Use [] to view one of them
> head(ymd("2016-01-01"):today())
[1] 16801 16802 16803 16804 16805 16806
```

You call `quarter` from another package, and you get numeric `local_date` instead of Date.

**Comment by annalibey** [comment]
Thank you! Should have checked for that.
