### ISSUE TITLE
ymd("2016-05-31") - months(6) returns NA

### ISSUE THREAD

**Issue by kentm4** [tidyverse/lubridate#916]
The following code

```r
ymd("2016-05-31") - months(6)
```

returns `NA`. However, changing to 

```r
ymd("2016-05-31") - months(5)
```

returns `2015-12-31`.

I'm using R version 4.0.2 and lubridate version 1.7.9

**Comment by vspinu** [comment]
Use %m-% or %m+% instead.

**Comment by kentm4** [comment]
Ah, right. Thanks.
