### ISSUE TITLE
Problem with America/Fortaleza timezone

### ISSUE THREAD

**Issue by Rielbe** [tidyverse/lubridate#921]
When calculating the difference of two dates with different timezones, I get an incorrect value for the "America/Fortaleza" timezone, which offset is UTC-3.

``` r
utc_date <- lubridate::ymd_hms("2000-01-01 00:00:00", tz="UTC")
local_date <- lubridate::ymd_hms("2000-01-01 00:00:00", tz="America/Fortaleza")

utc_date - local_date
#> Time difference of -2 hours
```

<sup>Created on 2020-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This should output a time difference of -3 hours. However, I get a time difference of -2.

Afaik, this doesn't happen with any other timezone. For example, with "Europe/Madrid" (UTC+1 at January) I get the expected result:

``` r
utc_date <- lubridate::ymd_hms("2000-01-01 00:00:00", tz="UTC")
local_date <- lubridate::ymd_hms("2000-01-01 00:00:00", tz="Europe/Madrid")

utc_date - local_date
#> Time difference of 1 hours
```

<sup>Created on 2020-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
Time difference is R core functionality. If it's a real issue we cannot do much here. 

But I think the result is expected. -2 h in the winter and -3 h in the summer:

```
> utc_date <- lubridate::ymd_hms("2000-06-01 00:00:00", tz="UTC")
> local_date <- lubridate::ymd_hms("2000-06-01 00:00:00", tz="America/Fortaleza")
> utc_date - local_date
Time difference of -3 hours
```

Or there is no DST in Fortaleza?

**Comment by Rielbe** [comment]
According to several sources I consulted, there isn't DST in that timezone nowadays:

- [time&date](https://www.timeanddate.com/worldclock/brazil/fortaleza)
- [TimeZoneConverter](http://www.timezoneconverter.com/cgi-bin/zoneinfo?tz=America/Fortaleza)
- [zeitverschiebung](https://www.zeitverschiebung.net/en/city/3399415)

At [zeitverschiebung](https://www.zeitverschiebung.net/en/city/3399415) is pointed out that the last DST transition was at February 2002 and there isn't any scheduled transition.
