### ISSUE TITLE
Inconsistent results dividing an interval by a period

### ISSUE THREAD

**Issue by petehobo** [tidyverse/lubridate#926]
I'm using current version of lubridate (1.7.9) from CRAN.

While investigating some code left by a predecessor, I found the following inconsistency:

```r
library(lubridate)
interval(ymd('2019-01-29'), ymd('2019-01-30'))/months(1)  # 0.06451613
interval(ymd('2020-01-29'), ymd('2020-01-30'))/months(1)  # 0.03225806
```

The 2019 figure seems wrong, equating to 2 (/31) days, when it should be 1.

I have a workaround using `time_length()`, which returns consistent results
```r
time_length(interval(ymd('2019-01-29'), ymd('2019-01-30')), 'month')  # 0.03225806
time_length(interval(ymd('2020-01-29'), ymd('2020-01-30')), 'month')  # 0.03225806
```

Perhaps the approach taken by my predecessor is an anti-pattern, but I figured it was worth raising, as it does seem like a bug.

**Comment by petehobo** [comment]
A little more digging shows the difference seems to come from the `adjust_estimate()` function.  In both these cases, the estimate is `0.03285421`, but `adjust_estimate()` returns different values:

```
library(lubridate)

p <- months(1)

i <- interval(ymd('2019-01-29'), ymd('2019-01-30'))
estimate <- i/as.duration(p) # 0.03285421
lubridate:::adjust_estimate(estimate, i, p)

i <- interval(ymd('2020-01-29'), ymd('2020-01-30'))
estimate <- i/as.duration(p) # 0.03285421
lubridate:::adjust_estimate(estimate, i, p)
```

I assume it comes down to leap year/non-leap year differences, but I haven't investigated further.

**Comment by vspinu** [comment]
Thank @petehobo. I am on it. The problem of division by periods is not well defined, but at least in obvious cases like your exampe it should give meaningful results.

**Comment by petehobo** [comment]
Thanks @vspinu .  Yeah, I figured it was messy - that's why I stopped digging where I did...

Thanks for looking into it - lubridate is such a useful library

**Comment by oude-gao** [comment]
I'm experiencing the same issue -- is there a plan to apply a fix? I have been using the division for a long time and just realized the inconsistency today. Am imagining a lot of people are doing the same thing, so if there is a quick fix it would be greatly appreciated! Thanks!!

**Comment by vspinu** [comment]
Thanks guys for reporting and sorry for the delay. Should be fixed now.

**Comment by petehobo** [comment]
Excellent - thanks @vspinu!  Looks good
