### ISSUE TITLE
Conversion from time zone Etc/GMT+1 to GMT

### ISSUE THREAD

**Issue by afinez** [tidyverse/lubridate#927]
As I set a datetime in the ETC/GMT+1 timezone with the clock 01:00, 
```r
(d <- lubridate::ymd_hm("2020/01/01 01:00", tz = "Etc/GMT+1"))
```
--> [1] "2020-01-01 01:00:00 -01"

I would expect this instant expressed in the GMT/UTC time zone to have the clock "00:00". 
```r
lubridate::with_tz(d, tz = "GMT")
```
This is not what I obtain  : 
--> "2020-01-01 02:00:00 GMT"

If I use a similar code using the "Europe/Paris" time zone (which is in GMT+1 in january), I get the correct/expected  answer 
```r
(d <- lubridate::ymd_hm("2020/01/01 01:00", tz = "Europe/Paris"))

```
-->"2020-01-01 01:00:00 CET"
```r
lubridate::with_tz(d, tz = "GMT")
```
-->  "2020-01-01 GMT"
I believed this unexpected behaviour comes from the definition of the GMT+1 timezone (and probably the similar ones GMT +2, +3 etc...) which displays a strange "-01" at the end of the first exemple here above.

**Comment by vspinu** [comment]
tz databases uses the opposite sign to comply with POSIX conventions:

https://en.wikipedia.org/wiki/Tz_database#Area
https://github.com/eggert/tz/blob/2018d/etcetera#L36-L42
