### ISSUE TITLE
as.period fails for grouped data

### ISSUE THREAD

**Issue by julianbarg** [tidyverse/lubridate#930]
as.period fails with a nondescript error when applied to a grouped dataframe.

```r
df <- data.frame(group = c("a","a","b"),
                 p1 = as.Date(c("2020-10-23", "2020-10-24", "2020-10-25")), 
                 p2 = as.Date(c("2020-10-26", "2020-10-27", "2020-10-28")))

#This succeeds
df %>%
  mutate(interval = as.period(interval(start = p1, end = p2)))

# This throws the error message
df %>%
  group_by(group) %>%
  mutate(interval = as.period(interval(start = p1, end = p2)))
```

Error message: 
Error: Problem with `mutate()` input `interval`.
x Internal error in `vec_proxy_assign_opts()`: `proxy` of type `double` incompatible with `value` proxy of type `integer`.
ℹ Input `interval` is `as.period(interval(start = p1, end = p2))`.
ℹ The error occurred in group 2: group = "b".

**Comment by vspinu** [comment]
@DavisVaughan you have added support for vectrs. Is this issue expected?

**Comment by DavisVaughan** [comment]
I think this is a lubridate bug? I think that year/month/day/hour/minute components of a Period object should always be `integer`, and the second component should be `numeric`. But that is not the case. Creating a period object from `as.period()` maintains this property, but creating one from `period()` or a helper like `days()` does not. That causes the problem.

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
library(vctrs)

x <- as.Date("2020-10-25")
interval <- interval(x, x + 1)
period_from_interval <- as.period(interval)

period <- days(3)

get_fields <- function(x) {
  list(
    year = x@year, 
    month = x@month, 
    day = x@day, 
    hour = x@hour, 
    minute = x@minute, 
    second = x@.Data
  )
}

# this feels correct
vapply(get_fields(period_from_interval), class, character(1))
#>      year     month       day      hour    minute    second 
#> "integer" "integer" "integer" "integer" "integer" "numeric"

# this feels wrong?
vapply(get_fields(period), class, character(1))
#>      year     month       day      hour    minute    second 
#> "numeric" "numeric" "numeric" "numeric" "numeric" "numeric"

# the shared empty period object is just created by:
# `delayedAssign("lubridate_shared_empty_period", period())`
vapply(get_fields(lubridate:::lubridate_shared_empty_period), class, character(1))
#>      year     month       day      hour    minute    second 
#> "numeric" "numeric" "numeric" "numeric" "numeric" "numeric"

# we expect the same types as `lubridate_shared_empty_period`, so this errors
vec_c(period_from_interval, period_from_interval)
#> Error: Internal error in `vec_proxy_assign_opts()`: `proxy` of type `double` incompatible with `value` proxy of type `integer`.

# this has the same type as `lubridate_shared_empty_period`, so no error
vec_c(period, period)
#> [1] "3d 0H 0M 0S" "3d 0H 0M 0S"
```

<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Maybe these should be integers (except seconds)
https://github.com/tidyverse/lubridate/blob/b9025e6d5152f9da3857d7ef18f2571d3d861bae/R/periods.r#L449-L450

And day math here might should use `7L`
https://github.com/tidyverse/lubridate/blob/b9025e6d5152f9da3857d7ef18f2571d3d861bae/R/periods.r#L457

An even more robust way to handle this is probably to handle it in the initialization function for Period. Let `validObject()` first do its checks to make sure the values are integer-ish, then after that actually convert the components to integer
https://github.com/tidyverse/lubridate/blob/b9025e6d5152f9da3857d7ef18f2571d3d861bae/R/periods.r#L174
