### ISSUE TITLE
Documentation doesn't explain rounding functions accept a Period for `unit`

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/lubridate#931]
Rounding functions (e.g. `round_date()`) accepts a Period object as `unit` argument, but this usage is not described in <https://lubridate.tidyverse.org/reference/round_date.html>. As `unit` accepts arbitrary strings that can be parsed into period, I guess passing Period objects is a valid usage. Is my understanding correct? If so, may I send a pull request to add some sentences about this to the doc?

    library(lubridate, warn.conflicts = FALSE)

    ceiling_date(today() + 1:7, days(3))
    #> [1] "2020-11-07" "2020-11-07" "2020-11-07" "2020-11-10" "2020-11-10"
    #> [6] "2020-11-10" "2020-11-13"

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
it's actually not an intended usage. It probably works because the unit is converted to character with your `days(3)` being converted into `"3d 0H 0M 0S"` which is parsed as 3 days. Better use "3d" as unit.

**Comment by vspinu** [comment]
I am closing this as I don't see a benefit in explicitly accepting periods as units. It would be confusing I think. Let me know if you have good use case to use periods as unit.

**Comment by yutannihilation** [comment]
Thanks for clarifying. I personally prefer using a typed object rather than a string because

1. we cannot know the string is in an acceptable format (though it's well-documented) without actually executing the function, and
2. the former feels slightly cleaner when I provide the unit programmatically (e.g. `ceiling_date(x, days(i))` rather than `ceiling_date(x, glue("{i}d"))`).

But, probably both are just my preferences, so sticking with strings is fine to me :)

**Comment by vspinu** [comment]
I think your point 2 is a good one. Let's have it as an option.
