### ISSUE TITLE
Result of `sum()` incorrect for Period objects

### ISSUE THREAD

**Issue by petrbouchal** [tidyverse/lubridate#937]
When calling `sum()` on a Period object, the result returned is incorrect (and in any case different from the `sum()` of a Duration or Interval object.) 

``` r
library(tibble)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

df <- tibble(
  start = rep(now(), 3),
  added = c(10, 1000, 10000),
  end = start + dseconds(added),
  t_period = as.period(end - start),
  t_duration = as.duration(end - start),
  t_interval = interval(start, end)
)


sum(df$t_period)
#> [1] 90
sum(df$t_duration)
#> [1] 11010
sum(df$t_interval)
#> [1] 11010

df$t_period
#> [1] "10S"        "16M 40S"    "2H 46M 40S"

sum(df$t_period[1])
#> [1] 10
sum(df$t_period[2])
#> [1] 40
sum(df$t_period[3])
#> [1] 40
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The `sum()` method seems to be taking in the `.Data` slot in the object, which only contains the seconds element of the period.

**Comment by vspinu** [comment]
`sum` is not a generic unfortunately. I am not sure we want to mess with that. I am opening a discussion on generics package tracker. Let's see what other people think about this.

**Comment by vspinu** [comment]
Closing in favor of the more general #918 . Will implement this soonish.

**Comment by vspinu** [comment]
Actually a true duplicate is #902
