### ISSUE TITLE
The documentation of timezone handling in `as_date` is confusing

### ISSUE THREAD

**Issue by Kodiologist** [tidyverse/lubridate#940]
The documentation for `as_date` says "`as_date()` ignores the timezone attribute, resulting in a more intuitive conversion (see examples)". But unless I'm missing something, the opposite is true: `as_date` uses the `tzone` attribute, producing the same date that's encoded in a timezoned `POSIXct` object, whereas `as.Date` ignores `tzone`. The example shown on the same page is:

```
dt_europe <- ymd_hms("2010-08-03 00:50:50", tz="Europe/London")
c(as_date(dt_europe), as.Date(dt_europe))
#> [1] "2010-08-03" "2010-08-02"```

**Comment by vspinu** [comment]
It all depends how you interpret "ignores". In case of lubridate's doc it means "don't look at the TZ and use local time to decide the date". In other words "2010-08-03 00:50:50 Europe/London" -> "2020-08-03 00:50:50" -> "2020-08-03". 

In this regard `as.Date` does not ignore the TZ because it essentially converts to UTC and then looks at the date.

**Comment by Kodiologist** [comment]
When you say "use local time", do you mean the machine's local time? So the result of  `as_date(ymd_hms("2010-08-03 00:50:50", tz="Europe/London"))` depends on your system's time zone, instead of always being equivalent to `as_date("2010-08-03")`?

**Comment by vspinu** [comment]
No, by local time I meant "clock time" the time that you see on your local clock. That is, just numbers - `2010-08-03 00:50:50`.

**Comment by Kodiologist** [comment]
Okay, well, I'm sure I'm not the only one who finds this confusing, so a sentence or two of explicit description of how time zones are handled could be helpful.

**Comment by vspinu** [comment]
I am not even sure how you can interpret that differently. Can you elaborate what you understood precisely? 

If you have a concrete wording that would make it clearer to you, I would be more than happy to add it to the docs.

**Comment by Kodiologist** [comment]
I'm not sure I understand it correctly, but presuming I do, here's how I'd describe it:

> Called on a `POSIXct` object, `as_date` uses the `tzone` attribute of the object to return the same date indicated by the printed representation of the object. This differs from `as.Date`, which ignores the attribute and uses only the `tz` argument to `as.Date` ("UTC" by default).

**Comment by vspinu** [comment]
Ok, this is another interpretation indeed. I like your wording. Adding with minor edits. Thanks!
