### ISSUE TITLE
Feature request: option to use "Z" tz label in format_ISO8601() output

### ISSUE THREAD

**Issue by francisbarton** [tidyverse/lubridate#941]
This suggestion references @billdenney 's [comment](https://github.com/tidyverse/lubridate/issues/629#issuecomment-407961461) in #629, with the addition of a specific use case.

Bill wrote:
> I didn't do the additional formatting for adding Z instead of -0000 for UTC because that would have added a notable amount more code. I can do it, but the longer-term maintenance didn't seem like it was worthwhile. If you'd like Z, I can make that update.

### Example use case
The Twitter API v2 ([example](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets)) currently only accepts `YYYY-MM-DDTHH:mm:ssZ` format for the `start_time` and `end_time` query parameters. Passing in `YYYY-MM-DDTHH:mm:ss+0000` format results in a HTTP 400 Bad Request error. This makes it incompatible with `lubridate::format_ISO8601()`'s output.

``` r
lubridate::format_ISO8601(
  lubridate::make_datetime(2019),
  usetz = TRUE)
#> [1] "2019-01-01T00:00:00+0000"
```

It's not difficult for me to construct the "Z" format locally within my script and use that, but it would be great if this could be made part of `lubridate`'s capability. Something like:

``` r
# pseudocode
lubridate::format_ISO8601(
  lubridate::make_datetime(2019),
  use_z_format = TRUE)
#> [1] "2019-01-01T00:00:00Z"
```

This option obviously is only appropriate when the `tz` is UTC, or more realistically, where no timezone is stipulated. Would require some thought as to how it would work in cases when a date with a timezone is passed in. Just return an error, I suppose.

I'm happy to work on a PR to try to provide this feature, but I haven't looked into the code yet.

PS I'm adding the inverse feature suggestion on Twitter's API feedback forum - that they should accept all valid ISO8601 datetime formats, but we don't have much control over what they do!

**Comment by billdenney** [comment]
If this were implemented, I would suggest having the `use_z_format` argument cause the datetime to be converted to UTC if it has a time zone or assume UTC if it does not have a time zone.  This can be done using `with_tz()` or `force_tz()`.

**Comment by francisbarton** [comment]
Fully agree,

**Comment by billdenney** [comment]
I don't.  Everything that I have is in the current version of lubridate.

**Comment by billdenney** [comment]
I decided to work on this one.  PR coming shortly...

**Comment by francisbarton** [comment]
That's fantastic, Bill, thanks. I wanted to do this but i don't think i ever would have got round to it!

**Comment by billdenney** [comment]
@francisbarton , I'm procrastinating by making this PR.  :)

**Comment by billdenney** [comment]
@francisbarton , Please take a look and let me know if it does what you'd expect/want.

**Comment by francisbarton** [comment]
@billdenney I'm sorry, I'm in the process of moving between employers at the moment and I haven't got easy access to R and my usual set-up for a while. I will get back to this as soon as I can.
