### ISSUE TITLE
`[[` not implemented for difftime objects

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverse/lubridate#953]
Is this an intentional ommission?

``` r
d <- lubridate::make_difftime(1:3, "second")

d
#> Time differences in secs
#> [1] 1 2 3

# correct
d[1]
#> Time difference of 1 secs

# incorrect
d[[1]]
#> [1] 1
```

<sup>Created on 2021-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I was surprised when I used `dplyr::first` on a `difftime` column that the class was not maintained.  Thanks.

**Comment by vspinu** [comment]
This is difftime which is a base class not lubridate's. It's an omission indeed. It cannot be fixed on lubridate side unfortunately. We are already fixing a number of "omissions"  and it is generally dangerous This change would be backward incompatible with the existing code and code would behave differently with and without lubridate loaded.
