### ISSUE TITLE
floor_date error when used with curly curly rlang

### ISSUE THREAD

**Issue by user63230** [tidyverse/lubridate#959]
When I use curly curly `{{}}` with `floor_date` I run into an apparent bug as mentioned [here ](https://stackoverflow.com/questions/66553753/curly-curly-error-base-operators-are-not-defined-for-quosures/) on SO. 

```
library(tidyverse)
library(rlang)
library(scales)
data1 <- data.frame(date1 = sample(seq(as.Date("2005-01-01"), as.Date('2018-01-01'), by="day"), 5),
                    num1 = 1:5)
data1
hist_date_f <- function(df, date_varaible) {
    df %>%
      group_by(month = floor_date({{date_varaible}}, "month")) %>%
      dplyr::summarize(freq = n()) %>%  
      ggplot(aes(x = month, y = freq)) + 
      geom_bar(stat = "identity") + 
      scale_x_date(labels = date_format("%m-%Y"), 
                   breaks = date_breaks ("1 month")) + 
      theme_bw()
}

hist_date_f(data1, date1)
# Error: Base operators are not defined for quosures.
# Do you need to unquote the quosure?

#   # Bad:
#   myquosure == rhs

#   # Good:
#   !!myquosure == rhs
```

```
sessionInfo()
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     

# other attached packages:
#  [1] scales_1.1.1    rlang_0.4.10    forcats_0.5.0   stringr_1.4.0  
#  [5] dplyr_1.0.3     purrr_0.3.4     readr_1.4.0     tidyr_1.1.2    
#  [9] tibble_3.0.5    ggplot2_3.3.3   tidyverse_1.3.0 tidylog_1.0.2
```
@akrun suggests there is a clash with `lubridate` function `floor_date` because `group_by(month = month({{date_varaible}})) ` works. 

As described on the SO question, the fact that it used to work also suggests that it is a bug.

**Comment by vspinu** [comment]
@user63230 I don't know why `{{` is not working here. As far as I can judge it should work; `!!ensym()` does work here. I think this issue is more appropriate for rlang proper, especially that you claim it used to work before. Could be a bug there. cc @lionel-

**Comment by lionel-** [comment]
This is a bug in dplyr which will be fixed once tidyverse/dplyr#5814 is merged.

**Comment by vspinu** [comment]
Amazing, thanks!

**Comment by user63230** [comment]
thanks!
