### ISSUE TITLE
force_tz returns the second time on a winter DST change

### ISSUE THREAD

**Issue by carissalow** [tidyverse/lubridate#962]
```r
as.numeric(force_tz(lubridate::parse_date_time(paste("2020-11-01", "01:30"), orders = c("Ymd HMS", "Ymd HM")), tzone = "America/New_York"))
```

Returns `1604212200` which corresponds to 2020-11-01 01:30 -0500 instead of -0400. I understand this time is ambiguous as it could point to two moments in time `1604212200` or `1604208600`. I have two questions:

1. Is there a reason why `force_tz` returns the timestamp corresponding to the second 01:30 instead of the first?
2. Is it possible to get `1604208600` from this date-time string? I assume it needs a different time zone?

**Comment by DavisVaughan** [comment]
You are correct that this is an _ambiguous time_. AFAIK, there is no way to return the other moment in time in lubridate.

In clock, this is an error by default, and you have to specify which you want with the `ambiguous` argument.

``` r
library(clock)

date_time_parse("2020-11-01 01:30:00", "America/New_York")
#> Error: Ambiguous time due to daylight saving time at location 1.
#> ℹ Resolve ambiguous time issues by specifying the `ambiguous` argument.

date_time_parse("2020-11-01 01:30:00", "America/New_York", ambiguous = "earliest")
#> [1] "2020-11-01 01:30:00 EDT"

date_time_parse("2020-11-01 01:30:00", "America/New_York", ambiguous = "latest")
#> [1] "2020-11-01 01:30:00 EST"
```

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by vspinu** [comment]
`force_tz` gained new argument to control this behavior `roll_dst`

```R
> dt <- ymd_hm("2020-11-01 01:30")
> force_tz(dt, tzone = "America/New_York", roll_dst = c("NA", "pre"))
[1] "2020-11-01 01:30:00 EDT"
> force_tz(dt, tzone = "America/New_York", roll_dst = c("NA", "post"))
[1] "2020-11-01 01:30:00 EST"
> force_tz(dt, tzone = "America/New_York", roll_dst = c("NA", "boundary"))
[1] "2020-11-01 01:00:00 EST"
> force_tz(dt, tzone = "America/New_York", roll_dst = c("NA", "NA"))
[1] NA
```
