### ISSUE TITLE
goes through without error when using Japanese

### ISSUE THREAD

**Issue by amazongodman** [tidyverse/lubridate#964]
I was trying to see how far lubridate would go in its automatic recognition.

I tried japanese, and I found a behavior that did not result in an error.

When I input numbers in kanji, they are all converted to "2" without any errors.

## kanji to number

一二三四五六七八九
123456789

## Correct conversion(I was suprized)

```r
ymd("2020年/10月/28日")
> "2020-10-28"
```

## error is correct

I tried to tease lubridate.

```r
ymd("二千二十年/1月/28日")
[1] NA
All formats failed to parse. No formats found. 
```

2020-01-28
is correct

## and this is strange.

```r
ymd("2020年/五月/28日")
ymd("2020年-八月-28日")
```

Both will respond with "2020-02-08".
but correct ans is,
2020-05-28
2020-08-28

It goes through without error, is this a problem?

(It would be nice if kanji could be converted to numbers with stringr as a preprocessing step, but I asked this question because I felt it would be nice to improve the automatic recognition feature of lubridate).

R version 4.0.3 (2020-10-10)
lubridate_1.7.9.2

**Comment by vspinu** [comment]
Only arabic numbers are recognized, no kanji or any other symbols. The "strange" example is because 2 is treated as month and 8 as day, there can not be other interpretation in this particular case if you want ymd.
