### ISSUE TITLE
Loading lubridate 1.7.10 produces warning

### ISSUE THREAD

**Issue by snlf** [tidyverse/lubridate#965]
Loading lubridate 1.7.10 produces the following warning:
Failed to query server: Connection timed out
Warning in system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1

Loading lubridate 1.7.9.2 does not produce the same warning.

RStudio Server Pro Version 1.4.1106-5
R versions 4.0.3 and 4.0.4
Red Hat Linux 7.4
Linux 3.10.0-693.el7.x86_64

(First time posting issue on Github, so I am sorry if this is incorrectly formatted or missing information.)

**Comment by tedmoorman** [comment]
See #957
