### ISSUE TITLE
could not find function "ymd_hms"

### ISSUE THREAD

**Issue by AdityaUpmanyu** [tidyverse/lubridate#973]
Hey guys, I am facing the same issue as OP and I couldn't resolve it through the suggestions. It would be of great help if someone could have a look and point out my error. Here's the code:

data_2014 <- rbind(apr_data,may_data, jun_data, jul_data, aug_data, sep_data)
data_2014$Date.Time <- as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S")
data_2014$Time <- format(as.POSIXct(data_2014$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")
data_2014$Date.Time <- ymd_hms(data_2014$Date.Time)
data_2014$day <- factor(day(data_2014$Date.Time))
data_2014$month <- factor(month(data_2014$Date.Time, label = TRUE))
data_2014$year <- factor(year(data_2014$Date.Time))
data_2014$dayofweek <- factor(wday(data_2014$Date.Time, label = TRUE))

I have reinstalled all packages and restarted R Studio as well.
Below is the error I'm getting:
> data_2014$Date.Time <- ymd_hms(data_2014$Date.Time)
Error in ymd_hms(data_2014$Date.Time) : could not find function "ymd_hms"
> data_2014$day <- factor(day(data_2014$Date.Time))
Error in day(data_2014$Date.Time) : could not find function "day"
> data_2014$month <- factor(month(data_2014$Date.Time, label = TRUE))
Error in month(data_2014$Date.Time, label = TRUE) : 
  could not find function "month"
> data_2014$year <- factor(year(data_2014$Date.Time))
Error in year(data_2014$Date.Time) : could not find function "year"
> data_2014$dayofweek <- factor(wday(data_2014$Date.Time, label = TRUE))
Error in wday(data_2014$Date.Time, label = TRUE) : 
  could not find function "wday"

_Originally posted by @AdityaUpmanyu in https://github.com/tidyverse/lubridate/issues/765#issuecomment-846357194_

**Comment by vspinu** [comment]
Try installing with devtools::install_github. Your package is not installed correctly for whatever reason. Rcpp is no longer needed.
