### ISSUE TITLE
hm()'s roll = TRUE does not works properly

### ISSUE THREAD

**Issue by mopcup** [tidyverse/lubridate#975]
I executed  the following code, but "roll" argument does not work properly.
The correct output that I want is "13H 4M 0S".
If I misunderstood the specification or configuration, pls let me know how to do it. 

```r
time_hm <- hm("12:34", roll = TRUE) + minutes(30)
time_hm
> [ 1 ] "12H 64M 0S"
```

If right, I will try to submit pull request to fix it.
But, I have never done it before in any other repos.

Thanks,

**Comment by mopcup** [comment]
I found that roll = TRUE is for creating period from character or numeric.
For my purpose, what should i do...?

**Comment by vspinu** [comment]
I don't think there a function which operates on a period to do what you want. But if your periods don't have days then you can re-parse the period like this:

```
> hms(time_hm, roll = T)
[1] "13H 4M 0S"
```

For computation with periods which units hold the the amount does not matter. All representations are equivalent. It's only for visual comfort that it makes the difference.

**Comment by mopcup** [comment]
Thank you for your comment.
I think that "Period + Period" should be Period with roll = true.

I will try the way you told me.

thank you so much
