### ISSUE TITLE
Export the wday labelling functionality?

### ISSUE THREAD

**Issue by llrs** [tidyverse/lubridate#978]
Currently one can convert a day to a weekday with wday, particularly it is very useful the `label = TRUE` argument.  However, lubridate does not provide the opposite: Start with a number and convert it to a label. 

Perhaps a function could be exported that does something along:

```r
label_wday <- function(x, locale = Sys.getlocale("LC_TIME"), week_start = getOption("lubridate.week.start", 7)) {
     names <- .get_locale_regs(locale)$wday_names
     labels <- if (abbr) names$abr else names$full
    ordered(x, levels = 1:7, .shift_wday_names(labels, week_start = week_start))
}
```
Apologies if this is too trivial, but I couldn't find any other way to do this after some searches.
Also looked at the new clock package and couldn't find this. Thanks!

**Comment by vspinu** [comment]
wday works on numbers

```
> wday(2, label = T)
[1] Mon
Levels: Sun < Mon < Tue < Wed < Thu < Fri < Sat
```

Is this what you need?

**Comment by llrs** [comment]
Oh, should have tried! Yes, thanks!
