### ISSUE TITLE
mdy() fails to parse the date with the name of a month 

### ISSUE THREAD

**Issue by yetanothersu** [tidyverse/lubridate#979]
I have been recently working with "R for Data Science" and found a problem with lubridate::mdy().

When I use the name of a month (January, February, ...) with a single-digit day, it seems to fail to parse the date correctly.

```r
mdy("January 3 2010")
## [1] "2010-03-20"
mdy("January 3 (2010)")
## [1] "2010-03-20"
```

But when I put a zero with the day, it's OK.

```r
mdy("January 03 2010")
## [1] "2010-01-03"
```

I use lubridate version 1.7.10.

**Comment by jmcastagnetto** [comment]
Just a comment, under R 4.2.0 and lubridate 1.8.0, the code above produces the correct result:

```r
> mdy("January 3 2010")
[1] "2010-01-03"
> mdy("January 3 (2010)")
[1] "2010-01-03"
> mdy("January 03 2010")
[1] "2010-01-03"
> packageVersion("lubridate")
[1] ‘1.8.0’
> R.version.string
[1] "R version 4.2.0 (2022-04-22)"
```

**Comment by vspinu** [comment]
This might be a locale issue. @yetanothersu if you continue seeing this with the deelopment version please reopen and report your `Sys.getlocale("LC_TIME")`.
