### ISSUE TITLE
ym() and my() missing from website reference

### ISSUE THREAD

**Issue by averiperny** [tidyverse/lubridate#982]
It looks like the way they're exported `my()` and `ym()` should appear with year, month, and day parsers on the website's reference page (https://lubridate.tidyverse.org/reference/index.html) and the ymd function page (https://lubridate.tidyverse.org/reference/ymd.html) but I don't see them. 

I just posted an issue about a the version number not updating on the website as well and I wonder if this is related?

**Comment by vspinu** [comment]
Closing in favor of #981 It's the same issue.
