### ISSUE TITLE
stamp makes a bad choice of format

### ISSUE THREAD

**Issue by bryanosborne** [tidyverse/lubridate#983]
# Tried this code, which I believe to be correct
date_stamp <- stamp("Tuesday, September 21, 2021")
a_date <- as.POSIXct("2021-11-07 12:00:00") 
a_date
date_stamp(a_date)

Receive the following output:
> date_stamp <- stamp("Tuesday, September 21, 2021")
Multiple formats matched: "%A, %B %d, %y%H"(1), "%A, %B %y, %d%H"(1), "%A, %B %d, %Y"(1), "%A, September %H, %M%S"(1), "Tuesday, %Om %d, %y%H"(1), "Tuesday, %Om %y, %d%H"(1), "Tuesday, %Om %d, %Y"(1), "Tuesday, %B %d, %y%H"(1), "Tuesday, %B %y, %d%H"(1), "Tuesday, %B %d, %Y"(1), "Tuesday, September %H, %M%S"(1), "%A, %Om %d, %y%H"(0), "%A, %Om %y, %d%H"(0), "%A, %Om %d, %Y"(0)
Using: "%A, %B %y, %d%H"
> a_date <- as.POSIXct("2021-11-07 12:00:00") 
> a_date
[1] "2021-11-07 12:00:00 CST"
> date_stamp(a_date)
[1] "Sunday, November 21, 0712"

Running RStudio Version 1.4.1106 and "R version 4.1.0 (2021-05-18)"

**Comment by vspinu** [comment]
With `stamp` you need to supply formats explicitly, the default ones are a bit too permissive and likely will result in the wrong one being picked because there are usually multiple options. 

 Use `stamp_date` instead:

```
> st <- stamp_date("Tuesday, September 21, 2021")
Multiple formats matched: "%A, %B %d, %Y"(1), "Tuesday, %Om %d, %Y"(1), "Tuesday, %B %d, %Y"(1), "%A, %Om %d, %Y"(0)
Using: "%A, %B %d, %Y"
> st(now())
[1] "Friday, July 23, 2021"
```
