### ISSUE TITLE
Add "mm" and "dd" string return to `month()` and `day()`

### ISSUE THREAD

**Issue by matiasandina** [tidyverse/lubridate#984]
Currently, `lubridate::month()` returns either a number from 1 to 12 or a `factor` depending on the arguments passed.
I find myself often combining this with `stringr::str_pad()` as in the example

```r
# normally instead of 4 I would have a date or datetime
stringr::str_pad(lubridate::month(4), 2, pad=0)
[1] "04"
```
This is currently a minor issue, but it would be nice if `lubridate::month()` could handle this in the same way it handles `label`, for example:

```r
lubridate::month(4), string=T)
[1] "04"
```
Similar cases apply for `lubridate::day()`

**Comment by vspinu** [comment]
Thanks for the proposal but I don't think this is a common enough requirement to add a new argument. It's a one function call away and it's a established pattern if one wants a formatted number one has to call `format` or similar function. It's better for code readability I think to keep it separate.
